// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/openmetrics_data_model.proto

// The OpenMetrics protobuf schema which defines the protobuf wire format.
// Ensure to interpret "required" as semantically required for a valid message.
// All string fields MUST be UTF-8 encoded strings.

package openmetrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of a Metric.
type MetricType int32

const (
	// Unknown must use unknown MetricPoint values.
	MetricType_UNKNOWN MetricType = 0
	// Gauge must use gauge MetricPoint values.
	MetricType_GAUGE MetricType = 1
	// Counter must use counter MetricPoint values.
	MetricType_COUNTER MetricType = 2
	// State set must use state set MetricPoint values.
	MetricType_STATE_SET MetricType = 3
	// Info must use info MetricPoint values.
	MetricType_INFO MetricType = 4
	// Histogram must use histogram value MetricPoint values.
	MetricType_HISTOGRAM MetricType = 5
	// Gauge histogram must use histogram value MetricPoint values.
	MetricType_GAUGE_HISTOGRAM MetricType = 6
	// Summary quantiles must use summary value MetricPoint values.
	MetricType_SUMMARY MetricType = 7
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "UNKNOWN",
		1: "GAUGE",
		2: "COUNTER",
		3: "STATE_SET",
		4: "INFO",
		5: "HISTOGRAM",
		6: "GAUGE_HISTOGRAM",
		7: "SUMMARY",
	}
	MetricType_value = map[string]int32{
		"UNKNOWN":         0,
		"GAUGE":           1,
		"COUNTER":         2,
		"STATE_SET":       3,
		"INFO":            4,
		"HISTOGRAM":       5,
		"GAUGE_HISTOGRAM": 6,
		"SUMMARY":         7,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_openmetrics_data_model_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_streamlit_proto_openmetrics_data_model_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{0}
}

// The top-level container type that is encoded and sent over the wire.
type MetricSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each MetricFamily has one or more MetricPoints for a single Metric.
	MetricFamilies []*MetricFamily `protobuf:"bytes,1,rep,name=metric_families,json=metricFamilies,proto3" json:"metric_families,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricSet) Reset() {
	*x = MetricSet{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSet) ProtoMessage() {}

func (x *MetricSet) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSet.ProtoReflect.Descriptor instead.
func (*MetricSet) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{0}
}

func (x *MetricSet) GetMetricFamilies() []*MetricFamily {
	if x != nil {
		return x.MetricFamilies
	}
	return nil
}

// One or more Metrics for a single MetricFamily, where each Metric
// has one or more MetricPoints.
type MetricFamily struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional.
	Type MetricType `protobuf:"varint,2,opt,name=type,proto3,enum=openmetrics.MetricType" json:"type,omitempty"`
	// Optional.
	Unit string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	// Optional.
	Help string `protobuf:"bytes,4,opt,name=help,proto3" json:"help,omitempty"`
	// Optional.
	Metrics       []*Metric `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricFamily) Reset() {
	*x = MetricFamily{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricFamily) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricFamily) ProtoMessage() {}

func (x *MetricFamily) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricFamily.ProtoReflect.Descriptor instead.
func (*MetricFamily) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{1}
}

func (x *MetricFamily) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricFamily) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_UNKNOWN
}

func (x *MetricFamily) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricFamily) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *MetricFamily) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// A single metric with a unique set of labels within a metric family.
type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional.
	Labels []*Label `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	// Optional.
	MetricPoints  []*MetricPoint `protobuf:"bytes,2,rep,name=metric_points,json=metricPoints,proto3" json:"metric_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{2}
}

func (x *Metric) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metric) GetMetricPoints() []*MetricPoint {
	if x != nil {
		return x.MetricPoints
	}
	return nil
}

// A name-value pair. These are used in multiple places: identifying
// timeseries, value of INFO metrics, and exemplars in Histograms.
type Label struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{3}
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// A MetricPoint in a Metric.
type MetricPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*MetricPoint_UnknownValue
	//	*MetricPoint_GaugeValue
	//	*MetricPoint_CounterValue
	//	*MetricPoint_HistogramValue
	//	*MetricPoint_StateSetValue
	//	*MetricPoint_InfoValue
	//	*MetricPoint_SummaryValue
	Value isMetricPoint_Value `protobuf_oneof:"value"`
	// Optional.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{4}
}

func (x *MetricPoint) GetValue() isMetricPoint_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetricPoint) GetUnknownValue() *UnknownValue {
	if x != nil {
		if x, ok := x.Value.(*MetricPoint_UnknownValue); ok {
			return x.UnknownValue
		}
	}
	return nil
}

func (x *MetricPoint) GetGaugeValue() *GaugeValue {
	if x != nil {
		if x, ok := x.Value.(*MetricPoint_GaugeValue); ok {
			return x.GaugeValue
		}
	}
	return nil
}

func (x *MetricPoint) GetCounterValue() *CounterValue {
	if x != nil {
		if x, ok := x.Value.(*MetricPoint_CounterValue); ok {
			return x.CounterValue
		}
	}
	return nil
}

func (x *MetricPoint) GetHistogramValue() *HistogramValue {
	if x != nil {
		if x, ok := x.Value.(*MetricPoint_HistogramValue); ok {
			return x.HistogramValue
		}
	}
	return nil
}

func (x *MetricPoint) GetStateSetValue() *StateSetValue {
	if x != nil {
		if x, ok := x.Value.(*MetricPoint_StateSetValue); ok {
			return x.StateSetValue
		}
	}
	return nil
}

func (x *MetricPoint) GetInfoValue() *InfoValue {
	if x != nil {
		if x, ok := x.Value.(*MetricPoint_InfoValue); ok {
			return x.InfoValue
		}
	}
	return nil
}

func (x *MetricPoint) GetSummaryValue() *SummaryValue {
	if x != nil {
		if x, ok := x.Value.(*MetricPoint_SummaryValue); ok {
			return x.SummaryValue
		}
	}
	return nil
}

func (x *MetricPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type isMetricPoint_Value interface {
	isMetricPoint_Value()
}

type MetricPoint_UnknownValue struct {
	UnknownValue *UnknownValue `protobuf:"bytes,1,opt,name=unknown_value,json=unknownValue,proto3,oneof"`
}

type MetricPoint_GaugeValue struct {
	GaugeValue *GaugeValue `protobuf:"bytes,2,opt,name=gauge_value,json=gaugeValue,proto3,oneof"`
}

type MetricPoint_CounterValue struct {
	CounterValue *CounterValue `protobuf:"bytes,3,opt,name=counter_value,json=counterValue,proto3,oneof"`
}

type MetricPoint_HistogramValue struct {
	HistogramValue *HistogramValue `protobuf:"bytes,4,opt,name=histogram_value,json=histogramValue,proto3,oneof"`
}

type MetricPoint_StateSetValue struct {
	StateSetValue *StateSetValue `protobuf:"bytes,5,opt,name=state_set_value,json=stateSetValue,proto3,oneof"`
}

type MetricPoint_InfoValue struct {
	InfoValue *InfoValue `protobuf:"bytes,6,opt,name=info_value,json=infoValue,proto3,oneof"`
}

type MetricPoint_SummaryValue struct {
	SummaryValue *SummaryValue `protobuf:"bytes,7,opt,name=summary_value,json=summaryValue,proto3,oneof"`
}

func (*MetricPoint_UnknownValue) isMetricPoint_Value() {}

func (*MetricPoint_GaugeValue) isMetricPoint_Value() {}

func (*MetricPoint_CounterValue) isMetricPoint_Value() {}

func (*MetricPoint_HistogramValue) isMetricPoint_Value() {}

func (*MetricPoint_StateSetValue) isMetricPoint_Value() {}

func (*MetricPoint_InfoValue) isMetricPoint_Value() {}

func (*MetricPoint_SummaryValue) isMetricPoint_Value() {}

// Value for UNKNOWN MetricPoint.
type UnknownValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*UnknownValue_DoubleValue
	//	*UnknownValue_IntValue
	Value         isUnknownValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnknownValue) Reset() {
	*x = UnknownValue{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnknownValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnknownValue) ProtoMessage() {}

func (x *UnknownValue) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnknownValue.ProtoReflect.Descriptor instead.
func (*UnknownValue) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{5}
}

func (x *UnknownValue) GetValue() isUnknownValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UnknownValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*UnknownValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *UnknownValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*UnknownValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

type isUnknownValue_Value interface {
	isUnknownValue_Value()
}

type UnknownValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,1,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type UnknownValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*UnknownValue_DoubleValue) isUnknownValue_Value() {}

func (*UnknownValue_IntValue) isUnknownValue_Value() {}

// Value for GAUGE MetricPoint.
type GaugeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*GaugeValue_DoubleValue
	//	*GaugeValue_IntValue
	Value         isGaugeValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GaugeValue) Reset() {
	*x = GaugeValue{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GaugeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaugeValue) ProtoMessage() {}

func (x *GaugeValue) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaugeValue.ProtoReflect.Descriptor instead.
func (*GaugeValue) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{6}
}

func (x *GaugeValue) GetValue() isGaugeValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GaugeValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*GaugeValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *GaugeValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*GaugeValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

type isGaugeValue_Value interface {
	isGaugeValue_Value()
}

type GaugeValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,1,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type GaugeValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*GaugeValue_DoubleValue) isGaugeValue_Value() {}

func (*GaugeValue_IntValue) isGaugeValue_Value() {}

// Value for COUNTER MetricPoint.
type CounterValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	//
	// Types that are valid to be assigned to Total:
	//
	//	*CounterValue_DoubleValue
	//	*CounterValue_IntValue
	Total isCounterValue_Total `protobuf_oneof:"total"`
	// The time values began being collected for this counter.
	// Optional.
	Created *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	// Optional.
	Exemplar      *Exemplar `protobuf:"bytes,4,opt,name=exemplar,proto3" json:"exemplar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterValue) Reset() {
	*x = CounterValue{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterValue) ProtoMessage() {}

func (x *CounterValue) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterValue.ProtoReflect.Descriptor instead.
func (*CounterValue) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{7}
}

func (x *CounterValue) GetTotal() isCounterValue_Total {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *CounterValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Total.(*CounterValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *CounterValue) GetIntValue() uint64 {
	if x != nil {
		if x, ok := x.Total.(*CounterValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *CounterValue) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *CounterValue) GetExemplar() *Exemplar {
	if x != nil {
		return x.Exemplar
	}
	return nil
}

type isCounterValue_Total interface {
	isCounterValue_Total()
}

type CounterValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,1,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type CounterValue_IntValue struct {
	IntValue uint64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*CounterValue_DoubleValue) isCounterValue_Total() {}

func (*CounterValue_IntValue) isCounterValue_Total() {}

// Value for HISTOGRAM or GAUGE_HISTOGRAM MetricPoint.
type HistogramValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional.
	//
	// Types that are valid to be assigned to Sum:
	//
	//	*HistogramValue_DoubleValue
	//	*HistogramValue_IntValue
	Sum isHistogramValue_Sum `protobuf_oneof:"sum"`
	// Optional.
	Count uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// The time values began being collected for this histogram.
	// Optional.
	Created *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	// Optional.
	Buckets       []*HistogramValue_Bucket `protobuf:"bytes,5,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramValue) Reset() {
	*x = HistogramValue{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramValue) ProtoMessage() {}

func (x *HistogramValue) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramValue.ProtoReflect.Descriptor instead.
func (*HistogramValue) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{8}
}

func (x *HistogramValue) GetSum() isHistogramValue_Sum {
	if x != nil {
		return x.Sum
	}
	return nil
}

func (x *HistogramValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Sum.(*HistogramValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *HistogramValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Sum.(*HistogramValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *HistogramValue) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *HistogramValue) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *HistogramValue) GetBuckets() []*HistogramValue_Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type isHistogramValue_Sum interface {
	isHistogramValue_Sum()
}

type HistogramValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,1,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type HistogramValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*HistogramValue_DoubleValue) isHistogramValue_Sum() {}

func (*HistogramValue_IntValue) isHistogramValue_Sum() {}

type Exemplar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	// Optional.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Labels are additional information about the exemplar value (e.g. trace id).
	// Optional.
	Label         []*Label `protobuf:"bytes,3,rep,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exemplar) Reset() {
	*x = Exemplar{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exemplar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exemplar) ProtoMessage() {}

func (x *Exemplar) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exemplar.ProtoReflect.Descriptor instead.
func (*Exemplar) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{9}
}

func (x *Exemplar) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Exemplar) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Exemplar) GetLabel() []*Label {
	if x != nil {
		return x.Label
	}
	return nil
}

// Value for STATE_SET MetricPoint.
type StateSetValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional.
	States        []*StateSetValue_State `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSetValue) Reset() {
	*x = StateSetValue{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSetValue) ProtoMessage() {}

func (x *StateSetValue) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSetValue.ProtoReflect.Descriptor instead.
func (*StateSetValue) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{10}
}

func (x *StateSetValue) GetStates() []*StateSetValue_State {
	if x != nil {
		return x.States
	}
	return nil
}

// Value for INFO MetricPoint.
type InfoValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional.
	Info          []*Label `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoValue) Reset() {
	*x = InfoValue{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoValue) ProtoMessage() {}

func (x *InfoValue) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoValue.ProtoReflect.Descriptor instead.
func (*InfoValue) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{11}
}

func (x *InfoValue) GetInfo() []*Label {
	if x != nil {
		return x.Info
	}
	return nil
}

// Value for SUMMARY MetricPoint.
type SummaryValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional.
	//
	// Types that are valid to be assigned to Sum:
	//
	//	*SummaryValue_DoubleValue
	//	*SummaryValue_IntValue
	Sum isSummaryValue_Sum `protobuf_oneof:"sum"`
	// Optional.
	Count uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// The time sum and count values began being collected for this summary.
	// Optional.
	Created *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	// Optional.
	Quantile      []*SummaryValue_Quantile `protobuf:"bytes,5,rep,name=quantile,proto3" json:"quantile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryValue) Reset() {
	*x = SummaryValue{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryValue) ProtoMessage() {}

func (x *SummaryValue) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryValue.ProtoReflect.Descriptor instead.
func (*SummaryValue) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{12}
}

func (x *SummaryValue) GetSum() isSummaryValue_Sum {
	if x != nil {
		return x.Sum
	}
	return nil
}

func (x *SummaryValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Sum.(*SummaryValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *SummaryValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Sum.(*SummaryValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *SummaryValue) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SummaryValue) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *SummaryValue) GetQuantile() []*SummaryValue_Quantile {
	if x != nil {
		return x.Quantile
	}
	return nil
}

type isSummaryValue_Sum interface {
	isSummaryValue_Sum()
}

type SummaryValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,1,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type SummaryValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*SummaryValue_DoubleValue) isSummaryValue_Sum() {}

func (*SummaryValue_IntValue) isSummaryValue_Sum() {}

// Bucket is the number of values for a bucket in the histogram
// with an optional exemplar.
type HistogramValue_Bucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// Optional.
	UpperBound float64 `protobuf:"fixed64,2,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	// Optional.
	Exemplar      *Exemplar `protobuf:"bytes,3,opt,name=exemplar,proto3" json:"exemplar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramValue_Bucket) Reset() {
	*x = HistogramValue_Bucket{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramValue_Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramValue_Bucket) ProtoMessage() {}

func (x *HistogramValue_Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramValue_Bucket.ProtoReflect.Descriptor instead.
func (*HistogramValue_Bucket) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{8, 0}
}

func (x *HistogramValue_Bucket) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *HistogramValue_Bucket) GetUpperBound() float64 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

func (x *HistogramValue_Bucket) GetExemplar() *Exemplar {
	if x != nil {
		return x.Exemplar
	}
	return nil
}

type StateSetValue_State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Required.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSetValue_State) Reset() {
	*x = StateSetValue_State{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSetValue_State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSetValue_State) ProtoMessage() {}

func (x *StateSetValue_State) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSetValue_State.ProtoReflect.Descriptor instead.
func (*StateSetValue_State) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{10, 0}
}

func (x *StateSetValue_State) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StateSetValue_State) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SummaryValue_Quantile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Quantile float64 `protobuf:"fixed64,1,opt,name=quantile,proto3" json:"quantile,omitempty"`
	// Required.
	Value         float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryValue_Quantile) Reset() {
	*x = SummaryValue_Quantile{}
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryValue_Quantile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryValue_Quantile) ProtoMessage() {}

func (x *SummaryValue_Quantile) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_openmetrics_data_model_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryValue_Quantile.ProtoReflect.Descriptor instead.
func (*SummaryValue_Quantile) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP(), []int{12, 0}
}

func (x *SummaryValue_Quantile) GetQuantile() float64 {
	if x != nil {
		return x.Quantile
	}
	return 0
}

func (x *SummaryValue_Quantile) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_streamlit_proto_openmetrics_data_model_proto protoreflect.FileDescriptor

const file_streamlit_proto_openmetrics_data_model_proto_rawDesc = "" +
	"\n" +
	",streamlit/proto/openmetrics_data_model.proto\x12\vopenmetrics\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n" +
	"\tMetricSet\x12B\n" +
	"\x0fmetric_families\x18\x01 \x03(\v2\x19.openmetrics.MetricFamilyR\x0emetricFamilies\"\xa6\x01\n" +
	"\fMetricFamily\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.openmetrics.MetricTypeR\x04type\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x12\n" +
	"\x04help\x18\x04 \x01(\tR\x04help\x12-\n" +
	"\ametrics\x18\x05 \x03(\v2\x13.openmetrics.MetricR\ametrics\"s\n" +
	"\x06Metric\x12*\n" +
	"\x06labels\x18\x01 \x03(\v2\x12.openmetrics.LabelR\x06labels\x12=\n" +
	"\rmetric_points\x18\x02 \x03(\v2\x18.openmetrics.MetricPointR\fmetricPoints\"1\n" +
	"\x05Label\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x99\x04\n" +
	"\vMetricPoint\x12@\n" +
	"\runknown_value\x18\x01 \x01(\v2\x19.openmetrics.UnknownValueH\x00R\funknownValue\x12:\n" +
	"\vgauge_value\x18\x02 \x01(\v2\x17.openmetrics.GaugeValueH\x00R\n" +
	"gaugeValue\x12@\n" +
	"\rcounter_value\x18\x03 \x01(\v2\x19.openmetrics.CounterValueH\x00R\fcounterValue\x12F\n" +
	"\x0fhistogram_value\x18\x04 \x01(\v2\x1b.openmetrics.HistogramValueH\x00R\x0ehistogramValue\x12D\n" +
	"\x0fstate_set_value\x18\x05 \x01(\v2\x1a.openmetrics.StateSetValueH\x00R\rstateSetValue\x127\n" +
	"\n" +
	"info_value\x18\x06 \x01(\v2\x16.openmetrics.InfoValueH\x00R\tinfoValue\x12@\n" +
	"\rsummary_value\x18\a \x01(\v2\x19.openmetrics.SummaryValueH\x00R\fsummaryValue\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\a\n" +
	"\x05value\"[\n" +
	"\fUnknownValue\x12#\n" +
	"\fdouble_value\x18\x01 \x01(\x01H\x00R\vdoubleValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValueB\a\n" +
	"\x05value\"Y\n" +
	"\n" +
	"GaugeValue\x12#\n" +
	"\fdouble_value\x18\x01 \x01(\x01H\x00R\vdoubleValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValueB\a\n" +
	"\x05value\"\xc4\x01\n" +
	"\fCounterValue\x12#\n" +
	"\fdouble_value\x18\x01 \x01(\x01H\x00R\vdoubleValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x04H\x00R\bintValue\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x121\n" +
	"\bexemplar\x18\x04 \x01(\v2\x15.openmetrics.ExemplarR\bexemplarB\a\n" +
	"\x05total\"\xd9\x02\n" +
	"\x0eHistogramValue\x12#\n" +
	"\fdouble_value\x18\x01 \x01(\x01H\x00R\vdoubleValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\x124\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12<\n" +
	"\abuckets\x18\x05 \x03(\v2\".openmetrics.HistogramValue.BucketR\abuckets\x1ar\n" +
	"\x06Bucket\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\x12\x1f\n" +
	"\vupper_bound\x18\x02 \x01(\x01R\n" +
	"upperBound\x121\n" +
	"\bexemplar\x18\x03 \x01(\v2\x15.openmetrics.ExemplarR\bexemplarB\x05\n" +
	"\x03sum\"\x84\x01\n" +
	"\bExemplar\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12(\n" +
	"\x05label\x18\x03 \x03(\v2\x12.openmetrics.LabelR\x05label\"\x80\x01\n" +
	"\rStateSetValue\x128\n" +
	"\x06states\x18\x01 \x03(\v2 .openmetrics.StateSetValue.StateR\x06states\x1a5\n" +
	"\x05State\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"3\n" +
	"\tInfoValue\x12&\n" +
	"\x04info\x18\x01 \x03(\v2\x12.openmetrics.LabelR\x04info\"\xa3\x02\n" +
	"\fSummaryValue\x12#\n" +
	"\fdouble_value\x18\x01 \x01(\x01H\x00R\vdoubleValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\x124\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12>\n" +
	"\bquantile\x18\x05 \x03(\v2\".openmetrics.SummaryValue.QuantileR\bquantile\x1a<\n" +
	"\bQuantile\x12\x1a\n" +
	"\bquantile\x18\x01 \x01(\x01R\bquantile\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05valueB\x05\n" +
	"\x03sum*{\n" +
	"\n" +
	"MetricType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05GAUGE\x10\x01\x12\v\n" +
	"\aCOUNTER\x10\x02\x12\r\n" +
	"\tSTATE_SET\x10\x03\x12\b\n" +
	"\x04INFO\x10\x04\x12\r\n" +
	"\tHISTOGRAM\x10\x05\x12\x13\n" +
	"\x0fGAUGE_HISTOGRAM\x10\x06\x12\v\n" +
	"\aSUMMARY\x10\aB=Z;github.com/streamlit/streamlit/go-backend/proto/openmetricsb\x06proto3"

var (
	file_streamlit_proto_openmetrics_data_model_proto_rawDescOnce sync.Once
	file_streamlit_proto_openmetrics_data_model_proto_rawDescData []byte
)

func file_streamlit_proto_openmetrics_data_model_proto_rawDescGZIP() []byte {
	file_streamlit_proto_openmetrics_data_model_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_openmetrics_data_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_openmetrics_data_model_proto_rawDesc), len(file_streamlit_proto_openmetrics_data_model_proto_rawDesc)))
	})
	return file_streamlit_proto_openmetrics_data_model_proto_rawDescData
}

var file_streamlit_proto_openmetrics_data_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_openmetrics_data_model_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_streamlit_proto_openmetrics_data_model_proto_goTypes = []any{
	(MetricType)(0),               // 0: openmetrics.MetricType
	(*MetricSet)(nil),             // 1: openmetrics.MetricSet
	(*MetricFamily)(nil),          // 2: openmetrics.MetricFamily
	(*Metric)(nil),                // 3: openmetrics.Metric
	(*Label)(nil),                 // 4: openmetrics.Label
	(*MetricPoint)(nil),           // 5: openmetrics.MetricPoint
	(*UnknownValue)(nil),          // 6: openmetrics.UnknownValue
	(*GaugeValue)(nil),            // 7: openmetrics.GaugeValue
	(*CounterValue)(nil),          // 8: openmetrics.CounterValue
	(*HistogramValue)(nil),        // 9: openmetrics.HistogramValue
	(*Exemplar)(nil),              // 10: openmetrics.Exemplar
	(*StateSetValue)(nil),         // 11: openmetrics.StateSetValue
	(*InfoValue)(nil),             // 12: openmetrics.InfoValue
	(*SummaryValue)(nil),          // 13: openmetrics.SummaryValue
	(*HistogramValue_Bucket)(nil), // 14: openmetrics.HistogramValue.Bucket
	(*StateSetValue_State)(nil),   // 15: openmetrics.StateSetValue.State
	(*SummaryValue_Quantile)(nil), // 16: openmetrics.SummaryValue.Quantile
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_streamlit_proto_openmetrics_data_model_proto_depIdxs = []int32{
	2,  // 0: openmetrics.MetricSet.metric_families:type_name -> openmetrics.MetricFamily
	0,  // 1: openmetrics.MetricFamily.type:type_name -> openmetrics.MetricType
	3,  // 2: openmetrics.MetricFamily.metrics:type_name -> openmetrics.Metric
	4,  // 3: openmetrics.Metric.labels:type_name -> openmetrics.Label
	5,  // 4: openmetrics.Metric.metric_points:type_name -> openmetrics.MetricPoint
	6,  // 5: openmetrics.MetricPoint.unknown_value:type_name -> openmetrics.UnknownValue
	7,  // 6: openmetrics.MetricPoint.gauge_value:type_name -> openmetrics.GaugeValue
	8,  // 7: openmetrics.MetricPoint.counter_value:type_name -> openmetrics.CounterValue
	9,  // 8: openmetrics.MetricPoint.histogram_value:type_name -> openmetrics.HistogramValue
	11, // 9: openmetrics.MetricPoint.state_set_value:type_name -> openmetrics.StateSetValue
	12, // 10: openmetrics.MetricPoint.info_value:type_name -> openmetrics.InfoValue
	13, // 11: openmetrics.MetricPoint.summary_value:type_name -> openmetrics.SummaryValue
	17, // 12: openmetrics.MetricPoint.timestamp:type_name -> google.protobuf.Timestamp
	17, // 13: openmetrics.CounterValue.created:type_name -> google.protobuf.Timestamp
	10, // 14: openmetrics.CounterValue.exemplar:type_name -> openmetrics.Exemplar
	17, // 15: openmetrics.HistogramValue.created:type_name -> google.protobuf.Timestamp
	14, // 16: openmetrics.HistogramValue.buckets:type_name -> openmetrics.HistogramValue.Bucket
	17, // 17: openmetrics.Exemplar.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 18: openmetrics.Exemplar.label:type_name -> openmetrics.Label
	15, // 19: openmetrics.StateSetValue.states:type_name -> openmetrics.StateSetValue.State
	4,  // 20: openmetrics.InfoValue.info:type_name -> openmetrics.Label
	17, // 21: openmetrics.SummaryValue.created:type_name -> google.protobuf.Timestamp
	16, // 22: openmetrics.SummaryValue.quantile:type_name -> openmetrics.SummaryValue.Quantile
	10, // 23: openmetrics.HistogramValue.Bucket.exemplar:type_name -> openmetrics.Exemplar
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_streamlit_proto_openmetrics_data_model_proto_init() }
func file_streamlit_proto_openmetrics_data_model_proto_init() {
	if File_streamlit_proto_openmetrics_data_model_proto != nil {
		return
	}
	file_streamlit_proto_openmetrics_data_model_proto_msgTypes[4].OneofWrappers = []any{
		(*MetricPoint_UnknownValue)(nil),
		(*MetricPoint_GaugeValue)(nil),
		(*MetricPoint_CounterValue)(nil),
		(*MetricPoint_HistogramValue)(nil),
		(*MetricPoint_StateSetValue)(nil),
		(*MetricPoint_InfoValue)(nil),
		(*MetricPoint_SummaryValue)(nil),
	}
	file_streamlit_proto_openmetrics_data_model_proto_msgTypes[5].OneofWrappers = []any{
		(*UnknownValue_DoubleValue)(nil),
		(*UnknownValue_IntValue)(nil),
	}
	file_streamlit_proto_openmetrics_data_model_proto_msgTypes[6].OneofWrappers = []any{
		(*GaugeValue_DoubleValue)(nil),
		(*GaugeValue_IntValue)(nil),
	}
	file_streamlit_proto_openmetrics_data_model_proto_msgTypes[7].OneofWrappers = []any{
		(*CounterValue_DoubleValue)(nil),
		(*CounterValue_IntValue)(nil),
	}
	file_streamlit_proto_openmetrics_data_model_proto_msgTypes[8].OneofWrappers = []any{
		(*HistogramValue_DoubleValue)(nil),
		(*HistogramValue_IntValue)(nil),
	}
	file_streamlit_proto_openmetrics_data_model_proto_msgTypes[12].OneofWrappers = []any{
		(*SummaryValue_DoubleValue)(nil),
		(*SummaryValue_IntValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_openmetrics_data_model_proto_rawDesc), len(file_streamlit_proto_openmetrics_data_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_openmetrics_data_model_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_openmetrics_data_model_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_openmetrics_data_model_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_openmetrics_data_model_proto_msgTypes,
	}.Build()
	File_streamlit_proto_openmetrics_data_model_proto = out.File
	file_streamlit_proto_openmetrics_data_model_proto_goTypes = nil
	file_streamlit_proto_openmetrics_data_model_proto_depIdxs = nil
}
