//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/AudioInput.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label           string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Help            string                 `protobuf:"bytes,3,opt,name=help,proto3" json:"help,omitempty"`
	FormId          string                 `protobuf:"bytes,4,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Disabled        bool                   `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	LabelVisibility *LabelVisibility       `protobuf:"bytes,6,opt,name=label_visibility,json=labelVisibility,proto3" json:"label_visibility,omitempty"`
	SampleRate      *int32                 `protobuf:"varint,7,opt,name=sample_rate,json=sampleRate,proto3,oneof" json:"sample_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AudioInput) Reset() {
	*x = AudioInput{}
	mi := &file_streamlit_proto_AudioInput_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioInput) ProtoMessage() {}

func (x *AudioInput) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_AudioInput_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioInput.ProtoReflect.Descriptor instead.
func (*AudioInput) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_AudioInput_proto_rawDescGZIP(), []int{0}
}

func (x *AudioInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AudioInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AudioInput) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *AudioInput) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *AudioInput) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *AudioInput) GetLabelVisibility() *LabelVisibility {
	if x != nil {
		return x.LabelVisibility
	}
	return nil
}

func (x *AudioInput) GetSampleRate() int32 {
	if x != nil && x.SampleRate != nil {
		return *x.SampleRate
	}
	return 0
}

var File_streamlit_proto_AudioInput_proto protoreflect.FileDescriptor

const file_streamlit_proto_AudioInput_proto_rawDesc = "" +
	"\n" +
	" streamlit/proto/AudioInput.proto\x1a%streamlit/proto/LabelVisibility.proto\"\xee\x01\n" +
	"\n" +
	"AudioInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04help\x18\x03 \x01(\tR\x04help\x12\x17\n" +
	"\aform_id\x18\x04 \x01(\tR\x06formId\x12\x1a\n" +
	"\bdisabled\x18\x05 \x01(\bR\bdisabled\x12;\n" +
	"\x10label_visibility\x18\x06 \x01(\v2\x10.LabelVisibilityR\x0flabelVisibility\x12$\n" +
	"\vsample_rate\x18\a \x01(\x05H\x00R\n" +
	"sampleRate\x88\x01\x01B\x0e\n" +
	"\f_sample_rateB1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_AudioInput_proto_rawDescOnce sync.Once
	file_streamlit_proto_AudioInput_proto_rawDescData []byte
)

func file_streamlit_proto_AudioInput_proto_rawDescGZIP() []byte {
	file_streamlit_proto_AudioInput_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_AudioInput_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_AudioInput_proto_rawDesc), len(file_streamlit_proto_AudioInput_proto_rawDesc)))
	})
	return file_streamlit_proto_AudioInput_proto_rawDescData
}

var file_streamlit_proto_AudioInput_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_AudioInput_proto_goTypes = []any{
	(*AudioInput)(nil),      // 0: AudioInput
	(*LabelVisibility)(nil), // 1: LabelVisibility
}
var file_streamlit_proto_AudioInput_proto_depIdxs = []int32{
	1, // 0: AudioInput.label_visibility:type_name -> LabelVisibility
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_AudioInput_proto_init() }
func file_streamlit_proto_AudioInput_proto_init() {
	if File_streamlit_proto_AudioInput_proto != nil {
		return
	}
	file_streamlit_proto_LabelVisibility_proto_init()
	file_streamlit_proto_AudioInput_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_AudioInput_proto_rawDesc), len(file_streamlit_proto_AudioInput_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_AudioInput_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_AudioInput_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_AudioInput_proto_msgTypes,
	}.Build()
	File_streamlit_proto_AudioInput_proto = out.File
	file_streamlit_proto_AudioInput_proto_goTypes = nil
	file_streamlit_proto_AudioInput_proto_depIdxs = nil
}
