//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/AutoRerun.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AutoRerun struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The interval of reruns in seconds
	Interval float32 `protobuf:"fixed32,1,opt,name=interval,proto3" json:"interval,omitempty"`
	// The fragment ID to rerun
	FragmentId    string `protobuf:"bytes,2,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoRerun) Reset() {
	*x = AutoRerun{}
	mi := &file_streamlit_proto_AutoRerun_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoRerun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoRerun) ProtoMessage() {}

func (x *AutoRerun) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_AutoRerun_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoRerun.ProtoReflect.Descriptor instead.
func (*AutoRerun) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_AutoRerun_proto_rawDescGZIP(), []int{0}
}

func (x *AutoRerun) GetInterval() float32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *AutoRerun) GetFragmentId() string {
	if x != nil {
		return x.FragmentId
	}
	return ""
}

var File_streamlit_proto_AutoRerun_proto protoreflect.FileDescriptor

const file_streamlit_proto_AutoRerun_proto_rawDesc = "" +
	"\n" +
	"\x1fstreamlit/proto/AutoRerun.proto\"H\n" +
	"\tAutoRerun\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x02R\binterval\x12\x1f\n" +
	"\vfragment_id\x18\x02 \x01(\tR\n" +
	"fragmentIdB1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_AutoRerun_proto_rawDescOnce sync.Once
	file_streamlit_proto_AutoRerun_proto_rawDescData []byte
)

func file_streamlit_proto_AutoRerun_proto_rawDescGZIP() []byte {
	file_streamlit_proto_AutoRerun_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_AutoRerun_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_AutoRerun_proto_rawDesc), len(file_streamlit_proto_AutoRerun_proto_rawDesc)))
	})
	return file_streamlit_proto_AutoRerun_proto_rawDescData
}

var file_streamlit_proto_AutoRerun_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_AutoRerun_proto_goTypes = []any{
	(*AutoRerun)(nil), // 0: AutoRerun
}
var file_streamlit_proto_AutoRerun_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streamlit_proto_AutoRerun_proto_init() }
func file_streamlit_proto_AutoRerun_proto_init() {
	if File_streamlit_proto_AutoRerun_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_AutoRerun_proto_rawDesc), len(file_streamlit_proto_AutoRerun_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_AutoRerun_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_AutoRerun_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_AutoRerun_proto_msgTypes,
	}.Build()
	File_streamlit_proto_AutoRerun_proto = out.File
	file_streamlit_proto_AutoRerun_proto_goTypes = nil
	file_streamlit_proto_AutoRerun_proto_depIdxs = nil
}
