//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/BidiComponent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mixed data structure that allows JSON with embedded Arrow references
type MixedData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The main JSON structure with arrow references replaced by placeholders
	Json string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	// Map of arrow data blobs keyed by reference ID
	ArrowBlobs    map[string]*ArrowData `protobuf:"bytes,2,rep,name=arrow_blobs,json=arrowBlobs,proto3" json:"arrow_blobs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MixedData) Reset() {
	*x = MixedData{}
	mi := &file_streamlit_proto_BidiComponent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MixedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MixedData) ProtoMessage() {}

func (x *MixedData) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_BidiComponent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MixedData.ProtoReflect.Descriptor instead.
func (*MixedData) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_BidiComponent_proto_rawDescGZIP(), []int{0}
}

func (x *MixedData) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *MixedData) GetArrowBlobs() map[string]*ArrowData {
	if x != nil {
		return x.ArrowBlobs
	}
	return nil
}

// Represents an instance of a bidirectional component.
type BidiComponent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the widget instance.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The registered name of the component.
	ComponentName string `protobuf:"bytes,2,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	// The JavaScript content provided by the developer.
	JsContent *string `protobuf:"bytes,3,opt,name=js_content,json=jsContent,proto3,oneof" json:"js_content,omitempty"`
	// The source path for the JavaScript content.
	JsSourcePath *string `protobuf:"bytes,4,opt,name=js_source_path,json=jsSourcePath,proto3,oneof" json:"js_source_path,omitempty"`
	// The ID of the form this component belongs to, if any.
	FormId string `protobuf:"bytes,5,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	// The HTML content provided by the developer.
	HtmlContent *string `protobuf:"bytes,6,opt,name=html_content,json=htmlContent,proto3,oneof" json:"html_content,omitempty"`
	// The CSS content provided by the developer.
	CssContent *string `protobuf:"bytes,7,opt,name=css_content,json=cssContent,proto3,oneof" json:"css_content,omitempty"`
	// The source path for the CSS content.
	CssSourcePath *string `protobuf:"bytes,8,opt,name=css_source_path,json=cssSourcePath,proto3,oneof" json:"css_source_path,omitempty"`
	// Whether to isolate styles from the parent.
	IsolateStyles bool `protobuf:"varint,9,opt,name=isolate_styles,json=isolateStyles,proto3" json:"isolate_styles,omitempty"`
	// The component's data payload. Exactly one of the following fields
	// will be set at any given time.
	//
	// Types that are valid to be assigned to Data:
	//
	//	*BidiComponent_Json
	//	*BidiComponent_ArrowData
	//	*BidiComponent_Bytes
	//	*BidiComponent_Mixed
	Data          isBidiComponent_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidiComponent) Reset() {
	*x = BidiComponent{}
	mi := &file_streamlit_proto_BidiComponent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidiComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiComponent) ProtoMessage() {}

func (x *BidiComponent) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_BidiComponent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiComponent.ProtoReflect.Descriptor instead.
func (*BidiComponent) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_BidiComponent_proto_rawDescGZIP(), []int{1}
}

func (x *BidiComponent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BidiComponent) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *BidiComponent) GetJsContent() string {
	if x != nil && x.JsContent != nil {
		return *x.JsContent
	}
	return ""
}

func (x *BidiComponent) GetJsSourcePath() string {
	if x != nil && x.JsSourcePath != nil {
		return *x.JsSourcePath
	}
	return ""
}

func (x *BidiComponent) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *BidiComponent) GetHtmlContent() string {
	if x != nil && x.HtmlContent != nil {
		return *x.HtmlContent
	}
	return ""
}

func (x *BidiComponent) GetCssContent() string {
	if x != nil && x.CssContent != nil {
		return *x.CssContent
	}
	return ""
}

func (x *BidiComponent) GetCssSourcePath() string {
	if x != nil && x.CssSourcePath != nil {
		return *x.CssSourcePath
	}
	return ""
}

func (x *BidiComponent) GetIsolateStyles() bool {
	if x != nil {
		return x.IsolateStyles
	}
	return false
}

func (x *BidiComponent) GetData() isBidiComponent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BidiComponent) GetJson() string {
	if x != nil {
		if x, ok := x.Data.(*BidiComponent_Json); ok {
			return x.Json
		}
	}
	return ""
}

func (x *BidiComponent) GetArrowData() *ArrowData {
	if x != nil {
		if x, ok := x.Data.(*BidiComponent_ArrowData); ok {
			return x.ArrowData
		}
	}
	return nil
}

func (x *BidiComponent) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Data.(*BidiComponent_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *BidiComponent) GetMixed() *MixedData {
	if x != nil {
		if x, ok := x.Data.(*BidiComponent_Mixed); ok {
			return x.Mixed
		}
	}
	return nil
}

type isBidiComponent_Data interface {
	isBidiComponent_Data()
}

type BidiComponent_Json struct {
	// JSON-serialized value for generic data payloads.
	Json string `protobuf:"bytes,10,opt,name=json,proto3,oneof"`
}

type BidiComponent_ArrowData struct {
	// Data-only Apache Arrow buffer for dataframe-like payloads.
	ArrowData *ArrowData `protobuf:"bytes,11,opt,name=arrow_data,json=arrowData,proto3,oneof"`
}

type BidiComponent_Bytes struct {
	// Arbitrary bytes payload.
	Bytes []byte `protobuf:"bytes,12,opt,name=bytes,proto3,oneof"`
}

type BidiComponent_Mixed struct {
	// Mixed data with JSON structure + embedded Arrow references
	Mixed *MixedData `protobuf:"bytes,13,opt,name=mixed,proto3,oneof"`
}

func (*BidiComponent_Json) isBidiComponent_Data() {}

func (*BidiComponent_ArrowData) isBidiComponent_Data() {}

func (*BidiComponent_Bytes) isBidiComponent_Data() {}

func (*BidiComponent_Mixed) isBidiComponent_Data() {}

var File_streamlit_proto_BidiComponent_proto protoreflect.FileDescriptor

const file_streamlit_proto_BidiComponent_proto_rawDesc = "" +
	"\n" +
	"#streamlit/proto/BidiComponent.proto\x1a\x1fstreamlit/proto/ArrowData.proto\"\xa7\x01\n" +
	"\tMixedData\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12;\n" +
	"\varrow_blobs\x18\x02 \x03(\v2\x1a.MixedData.ArrowBlobsEntryR\n" +
	"arrowBlobs\x1aI\n" +
	"\x0fArrowBlobsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".ArrowDataR\x05value:\x028\x01\"\xae\x04\n" +
	"\rBidiComponent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0ecomponent_name\x18\x02 \x01(\tR\rcomponentName\x12\"\n" +
	"\n" +
	"js_content\x18\x03 \x01(\tH\x01R\tjsContent\x88\x01\x01\x12)\n" +
	"\x0ejs_source_path\x18\x04 \x01(\tH\x02R\fjsSourcePath\x88\x01\x01\x12\x17\n" +
	"\aform_id\x18\x05 \x01(\tR\x06formId\x12&\n" +
	"\fhtml_content\x18\x06 \x01(\tH\x03R\vhtmlContent\x88\x01\x01\x12$\n" +
	"\vcss_content\x18\a \x01(\tH\x04R\n" +
	"cssContent\x88\x01\x01\x12+\n" +
	"\x0fcss_source_path\x18\b \x01(\tH\x05R\rcssSourcePath\x88\x01\x01\x12%\n" +
	"\x0eisolate_styles\x18\t \x01(\bR\risolateStyles\x12\x14\n" +
	"\x04json\x18\n" +
	" \x01(\tH\x00R\x04json\x12+\n" +
	"\n" +
	"arrow_data\x18\v \x01(\v2\n" +
	".ArrowDataH\x00R\tarrowData\x12\x16\n" +
	"\x05bytes\x18\f \x01(\fH\x00R\x05bytes\x12\"\n" +
	"\x05mixed\x18\r \x01(\v2\n" +
	".MixedDataH\x00R\x05mixedB\x06\n" +
	"\x04dataB\r\n" +
	"\v_js_contentB\x11\n" +
	"\x0f_js_source_pathB\x0f\n" +
	"\r_html_contentB\x0e\n" +
	"\f_css_contentB\x12\n" +
	"\x10_css_source_pathB3Z1github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_BidiComponent_proto_rawDescOnce sync.Once
	file_streamlit_proto_BidiComponent_proto_rawDescData []byte
)

func file_streamlit_proto_BidiComponent_proto_rawDescGZIP() []byte {
	file_streamlit_proto_BidiComponent_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_BidiComponent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_BidiComponent_proto_rawDesc), len(file_streamlit_proto_BidiComponent_proto_rawDesc)))
	})
	return file_streamlit_proto_BidiComponent_proto_rawDescData
}

var file_streamlit_proto_BidiComponent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_streamlit_proto_BidiComponent_proto_goTypes = []any{
	(*MixedData)(nil),     // 0: MixedData
	(*BidiComponent)(nil), // 1: BidiComponent
	nil,                   // 2: MixedData.ArrowBlobsEntry
	(*ArrowData)(nil),     // 3: ArrowData
}
var file_streamlit_proto_BidiComponent_proto_depIdxs = []int32{
	2, // 0: MixedData.arrow_blobs:type_name -> MixedData.ArrowBlobsEntry
	3, // 1: BidiComponent.arrow_data:type_name -> ArrowData
	0, // 2: BidiComponent.mixed:type_name -> MixedData
	3, // 3: MixedData.ArrowBlobsEntry.value:type_name -> ArrowData
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_streamlit_proto_BidiComponent_proto_init() }
func file_streamlit_proto_BidiComponent_proto_init() {
	if File_streamlit_proto_BidiComponent_proto != nil {
		return
	}
	file_streamlit_proto_ArrowData_proto_init()
	file_streamlit_proto_BidiComponent_proto_msgTypes[1].OneofWrappers = []any{
		(*BidiComponent_Json)(nil),
		(*BidiComponent_ArrowData)(nil),
		(*BidiComponent_Bytes)(nil),
		(*BidiComponent_Mixed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_BidiComponent_proto_rawDesc), len(file_streamlit_proto_BidiComponent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_BidiComponent_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_BidiComponent_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_BidiComponent_proto_msgTypes,
	}.Build()
	File_streamlit_proto_BidiComponent_proto = out.File
	file_streamlit_proto_BidiComponent_proto_goTypes = nil
	file_streamlit_proto_BidiComponent_proto_depIdxs = nil
}
