//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Block.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block_FlexContainer_Direction int32

const (
	Block_FlexContainer_DIRECTION_UNDEFINED Block_FlexContainer_Direction = 0
	Block_FlexContainer_VERTICAL            Block_FlexContainer_Direction = 1
	Block_FlexContainer_HORIZONTAL          Block_FlexContainer_Direction = 2
)

// Enum value maps for Block_FlexContainer_Direction.
var (
	Block_FlexContainer_Direction_name = map[int32]string{
		0: "DIRECTION_UNDEFINED",
		1: "VERTICAL",
		2: "HORIZONTAL",
	}
	Block_FlexContainer_Direction_value = map[string]int32{
		"DIRECTION_UNDEFINED": 0,
		"VERTICAL":            1,
		"HORIZONTAL":          2,
	}
)

func (x Block_FlexContainer_Direction) Enum() *Block_FlexContainer_Direction {
	p := new(Block_FlexContainer_Direction)
	*p = x
	return p
}

func (x Block_FlexContainer_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Block_FlexContainer_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Block_proto_enumTypes[0].Descriptor()
}

func (Block_FlexContainer_Direction) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Block_proto_enumTypes[0]
}

func (x Block_FlexContainer_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Block_FlexContainer_Direction.Descriptor instead.
func (Block_FlexContainer_Direction) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 2, 0}
}

type Block_FlexContainer_Justify int32

const (
	Block_FlexContainer_JUSTIFY_UNDEFINED Block_FlexContainer_Justify = 0
	Block_FlexContainer_JUSTIFY_START     Block_FlexContainer_Justify = 1
	Block_FlexContainer_JUSTIFY_END       Block_FlexContainer_Justify = 2
	Block_FlexContainer_JUSTIFY_CENTER    Block_FlexContainer_Justify = 3
	Block_FlexContainer_SPACE_BETWEEN     Block_FlexContainer_Justify = 4
)

// Enum value maps for Block_FlexContainer_Justify.
var (
	Block_FlexContainer_Justify_name = map[int32]string{
		0: "JUSTIFY_UNDEFINED",
		1: "JUSTIFY_START",
		2: "JUSTIFY_END",
		3: "JUSTIFY_CENTER",
		4: "SPACE_BETWEEN",
	}
	Block_FlexContainer_Justify_value = map[string]int32{
		"JUSTIFY_UNDEFINED": 0,
		"JUSTIFY_START":     1,
		"JUSTIFY_END":       2,
		"JUSTIFY_CENTER":    3,
		"SPACE_BETWEEN":     4,
	}
)

func (x Block_FlexContainer_Justify) Enum() *Block_FlexContainer_Justify {
	p := new(Block_FlexContainer_Justify)
	*p = x
	return p
}

func (x Block_FlexContainer_Justify) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Block_FlexContainer_Justify) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Block_proto_enumTypes[1].Descriptor()
}

func (Block_FlexContainer_Justify) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Block_proto_enumTypes[1]
}

func (x Block_FlexContainer_Justify) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Block_FlexContainer_Justify.Descriptor instead.
func (Block_FlexContainer_Justify) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 2, 1}
}

type Block_FlexContainer_Align int32

const (
	Block_FlexContainer_ALIGN_UNDEFINED Block_FlexContainer_Align = 0
	Block_FlexContainer_ALIGN_START     Block_FlexContainer_Align = 1
	Block_FlexContainer_ALIGN_END       Block_FlexContainer_Align = 2
	Block_FlexContainer_ALIGN_CENTER    Block_FlexContainer_Align = 3
	Block_FlexContainer_STRETCH         Block_FlexContainer_Align = 4
)

// Enum value maps for Block_FlexContainer_Align.
var (
	Block_FlexContainer_Align_name = map[int32]string{
		0: "ALIGN_UNDEFINED",
		1: "ALIGN_START",
		2: "ALIGN_END",
		3: "ALIGN_CENTER",
		4: "STRETCH",
	}
	Block_FlexContainer_Align_value = map[string]int32{
		"ALIGN_UNDEFINED": 0,
		"ALIGN_START":     1,
		"ALIGN_END":       2,
		"ALIGN_CENTER":    3,
		"STRETCH":         4,
	}
)

func (x Block_FlexContainer_Align) Enum() *Block_FlexContainer_Align {
	p := new(Block_FlexContainer_Align)
	*p = x
	return p
}

func (x Block_FlexContainer_Align) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Block_FlexContainer_Align) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Block_proto_enumTypes[2].Descriptor()
}

func (Block_FlexContainer_Align) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Block_proto_enumTypes[2]
}

func (x Block_FlexContainer_Align) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Block_FlexContainer_Align.Descriptor instead.
func (Block_FlexContainer_Align) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 2, 2}
}

type Block_Column_VerticalAlignment int32

const (
	Block_Column_TOP    Block_Column_VerticalAlignment = 0
	Block_Column_CENTER Block_Column_VerticalAlignment = 1
	Block_Column_BOTTOM Block_Column_VerticalAlignment = 2
)

// Enum value maps for Block_Column_VerticalAlignment.
var (
	Block_Column_VerticalAlignment_name = map[int32]string{
		0: "TOP",
		1: "CENTER",
		2: "BOTTOM",
	}
	Block_Column_VerticalAlignment_value = map[string]int32{
		"TOP":    0,
		"CENTER": 1,
		"BOTTOM": 2,
	}
)

func (x Block_Column_VerticalAlignment) Enum() *Block_Column_VerticalAlignment {
	p := new(Block_Column_VerticalAlignment)
	*p = x
	return p
}

func (x Block_Column_VerticalAlignment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Block_Column_VerticalAlignment) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Block_proto_enumTypes[3].Descriptor()
}

func (Block_Column_VerticalAlignment) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Block_proto_enumTypes[3]
}

func (x Block_Column_VerticalAlignment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Block_Column_VerticalAlignment.Descriptor instead.
func (Block_Column_VerticalAlignment) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 3, 0}
}

type Block_Dialog_DialogWidth int32

const (
	Block_Dialog_SMALL  Block_Dialog_DialogWidth = 0
	Block_Dialog_LARGE  Block_Dialog_DialogWidth = 1
	Block_Dialog_MEDIUM Block_Dialog_DialogWidth = 2
)

// Enum value maps for Block_Dialog_DialogWidth.
var (
	Block_Dialog_DialogWidth_name = map[int32]string{
		0: "SMALL",
		1: "LARGE",
		2: "MEDIUM",
	}
	Block_Dialog_DialogWidth_value = map[string]int32{
		"SMALL":  0,
		"LARGE":  1,
		"MEDIUM": 2,
	}
)

func (x Block_Dialog_DialogWidth) Enum() *Block_Dialog_DialogWidth {
	p := new(Block_Dialog_DialogWidth)
	*p = x
	return p
}

func (x Block_Dialog_DialogWidth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Block_Dialog_DialogWidth) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Block_proto_enumTypes[4].Descriptor()
}

func (Block_Dialog_DialogWidth) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Block_proto_enumTypes[4]
}

func (x Block_Dialog_DialogWidth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Block_Dialog_DialogWidth.Descriptor instead.
func (Block_Dialog_DialogWidth) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 5, 0}
}

type Block_ChatMessage_AvatarType int32

const (
	Block_ChatMessage_IMAGE Block_ChatMessage_AvatarType = 0
	Block_ChatMessage_EMOJI Block_ChatMessage_AvatarType = 1
	Block_ChatMessage_ICON  Block_ChatMessage_AvatarType = 2
)

// Enum value maps for Block_ChatMessage_AvatarType.
var (
	Block_ChatMessage_AvatarType_name = map[int32]string{
		0: "IMAGE",
		1: "EMOJI",
		2: "ICON",
	}
	Block_ChatMessage_AvatarType_value = map[string]int32{
		"IMAGE": 0,
		"EMOJI": 1,
		"ICON":  2,
	}
)

func (x Block_ChatMessage_AvatarType) Enum() *Block_ChatMessage_AvatarType {
	p := new(Block_ChatMessage_AvatarType)
	*p = x
	return p
}

func (x Block_ChatMessage_AvatarType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Block_ChatMessage_AvatarType) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Block_proto_enumTypes[5].Descriptor()
}

func (Block_ChatMessage_AvatarType) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Block_proto_enumTypes[5]
}

func (x Block_ChatMessage_AvatarType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Block_ChatMessage_AvatarType.Descriptor instead.
func (Block_ChatMessage_AvatarType) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 10, 0}
}

type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Block_Vertical_
	//	*Block_Horizontal_
	//	*Block_Column_
	//	*Block_Expandable_
	//	*Block_Form_
	//	*Block_TabContainer_
	//	*Block_Tab_
	//	*Block_ChatMessage_
	//	*Block_Popover_
	//	*Block_Dialog_
	//	*Block_FlexContainer_
	Type          isBlock_Type  `protobuf_oneof:"type"`
	AllowEmpty    bool          `protobuf:"varint,8,opt,name=allow_empty,json=allowEmpty,proto3" json:"allow_empty,omitempty"`
	Id            *string       `protobuf:"bytes,12,opt,name=id,proto3,oneof" json:"id,omitempty"`
	HeightConfig  *HeightConfig `protobuf:"bytes,14,opt,name=height_config,json=heightConfig,proto3,oneof" json:"height_config,omitempty"`
	WidthConfig   *WidthConfig  `protobuf:"bytes,15,opt,name=width_config,json=widthConfig,proto3,oneof" json:"width_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_streamlit_proto_Block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetType() isBlock_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Block) GetVertical() *Block_Vertical {
	if x != nil {
		if x, ok := x.Type.(*Block_Vertical_); ok {
			return x.Vertical
		}
	}
	return nil
}

func (x *Block) GetHorizontal() *Block_Horizontal {
	if x != nil {
		if x, ok := x.Type.(*Block_Horizontal_); ok {
			return x.Horizontal
		}
	}
	return nil
}

func (x *Block) GetColumn() *Block_Column {
	if x != nil {
		if x, ok := x.Type.(*Block_Column_); ok {
			return x.Column
		}
	}
	return nil
}

func (x *Block) GetExpandable() *Block_Expandable {
	if x != nil {
		if x, ok := x.Type.(*Block_Expandable_); ok {
			return x.Expandable
		}
	}
	return nil
}

func (x *Block) GetForm() *Block_Form {
	if x != nil {
		if x, ok := x.Type.(*Block_Form_); ok {
			return x.Form
		}
	}
	return nil
}

func (x *Block) GetTabContainer() *Block_TabContainer {
	if x != nil {
		if x, ok := x.Type.(*Block_TabContainer_); ok {
			return x.TabContainer
		}
	}
	return nil
}

func (x *Block) GetTab() *Block_Tab {
	if x != nil {
		if x, ok := x.Type.(*Block_Tab_); ok {
			return x.Tab
		}
	}
	return nil
}

func (x *Block) GetChatMessage() *Block_ChatMessage {
	if x != nil {
		if x, ok := x.Type.(*Block_ChatMessage_); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *Block) GetPopover() *Block_Popover {
	if x != nil {
		if x, ok := x.Type.(*Block_Popover_); ok {
			return x.Popover
		}
	}
	return nil
}

func (x *Block) GetDialog() *Block_Dialog {
	if x != nil {
		if x, ok := x.Type.(*Block_Dialog_); ok {
			return x.Dialog
		}
	}
	return nil
}

func (x *Block) GetFlexContainer() *Block_FlexContainer {
	if x != nil {
		if x, ok := x.Type.(*Block_FlexContainer_); ok {
			return x.FlexContainer
		}
	}
	return nil
}

func (x *Block) GetAllowEmpty() bool {
	if x != nil {
		return x.AllowEmpty
	}
	return false
}

func (x *Block) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Block) GetHeightConfig() *HeightConfig {
	if x != nil {
		return x.HeightConfig
	}
	return nil
}

func (x *Block) GetWidthConfig() *WidthConfig {
	if x != nil {
		return x.WidthConfig
	}
	return nil
}

type isBlock_Type interface {
	isBlock_Type()
}

type Block_Vertical_ struct {
	Vertical *Block_Vertical `protobuf:"bytes,1,opt,name=vertical,proto3,oneof"`
}

type Block_Horizontal_ struct {
	Horizontal *Block_Horizontal `protobuf:"bytes,2,opt,name=horizontal,proto3,oneof"`
}

type Block_Column_ struct {
	Column *Block_Column `protobuf:"bytes,3,opt,name=column,proto3,oneof"`
}

type Block_Expandable_ struct {
	Expandable *Block_Expandable `protobuf:"bytes,4,opt,name=expandable,proto3,oneof"`
}

type Block_Form_ struct {
	Form *Block_Form `protobuf:"bytes,5,opt,name=form,proto3,oneof"`
}

type Block_TabContainer_ struct {
	TabContainer *Block_TabContainer `protobuf:"bytes,6,opt,name=tab_container,json=tabContainer,proto3,oneof"`
}

type Block_Tab_ struct {
	Tab *Block_Tab `protobuf:"bytes,7,opt,name=tab,proto3,oneof"`
}

type Block_ChatMessage_ struct {
	ChatMessage *Block_ChatMessage `protobuf:"bytes,9,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type Block_Popover_ struct {
	Popover *Block_Popover `protobuf:"bytes,10,opt,name=popover,proto3,oneof"`
}

type Block_Dialog_ struct {
	Dialog *Block_Dialog `protobuf:"bytes,11,opt,name=dialog,proto3,oneof"`
}

type Block_FlexContainer_ struct {
	FlexContainer *Block_FlexContainer `protobuf:"bytes,13,opt,name=flex_container,json=flexContainer,proto3,oneof"`
}

func (*Block_Vertical_) isBlock_Type() {}

func (*Block_Horizontal_) isBlock_Type() {}

func (*Block_Column_) isBlock_Type() {}

func (*Block_Expandable_) isBlock_Type() {}

func (*Block_Form_) isBlock_Type() {}

func (*Block_TabContainer_) isBlock_Type() {}

func (*Block_Tab_) isBlock_Type() {}

func (*Block_ChatMessage_) isBlock_Type() {}

func (*Block_Popover_) isBlock_Type() {}

func (*Block_Dialog_) isBlock_Type() {}

func (*Block_FlexContainer_) isBlock_Type() {}

type Block_Vertical struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Border        bool                   `protobuf:"varint,1,opt,name=border,proto3" json:"border,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block_Vertical) Reset() {
	*x = Block_Vertical{}
	mi := &file_streamlit_proto_Block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block_Vertical) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_Vertical) ProtoMessage() {}

func (x *Block_Vertical) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_Vertical.ProtoReflect.Descriptor instead.
func (*Block_Vertical) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Block_Vertical) GetBorder() bool {
	if x != nil {
		return x.Border
	}
	return false
}

type Block_Horizontal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gap           string                 `protobuf:"bytes,1,opt,name=gap,proto3" json:"gap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block_Horizontal) Reset() {
	*x = Block_Horizontal{}
	mi := &file_streamlit_proto_Block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block_Horizontal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_Horizontal) ProtoMessage() {}

func (x *Block_Horizontal) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_Horizontal.ProtoReflect.Descriptor instead.
func (*Block_Horizontal) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Block_Horizontal) GetGap() string {
	if x != nil {
		return x.Gap
	}
	return ""
}

type Block_FlexContainer struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Border        bool                          `protobuf:"varint,1,opt,name=border,proto3" json:"border,omitempty"`
	GapConfig     *GapConfig                    `protobuf:"bytes,2,opt,name=gap_config,json=gapConfig,proto3" json:"gap_config,omitempty"`
	Scale         float32                       `protobuf:"fixed32,3,opt,name=scale,proto3" json:"scale,omitempty"`
	Direction     Block_FlexContainer_Direction `protobuf:"varint,4,opt,name=direction,proto3,enum=Block_FlexContainer_Direction" json:"direction,omitempty"`
	Wrap          bool                          `protobuf:"varint,5,opt,name=wrap,proto3" json:"wrap,omitempty"`
	Justify       Block_FlexContainer_Justify   `protobuf:"varint,7,opt,name=justify,proto3,enum=Block_FlexContainer_Justify" json:"justify,omitempty"`
	Align         Block_FlexContainer_Align     `protobuf:"varint,8,opt,name=align,proto3,enum=Block_FlexContainer_Align" json:"align,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block_FlexContainer) Reset() {
	*x = Block_FlexContainer{}
	mi := &file_streamlit_proto_Block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block_FlexContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_FlexContainer) ProtoMessage() {}

func (x *Block_FlexContainer) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_FlexContainer.ProtoReflect.Descriptor instead.
func (*Block_FlexContainer) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Block_FlexContainer) GetBorder() bool {
	if x != nil {
		return x.Border
	}
	return false
}

func (x *Block_FlexContainer) GetGapConfig() *GapConfig {
	if x != nil {
		return x.GapConfig
	}
	return nil
}

func (x *Block_FlexContainer) GetScale() float32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *Block_FlexContainer) GetDirection() Block_FlexContainer_Direction {
	if x != nil {
		return x.Direction
	}
	return Block_FlexContainer_DIRECTION_UNDEFINED
}

func (x *Block_FlexContainer) GetWrap() bool {
	if x != nil {
		return x.Wrap
	}
	return false
}

func (x *Block_FlexContainer) GetJustify() Block_FlexContainer_Justify {
	if x != nil {
		return x.Justify
	}
	return Block_FlexContainer_JUSTIFY_UNDEFINED
}

func (x *Block_FlexContainer) GetAlign() Block_FlexContainer_Align {
	if x != nil {
		return x.Align
	}
	return Block_FlexContainer_ALIGN_UNDEFINED
}

type Block_Column struct {
	state             protoimpl.MessageState         `protogen:"open.v1"`
	Weight            float64                        `protobuf:"fixed64,1,opt,name=weight,proto3" json:"weight,omitempty"`
	VerticalAlignment Block_Column_VerticalAlignment `protobuf:"varint,3,opt,name=vertical_alignment,json=verticalAlignment,proto3,enum=Block_Column_VerticalAlignment" json:"vertical_alignment,omitempty"`
	ShowBorder        bool                           `protobuf:"varint,4,opt,name=show_border,json=showBorder,proto3" json:"show_border,omitempty"`
	GapConfig         *GapConfig                     `protobuf:"bytes,5,opt,name=gap_config,json=gapConfig,proto3,oneof" json:"gap_config,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Block_Column) Reset() {
	*x = Block_Column{}
	mi := &file_streamlit_proto_Block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block_Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_Column) ProtoMessage() {}

func (x *Block_Column) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_Column.ProtoReflect.Descriptor instead.
func (*Block_Column) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Block_Column) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Block_Column) GetVerticalAlignment() Block_Column_VerticalAlignment {
	if x != nil {
		return x.VerticalAlignment
	}
	return Block_Column_TOP
}

func (x *Block_Column) GetShowBorder() bool {
	if x != nil {
		return x.ShowBorder
	}
	return false
}

func (x *Block_Column) GetGapConfig() *GapConfig {
	if x != nil {
		return x.GapConfig
	}
	return nil
}

type Block_Expandable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Expanded      *bool                  `protobuf:"varint,2,opt,name=expanded,proto3,oneof" json:"expanded,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block_Expandable) Reset() {
	*x = Block_Expandable{}
	mi := &file_streamlit_proto_Block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block_Expandable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_Expandable) ProtoMessage() {}

func (x *Block_Expandable) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_Expandable.ProtoReflect.Descriptor instead.
func (*Block_Expandable) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Block_Expandable) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Block_Expandable) GetExpanded() bool {
	if x != nil && x.Expanded != nil {
		return *x.Expanded
	}
	return false
}

func (x *Block_Expandable) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type Block_Dialog struct {
	state       protoimpl.MessageState   `protogen:"open.v1"`
	Title       string                   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Dismissible bool                     `protobuf:"varint,2,opt,name=dismissible,proto3" json:"dismissible,omitempty"`
	Width       Block_Dialog_DialogWidth `protobuf:"varint,3,opt,name=width,proto3,enum=Block_Dialog_DialogWidth" json:"width,omitempty"`
	IsOpen      *bool                    `protobuf:"varint,4,opt,name=is_open,json=isOpen,proto3,oneof" json:"is_open,omitempty"`
	// If id is set, dismissal of the dialog will trigger a rerun.
	Id string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	// Optional icon shown next to the dialog title.
	Icon          string `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block_Dialog) Reset() {
	*x = Block_Dialog{}
	mi := &file_streamlit_proto_Block_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block_Dialog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_Dialog) ProtoMessage() {}

func (x *Block_Dialog) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Block_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_Dialog.ProtoReflect.Descriptor instead.
func (*Block_Dialog) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Block_Dialog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Block_Dialog) GetDismissible() bool {
	if x != nil {
		return x.Dismissible
	}
	return false
}

func (x *Block_Dialog) GetWidth() Block_Dialog_DialogWidth {
	if x != nil {
		return x.Width
	}
	return Block_Dialog_SMALL
}

func (x *Block_Dialog) GetIsOpen() bool {
	if x != nil && x.IsOpen != nil {
		return *x.IsOpen
	}
	return false
}

func (x *Block_Dialog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block_Dialog) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type Block_Form struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	ClearOnSubmit bool                   `protobuf:"varint,2,opt,name=clear_on_submit,json=clearOnSubmit,proto3" json:"clear_on_submit,omitempty"`
	Border        bool                   `protobuf:"varint,3,opt,name=border,proto3" json:"border,omitempty"`
	EnterToSubmit bool                   `protobuf:"varint,4,opt,name=enter_to_submit,json=enterToSubmit,proto3" json:"enter_to_submit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block_Form) Reset() {
	*x = Block_Form{}
	mi := &file_streamlit_proto_Block_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block_Form) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_Form) ProtoMessage() {}

func (x *Block_Form) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Block_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_Form.ProtoReflect.Descriptor instead.
func (*Block_Form) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Block_Form) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *Block_Form) GetClearOnSubmit() bool {
	if x != nil {
		return x.ClearOnSubmit
	}
	return false
}

func (x *Block_Form) GetBorder() bool {
	if x != nil {
		return x.Border
	}
	return false
}

func (x *Block_Form) GetEnterToSubmit() bool {
	if x != nil {
		return x.EnterToSubmit
	}
	return false
}

type Block_TabContainer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DefaultTabIndex int32                  `protobuf:"varint,1,opt,name=default_tab_index,json=defaultTabIndex,proto3" json:"default_tab_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Block_TabContainer) Reset() {
	*x = Block_TabContainer{}
	mi := &file_streamlit_proto_Block_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block_TabContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_TabContainer) ProtoMessage() {}

func (x *Block_TabContainer) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Block_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_TabContainer.ProtoReflect.Descriptor instead.
func (*Block_TabContainer) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Block_TabContainer) GetDefaultTabIndex() int32 {
	if x != nil {
		return x.DefaultTabIndex
	}
	return 0
}

type Block_Tab struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block_Tab) Reset() {
	*x = Block_Tab{}
	mi := &file_streamlit_proto_Block_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block_Tab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_Tab) ProtoMessage() {}

func (x *Block_Tab) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Block_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_Tab.ProtoReflect.Descriptor instead.
func (*Block_Tab) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 8}
}

func (x *Block_Tab) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Block_Popover struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Help          string                 `protobuf:"bytes,3,opt,name=help,proto3" json:"help,omitempty"`
	Disabled      bool                   `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block_Popover) Reset() {
	*x = Block_Popover{}
	mi := &file_streamlit_proto_Block_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block_Popover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_Popover) ProtoMessage() {}

func (x *Block_Popover) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Block_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_Popover.ProtoReflect.Descriptor instead.
func (*Block_Popover) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 9}
}

func (x *Block_Popover) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Block_Popover) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *Block_Popover) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Block_Popover) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Block_Popover) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Block_ChatMessage struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Name          string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                       `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	AvatarType    Block_ChatMessage_AvatarType `protobuf:"varint,3,opt,name=avatar_type,json=avatarType,proto3,enum=Block_ChatMessage_AvatarType" json:"avatar_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block_ChatMessage) Reset() {
	*x = Block_ChatMessage{}
	mi := &file_streamlit_proto_Block_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block_ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_ChatMessage) ProtoMessage() {}

func (x *Block_ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Block_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_ChatMessage.ProtoReflect.Descriptor instead.
func (*Block_ChatMessage) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Block_proto_rawDescGZIP(), []int{0, 10}
}

func (x *Block_ChatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Block_ChatMessage) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Block_ChatMessage) GetAvatarType() Block_ChatMessage_AvatarType {
	if x != nil {
		return x.AvatarType
	}
	return Block_ChatMessage_IMAGE
}

var File_streamlit_proto_Block_proto protoreflect.FileDescriptor

const file_streamlit_proto_Block_proto_rawDesc = "" +
	"\n" +
	"\x1bstreamlit/proto/Block.proto\x1a!streamlit/proto/WidthConfig.proto\x1a\"streamlit/proto/HeightConfig.proto\x1a\x1dstreamlit/proto/GapSize.proto\"\x87\x14\n" +
	"\x05Block\x12-\n" +
	"\bvertical\x18\x01 \x01(\v2\x0f.Block.VerticalH\x00R\bvertical\x123\n" +
	"\n" +
	"horizontal\x18\x02 \x01(\v2\x11.Block.HorizontalH\x00R\n" +
	"horizontal\x12'\n" +
	"\x06column\x18\x03 \x01(\v2\r.Block.ColumnH\x00R\x06column\x123\n" +
	"\n" +
	"expandable\x18\x04 \x01(\v2\x11.Block.ExpandableH\x00R\n" +
	"expandable\x12!\n" +
	"\x04form\x18\x05 \x01(\v2\v.Block.FormH\x00R\x04form\x12:\n" +
	"\rtab_container\x18\x06 \x01(\v2\x13.Block.TabContainerH\x00R\ftabContainer\x12\x1e\n" +
	"\x03tab\x18\a \x01(\v2\n" +
	".Block.TabH\x00R\x03tab\x127\n" +
	"\fchat_message\x18\t \x01(\v2\x12.Block.ChatMessageH\x00R\vchatMessage\x12*\n" +
	"\apopover\x18\n" +
	" \x01(\v2\x0e.Block.PopoverH\x00R\apopover\x12'\n" +
	"\x06dialog\x18\v \x01(\v2\r.Block.DialogH\x00R\x06dialog\x12=\n" +
	"\x0eflex_container\x18\r \x01(\v2\x14.Block.FlexContainerH\x00R\rflexContainer\x12\x1f\n" +
	"\vallow_empty\x18\b \x01(\bR\n" +
	"allowEmpty\x12\x13\n" +
	"\x02id\x18\f \x01(\tH\x01R\x02id\x88\x01\x01\x12A\n" +
	"\rheight_config\x18\x0e \x01(\v2\x17.streamlit.HeightConfigH\x02R\fheightConfig\x88\x01\x01\x12>\n" +
	"\fwidth_config\x18\x0f \x01(\v2\x16.streamlit.WidthConfigH\x03R\vwidthConfig\x88\x01\x01\x1a(\n" +
	"\bVertical\x12\x16\n" +
	"\x06border\x18\x01 \x01(\bR\x06borderJ\x04\b\x02\x10\x03\x1a\x1e\n" +
	"\n" +
	"Horizontal\x12\x10\n" +
	"\x03gap\x18\x01 \x01(\tR\x03gap\x1a\xbc\x04\n" +
	"\rFlexContainer\x12\x16\n" +
	"\x06border\x18\x01 \x01(\bR\x06border\x123\n" +
	"\n" +
	"gap_config\x18\x02 \x01(\v2\x14.streamlit.GapConfigR\tgapConfig\x12\x14\n" +
	"\x05scale\x18\x03 \x01(\x02R\x05scale\x12<\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x1e.Block.FlexContainer.DirectionR\tdirection\x12\x12\n" +
	"\x04wrap\x18\x05 \x01(\bR\x04wrap\x126\n" +
	"\ajustify\x18\a \x01(\x0e2\x1c.Block.FlexContainer.JustifyR\ajustify\x120\n" +
	"\x05align\x18\b \x01(\x0e2\x1a.Block.FlexContainer.AlignR\x05align\"B\n" +
	"\tDirection\x12\x17\n" +
	"\x13DIRECTION_UNDEFINED\x10\x00\x12\f\n" +
	"\bVERTICAL\x10\x01\x12\x0e\n" +
	"\n" +
	"HORIZONTAL\x10\x02\"k\n" +
	"\aJustify\x12\x15\n" +
	"\x11JUSTIFY_UNDEFINED\x10\x00\x12\x11\n" +
	"\rJUSTIFY_START\x10\x01\x12\x0f\n" +
	"\vJUSTIFY_END\x10\x02\x12\x12\n" +
	"\x0eJUSTIFY_CENTER\x10\x03\x12\x11\n" +
	"\rSPACE_BETWEEN\x10\x04\"[\n" +
	"\x05Align\x12\x13\n" +
	"\x0fALIGN_UNDEFINED\x10\x00\x12\x0f\n" +
	"\vALIGN_START\x10\x01\x12\r\n" +
	"\tALIGN_END\x10\x02\x12\x10\n" +
	"\fALIGN_CENTER\x10\x03\x12\v\n" +
	"\aSTRETCH\x10\x04\x1a\x96\x02\n" +
	"\x06Column\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x01R\x06weight\x12N\n" +
	"\x12vertical_alignment\x18\x03 \x01(\x0e2\x1f.Block.Column.VerticalAlignmentR\x11verticalAlignment\x12\x1f\n" +
	"\vshow_border\x18\x04 \x01(\bR\n" +
	"showBorder\x128\n" +
	"\n" +
	"gap_config\x18\x05 \x01(\v2\x14.streamlit.GapConfigH\x00R\tgapConfig\x88\x01\x01\"4\n" +
	"\x11VerticalAlignment\x12\a\n" +
	"\x03TOP\x10\x00\x12\n" +
	"\n" +
	"\x06CENTER\x10\x01\x12\n" +
	"\n" +
	"\x06BOTTOM\x10\x02B\r\n" +
	"\v_gap_configJ\x04\b\x02\x10\x03\x1ad\n" +
	"\n" +
	"Expandable\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1f\n" +
	"\bexpanded\x18\x02 \x01(\bH\x00R\bexpanded\x88\x01\x01\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04iconB\v\n" +
	"\t_expanded\x1a\xf0\x01\n" +
	"\x06Dialog\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdismissible\x18\x02 \x01(\bR\vdismissible\x12/\n" +
	"\x05width\x18\x03 \x01(\x0e2\x19.Block.Dialog.DialogWidthR\x05width\x12\x1c\n" +
	"\ais_open\x18\x04 \x01(\bH\x00R\x06isOpen\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\"/\n" +
	"\vDialogWidth\x12\t\n" +
	"\x05SMALL\x10\x00\x12\t\n" +
	"\x05LARGE\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02B\n" +
	"\n" +
	"\b_is_open\x1a\x87\x01\n" +
	"\x04Form\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x12&\n" +
	"\x0fclear_on_submit\x18\x02 \x01(\bR\rclearOnSubmit\x12\x16\n" +
	"\x06border\x18\x03 \x01(\bR\x06border\x12&\n" +
	"\x0fenter_to_submit\x18\x04 \x01(\bR\renterToSubmit\x1a:\n" +
	"\fTabContainer\x12*\n" +
	"\x11default_tab_index\x18\x01 \x01(\x05R\x0fdefaultTabIndex\x1a\x1b\n" +
	"\x03Tab\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x1a}\n" +
	"\aPopover\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04help\x18\x03 \x01(\tR\x04help\x12\x1a\n" +
	"\bdisabled\x18\x04 \x01(\bR\bdisabled\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04typeJ\x04\b\x02\x10\x03\x1a\xa7\x01\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12>\n" +
	"\vavatar_type\x18\x03 \x01(\x0e2\x1d.Block.ChatMessage.AvatarTypeR\n" +
	"avatarType\",\n" +
	"\n" +
	"AvatarType\x12\t\n" +
	"\x05IMAGE\x10\x00\x12\t\n" +
	"\x05EMOJI\x10\x01\x12\b\n" +
	"\x04ICON\x10\x02B\x06\n" +
	"\x04typeB\x05\n" +
	"\x03_idB\x10\n" +
	"\x0e_height_configB\x0f\n" +
	"\r_width_configB3Z1github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Block_proto_rawDescOnce sync.Once
	file_streamlit_proto_Block_proto_rawDescData []byte
)

func file_streamlit_proto_Block_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Block_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Block_proto_rawDesc), len(file_streamlit_proto_Block_proto_rawDesc)))
	})
	return file_streamlit_proto_Block_proto_rawDescData
}

var file_streamlit_proto_Block_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_streamlit_proto_Block_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_streamlit_proto_Block_proto_goTypes = []any{
	(Block_FlexContainer_Direction)(0),  // 0: Block.FlexContainer.Direction
	(Block_FlexContainer_Justify)(0),    // 1: Block.FlexContainer.Justify
	(Block_FlexContainer_Align)(0),      // 2: Block.FlexContainer.Align
	(Block_Column_VerticalAlignment)(0), // 3: Block.Column.VerticalAlignment
	(Block_Dialog_DialogWidth)(0),       // 4: Block.Dialog.DialogWidth
	(Block_ChatMessage_AvatarType)(0),   // 5: Block.ChatMessage.AvatarType
	(*Block)(nil),                       // 6: Block
	(*Block_Vertical)(nil),              // 7: Block.Vertical
	(*Block_Horizontal)(nil),            // 8: Block.Horizontal
	(*Block_FlexContainer)(nil),         // 9: Block.FlexContainer
	(*Block_Column)(nil),                // 10: Block.Column
	(*Block_Expandable)(nil),            // 11: Block.Expandable
	(*Block_Dialog)(nil),                // 12: Block.Dialog
	(*Block_Form)(nil),                  // 13: Block.Form
	(*Block_TabContainer)(nil),          // 14: Block.TabContainer
	(*Block_Tab)(nil),                   // 15: Block.Tab
	(*Block_Popover)(nil),               // 16: Block.Popover
	(*Block_ChatMessage)(nil),           // 17: Block.ChatMessage
	(*HeightConfig)(nil),                // 18: streamlit.HeightConfig
	(*WidthConfig)(nil),                 // 19: streamlit.WidthConfig
	(*GapConfig)(nil),                   // 20: streamlit.GapConfig
}
var file_streamlit_proto_Block_proto_depIdxs = []int32{
	7,  // 0: Block.vertical:type_name -> Block.Vertical
	8,  // 1: Block.horizontal:type_name -> Block.Horizontal
	10, // 2: Block.column:type_name -> Block.Column
	11, // 3: Block.expandable:type_name -> Block.Expandable
	13, // 4: Block.form:type_name -> Block.Form
	14, // 5: Block.tab_container:type_name -> Block.TabContainer
	15, // 6: Block.tab:type_name -> Block.Tab
	17, // 7: Block.chat_message:type_name -> Block.ChatMessage
	16, // 8: Block.popover:type_name -> Block.Popover
	12, // 9: Block.dialog:type_name -> Block.Dialog
	9,  // 10: Block.flex_container:type_name -> Block.FlexContainer
	18, // 11: Block.height_config:type_name -> streamlit.HeightConfig
	19, // 12: Block.width_config:type_name -> streamlit.WidthConfig
	20, // 13: Block.FlexContainer.gap_config:type_name -> streamlit.GapConfig
	0,  // 14: Block.FlexContainer.direction:type_name -> Block.FlexContainer.Direction
	1,  // 15: Block.FlexContainer.justify:type_name -> Block.FlexContainer.Justify
	2,  // 16: Block.FlexContainer.align:type_name -> Block.FlexContainer.Align
	3,  // 17: Block.Column.vertical_alignment:type_name -> Block.Column.VerticalAlignment
	20, // 18: Block.Column.gap_config:type_name -> streamlit.GapConfig
	4,  // 19: Block.Dialog.width:type_name -> Block.Dialog.DialogWidth
	5,  // 20: Block.ChatMessage.avatar_type:type_name -> Block.ChatMessage.AvatarType
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Block_proto_init() }
func file_streamlit_proto_Block_proto_init() {
	if File_streamlit_proto_Block_proto != nil {
		return
	}
	file_streamlit_proto_WidthConfig_proto_init()
	file_streamlit_proto_HeightConfig_proto_init()
	file_streamlit_proto_GapSize_proto_init()
	file_streamlit_proto_Block_proto_msgTypes[0].OneofWrappers = []any{
		(*Block_Vertical_)(nil),
		(*Block_Horizontal_)(nil),
		(*Block_Column_)(nil),
		(*Block_Expandable_)(nil),
		(*Block_Form_)(nil),
		(*Block_TabContainer_)(nil),
		(*Block_Tab_)(nil),
		(*Block_ChatMessage_)(nil),
		(*Block_Popover_)(nil),
		(*Block_Dialog_)(nil),
		(*Block_FlexContainer_)(nil),
	}
	file_streamlit_proto_Block_proto_msgTypes[4].OneofWrappers = []any{}
	file_streamlit_proto_Block_proto_msgTypes[5].OneofWrappers = []any{}
	file_streamlit_proto_Block_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Block_proto_rawDesc), len(file_streamlit_proto_Block_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Block_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Block_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_Block_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_Block_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Block_proto = out.File
	file_streamlit_proto_Block_proto_goTypes = nil
	file_streamlit_proto_Block_proto_depIdxs = nil
}
