//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/ButtonGroup.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ButtonGroup_ClickMode int32

const (
	ButtonGroup_SINGLE_SELECT ButtonGroup_ClickMode = 0
	ButtonGroup_MULTI_SELECT  ButtonGroup_ClickMode = 1
)

// Enum value maps for ButtonGroup_ClickMode.
var (
	ButtonGroup_ClickMode_name = map[int32]string{
		0: "SINGLE_SELECT",
		1: "MULTI_SELECT",
	}
	ButtonGroup_ClickMode_value = map[string]int32{
		"SINGLE_SELECT": 0,
		"MULTI_SELECT":  1,
	}
)

func (x ButtonGroup_ClickMode) Enum() *ButtonGroup_ClickMode {
	p := new(ButtonGroup_ClickMode)
	*p = x
	return p
}

func (x ButtonGroup_ClickMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ButtonGroup_ClickMode) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_ButtonGroup_proto_enumTypes[0].Descriptor()
}

func (ButtonGroup_ClickMode) Type() protoreflect.EnumType {
	return &file_streamlit_proto_ButtonGroup_proto_enumTypes[0]
}

func (x ButtonGroup_ClickMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ButtonGroup_ClickMode.Descriptor instead.
func (ButtonGroup_ClickMode) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_ButtonGroup_proto_rawDescGZIP(), []int{0, 0}
}

type ButtonGroup_Style int32

const (
	ButtonGroup_SEGMENTED_CONTROL ButtonGroup_Style = 0
	ButtonGroup_PILLS             ButtonGroup_Style = 1
)

// Enum value maps for ButtonGroup_Style.
var (
	ButtonGroup_Style_name = map[int32]string{
		0: "SEGMENTED_CONTROL",
		1: "PILLS",
	}
	ButtonGroup_Style_value = map[string]int32{
		"SEGMENTED_CONTROL": 0,
		"PILLS":             1,
	}
)

func (x ButtonGroup_Style) Enum() *ButtonGroup_Style {
	p := new(ButtonGroup_Style)
	*p = x
	return p
}

func (x ButtonGroup_Style) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ButtonGroup_Style) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_ButtonGroup_proto_enumTypes[1].Descriptor()
}

func (ButtonGroup_Style) Type() protoreflect.EnumType {
	return &file_streamlit_proto_ButtonGroup_proto_enumTypes[1]
}

func (x ButtonGroup_Style) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ButtonGroup_Style.Descriptor instead.
func (ButtonGroup_Style) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_ButtonGroup_proto_rawDescGZIP(), []int{0, 1}
}

type ButtonGroup struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Options []*ButtonGroup_Option  `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	// default is an array of indexes that are selected by default
	Default         []uint32              `protobuf:"varint,3,rep,packed,name=default,proto3" json:"default,omitempty"`
	Disabled        bool                  `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	ClickMode       ButtonGroup_ClickMode `protobuf:"varint,5,opt,name=click_mode,json=clickMode,proto3,enum=ButtonGroup_ClickMode" json:"click_mode,omitempty"`
	FormId          string                `protobuf:"bytes,6,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	SetValue        bool                  `protobuf:"varint,8,opt,name=set_value,json=setValue,proto3" json:"set_value,omitempty"`
	Style           ButtonGroup_Style     `protobuf:"varint,10,opt,name=style,proto3,enum=ButtonGroup_Style" json:"style,omitempty"`
	Label           string                `protobuf:"bytes,11,opt,name=label,proto3" json:"label,omitempty"`
	LabelVisibility *LabelVisibility      `protobuf:"bytes,12,opt,name=label_visibility,json=labelVisibility,proto3" json:"label_visibility,omitempty"`
	Help            *string               `protobuf:"bytes,13,opt,name=help,proto3,oneof" json:"help,omitempty"`
	// For multi-select mode, this contains all selected option strings.
	// For single-select mode, this contains at most one selected option string.
	RawValues     []string `protobuf:"bytes,14,rep,name=raw_values,json=rawValues,proto3" json:"raw_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ButtonGroup) Reset() {
	*x = ButtonGroup{}
	mi := &file_streamlit_proto_ButtonGroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonGroup) ProtoMessage() {}

func (x *ButtonGroup) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_ButtonGroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonGroup.ProtoReflect.Descriptor instead.
func (*ButtonGroup) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_ButtonGroup_proto_rawDescGZIP(), []int{0}
}

func (x *ButtonGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ButtonGroup) GetOptions() []*ButtonGroup_Option {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ButtonGroup) GetDefault() []uint32 {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *ButtonGroup) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *ButtonGroup) GetClickMode() ButtonGroup_ClickMode {
	if x != nil {
		return x.ClickMode
	}
	return ButtonGroup_SINGLE_SELECT
}

func (x *ButtonGroup) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *ButtonGroup) GetSetValue() bool {
	if x != nil {
		return x.SetValue
	}
	return false
}

func (x *ButtonGroup) GetStyle() ButtonGroup_Style {
	if x != nil {
		return x.Style
	}
	return ButtonGroup_SEGMENTED_CONTROL
}

func (x *ButtonGroup) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ButtonGroup) GetLabelVisibility() *LabelVisibility {
	if x != nil {
		return x.LabelVisibility
	}
	return nil
}

func (x *ButtonGroup) GetHelp() string {
	if x != nil && x.Help != nil {
		return *x.Help
	}
	return ""
}

func (x *ButtonGroup) GetRawValues() []string {
	if x != nil {
		return x.RawValues
	}
	return nil
}

type ButtonGroup_Option struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Content string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// when set, this is the icon that will be displayed next to the option
	ContentIcon   *string `protobuf:"bytes,3,opt,name=content_icon,json=contentIcon,proto3,oneof" json:"content_icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ButtonGroup_Option) Reset() {
	*x = ButtonGroup_Option{}
	mi := &file_streamlit_proto_ButtonGroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonGroup_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonGroup_Option) ProtoMessage() {}

func (x *ButtonGroup_Option) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_ButtonGroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonGroup_Option.ProtoReflect.Descriptor instead.
func (*ButtonGroup_Option) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_ButtonGroup_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ButtonGroup_Option) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ButtonGroup_Option) GetContentIcon() string {
	if x != nil && x.ContentIcon != nil {
		return *x.ContentIcon
	}
	return ""
}

var File_streamlit_proto_ButtonGroup_proto protoreflect.FileDescriptor

const file_streamlit_proto_ButtonGroup_proto_rawDesc = "" +
	"\n" +
	"!streamlit/proto/ButtonGroup.proto\x1a%streamlit/proto/LabelVisibility.proto\"\xa9\x05\n" +
	"\vButtonGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\aoptions\x18\x02 \x03(\v2\x13.ButtonGroup.OptionR\aoptions\x12\x18\n" +
	"\adefault\x18\x03 \x03(\rR\adefault\x12\x1a\n" +
	"\bdisabled\x18\x04 \x01(\bR\bdisabled\x125\n" +
	"\n" +
	"click_mode\x18\x05 \x01(\x0e2\x16.ButtonGroup.ClickModeR\tclickMode\x12\x17\n" +
	"\aform_id\x18\x06 \x01(\tR\x06formId\x12\x1b\n" +
	"\tset_value\x18\b \x01(\bR\bsetValue\x12(\n" +
	"\x05style\x18\n" +
	" \x01(\x0e2\x12.ButtonGroup.StyleR\x05style\x12\x14\n" +
	"\x05label\x18\v \x01(\tR\x05label\x12;\n" +
	"\x10label_visibility\x18\f \x01(\v2\x10.LabelVisibilityR\x0flabelVisibility\x12\x17\n" +
	"\x04help\x18\r \x01(\tH\x00R\x04help\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"raw_values\x18\x0e \x03(\tR\trawValues\x1a\x90\x01\n" +
	"\x06Option\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12&\n" +
	"\fcontent_icon\x18\x03 \x01(\tH\x00R\vcontentIcon\x88\x01\x01B\x0f\n" +
	"\r_content_iconJ\x04\b\x02\x10\x03J\x04\b\x04\x10\x05R\x10selected_contentR\x15selected_content_icon\"0\n" +
	"\tClickMode\x12\x11\n" +
	"\rSINGLE_SELECT\x10\x00\x12\x10\n" +
	"\fMULTI_SELECT\x10\x01\")\n" +
	"\x05Style\x12\x15\n" +
	"\x11SEGMENTED_CONTROL\x10\x00\x12\t\n" +
	"\x05PILLS\x10\x01B\a\n" +
	"\x05_helpJ\x04\b\a\x10\bJ\x04\b\t\x10\n" +
	"B1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_ButtonGroup_proto_rawDescOnce sync.Once
	file_streamlit_proto_ButtonGroup_proto_rawDescData []byte
)

func file_streamlit_proto_ButtonGroup_proto_rawDescGZIP() []byte {
	file_streamlit_proto_ButtonGroup_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_ButtonGroup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_ButtonGroup_proto_rawDesc), len(file_streamlit_proto_ButtonGroup_proto_rawDesc)))
	})
	return file_streamlit_proto_ButtonGroup_proto_rawDescData
}

var file_streamlit_proto_ButtonGroup_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_streamlit_proto_ButtonGroup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streamlit_proto_ButtonGroup_proto_goTypes = []any{
	(ButtonGroup_ClickMode)(0), // 0: ButtonGroup.ClickMode
	(ButtonGroup_Style)(0),     // 1: ButtonGroup.Style
	(*ButtonGroup)(nil),        // 2: ButtonGroup
	(*ButtonGroup_Option)(nil), // 3: ButtonGroup.Option
	(*LabelVisibility)(nil),    // 4: LabelVisibility
}
var file_streamlit_proto_ButtonGroup_proto_depIdxs = []int32{
	3, // 0: ButtonGroup.options:type_name -> ButtonGroup.Option
	0, // 1: ButtonGroup.click_mode:type_name -> ButtonGroup.ClickMode
	1, // 2: ButtonGroup.style:type_name -> ButtonGroup.Style
	4, // 3: ButtonGroup.label_visibility:type_name -> LabelVisibility
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_streamlit_proto_ButtonGroup_proto_init() }
func file_streamlit_proto_ButtonGroup_proto_init() {
	if File_streamlit_proto_ButtonGroup_proto != nil {
		return
	}
	file_streamlit_proto_LabelVisibility_proto_init()
	file_streamlit_proto_ButtonGroup_proto_msgTypes[0].OneofWrappers = []any{}
	file_streamlit_proto_ButtonGroup_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_ButtonGroup_proto_rawDesc), len(file_streamlit_proto_ButtonGroup_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_ButtonGroup_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_ButtonGroup_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_ButtonGroup_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_ButtonGroup_proto_msgTypes,
	}.Build()
	File_streamlit_proto_ButtonGroup_proto = out.File
	file_streamlit_proto_ButtonGroup_proto_goTypes = nil
	file_streamlit_proto_ButtonGroup_proto_depIdxs = nil
}
