//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Checkbox.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Checkbox_StyleType int32

const (
	Checkbox_DEFAULT Checkbox_StyleType = 0
	Checkbox_TOGGLE  Checkbox_StyleType = 1
)

// Enum value maps for Checkbox_StyleType.
var (
	Checkbox_StyleType_name = map[int32]string{
		0: "DEFAULT",
		1: "TOGGLE",
	}
	Checkbox_StyleType_value = map[string]int32{
		"DEFAULT": 0,
		"TOGGLE":  1,
	}
)

func (x Checkbox_StyleType) Enum() *Checkbox_StyleType {
	p := new(Checkbox_StyleType)
	*p = x
	return p
}

func (x Checkbox_StyleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Checkbox_StyleType) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Checkbox_proto_enumTypes[0].Descriptor()
}

func (Checkbox_StyleType) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Checkbox_proto_enumTypes[0]
}

func (x Checkbox_StyleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Checkbox_StyleType.Descriptor instead.
func (Checkbox_StyleType) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Checkbox_proto_rawDescGZIP(), []int{0, 0}
}

type Checkbox struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label           string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Default         bool                   `protobuf:"varint,3,opt,name=default,proto3" json:"default,omitempty"`
	Help            string                 `protobuf:"bytes,4,opt,name=help,proto3" json:"help,omitempty"`
	FormId          string                 `protobuf:"bytes,5,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Value           bool                   `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	SetValue        bool                   `protobuf:"varint,7,opt,name=set_value,json=setValue,proto3" json:"set_value,omitempty"`
	Disabled        bool                   `protobuf:"varint,8,opt,name=disabled,proto3" json:"disabled,omitempty"`
	LabelVisibility *LabelVisibility       `protobuf:"bytes,9,opt,name=label_visibility,json=labelVisibility,proto3" json:"label_visibility,omitempty"`
	Type            Checkbox_StyleType     `protobuf:"varint,10,opt,name=type,proto3,enum=Checkbox_StyleType" json:"type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Checkbox) Reset() {
	*x = Checkbox{}
	mi := &file_streamlit_proto_Checkbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkbox) ProtoMessage() {}

func (x *Checkbox) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Checkbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkbox.ProtoReflect.Descriptor instead.
func (*Checkbox) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Checkbox_proto_rawDescGZIP(), []int{0}
}

func (x *Checkbox) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Checkbox) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Checkbox) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *Checkbox) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *Checkbox) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *Checkbox) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *Checkbox) GetSetValue() bool {
	if x != nil {
		return x.SetValue
	}
	return false
}

func (x *Checkbox) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Checkbox) GetLabelVisibility() *LabelVisibility {
	if x != nil {
		return x.LabelVisibility
	}
	return nil
}

func (x *Checkbox) GetType() Checkbox_StyleType {
	if x != nil {
		return x.Type
	}
	return Checkbox_DEFAULT
}

var File_streamlit_proto_Checkbox_proto protoreflect.FileDescriptor

const file_streamlit_proto_Checkbox_proto_rawDesc = "" +
	"\n" +
	"\x1estreamlit/proto/Checkbox.proto\x1a%streamlit/proto/LabelVisibility.proto\"\xd2\x02\n" +
	"\bCheckbox\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\adefault\x18\x03 \x01(\bR\adefault\x12\x12\n" +
	"\x04help\x18\x04 \x01(\tR\x04help\x12\x17\n" +
	"\aform_id\x18\x05 \x01(\tR\x06formId\x12\x14\n" +
	"\x05value\x18\x06 \x01(\bR\x05value\x12\x1b\n" +
	"\tset_value\x18\a \x01(\bR\bsetValue\x12\x1a\n" +
	"\bdisabled\x18\b \x01(\bR\bdisabled\x12;\n" +
	"\x10label_visibility\x18\t \x01(\v2\x10.LabelVisibilityR\x0flabelVisibility\x12'\n" +
	"\x04type\x18\n" +
	" \x01(\x0e2\x13.Checkbox.StyleTypeR\x04type\"$\n" +
	"\tStyleType\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\n" +
	"\n" +
	"\x06TOGGLE\x10\x01B1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Checkbox_proto_rawDescOnce sync.Once
	file_streamlit_proto_Checkbox_proto_rawDescData []byte
)

func file_streamlit_proto_Checkbox_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Checkbox_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Checkbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Checkbox_proto_rawDesc), len(file_streamlit_proto_Checkbox_proto_rawDesc)))
	})
	return file_streamlit_proto_Checkbox_proto_rawDescData
}

var file_streamlit_proto_Checkbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_Checkbox_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Checkbox_proto_goTypes = []any{
	(Checkbox_StyleType)(0), // 0: Checkbox.StyleType
	(*Checkbox)(nil),        // 1: Checkbox
	(*LabelVisibility)(nil), // 2: LabelVisibility
}
var file_streamlit_proto_Checkbox_proto_depIdxs = []int32{
	2, // 0: Checkbox.label_visibility:type_name -> LabelVisibility
	0, // 1: Checkbox.type:type_name -> Checkbox.StyleType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Checkbox_proto_init() }
func file_streamlit_proto_Checkbox_proto_init() {
	if File_streamlit_proto_Checkbox_proto != nil {
		return
	}
	file_streamlit_proto_LabelVisibility_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Checkbox_proto_rawDesc), len(file_streamlit_proto_Checkbox_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Checkbox_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Checkbox_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_Checkbox_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_Checkbox_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Checkbox_proto = out.File
	file_streamlit_proto_Checkbox_proto_goTypes = nil
	file_streamlit_proto_Checkbox_proto_depIdxs = nil
}
