//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/ClientState.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContextInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timezone       *string                `protobuf:"bytes,1,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	TimezoneOffset *int32                 `protobuf:"varint,2,opt,name=timezone_offset,json=timezoneOffset,proto3,oneof" json:"timezone_offset,omitempty"`
	Locale         *string                `protobuf:"bytes,3,opt,name=locale,proto3,oneof" json:"locale,omitempty"`
	Url            *string                `protobuf:"bytes,4,opt,name=url,proto3,oneof" json:"url,omitempty"`
	IsEmbedded     *bool                  `protobuf:"varint,5,opt,name=is_embedded,json=isEmbedded,proto3,oneof" json:"is_embedded,omitempty"`
	ColorScheme    *string                `protobuf:"bytes,6,opt,name=color_scheme,json=colorScheme,proto3,oneof" json:"color_scheme,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContextInfo) Reset() {
	*x = ContextInfo{}
	mi := &file_streamlit_proto_ClientState_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextInfo) ProtoMessage() {}

func (x *ContextInfo) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_ClientState_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextInfo.ProtoReflect.Descriptor instead.
func (*ContextInfo) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_ClientState_proto_rawDescGZIP(), []int{0}
}

func (x *ContextInfo) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *ContextInfo) GetTimezoneOffset() int32 {
	if x != nil && x.TimezoneOffset != nil {
		return *x.TimezoneOffset
	}
	return 0
}

func (x *ContextInfo) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

func (x *ContextInfo) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *ContextInfo) GetIsEmbedded() bool {
	if x != nil && x.IsEmbedded != nil {
		return *x.IsEmbedded
	}
	return false
}

func (x *ContextInfo) GetColorScheme() string {
	if x != nil && x.ColorScheme != nil {
		return *x.ColorScheme
	}
	return ""
}

type ClientState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryString    string                 `protobuf:"bytes,1,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`
	WidgetStates   *WidgetStates          `protobuf:"bytes,2,opt,name=widget_states,json=widgetStates,proto3" json:"widget_states,omitempty"`
	PageScriptHash string                 `protobuf:"bytes,3,opt,name=page_script_hash,json=pageScriptHash,proto3" json:"page_script_hash,omitempty"`
	PageName       string                 `protobuf:"bytes,4,opt,name=page_name,json=pageName,proto3" json:"page_name,omitempty"`
	FragmentId     string                 `protobuf:"bytes,5,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	IsAutoRerun    bool                   `protobuf:"varint,6,opt,name=is_auto_rerun,json=isAutoRerun,proto3" json:"is_auto_rerun,omitempty"`
	// List of hashes of messages that are currently cached in
	// the frontend forward message cache.
	CachedMessageHashes []string     `protobuf:"bytes,7,rep,name=cached_message_hashes,json=cachedMessageHashes,proto3" json:"cached_message_hashes,omitempty"`
	ContextInfo         *ContextInfo `protobuf:"bytes,8,opt,name=context_info,json=contextInfo,proto3" json:"context_info,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClientState) Reset() {
	*x = ClientState{}
	mi := &file_streamlit_proto_ClientState_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientState) ProtoMessage() {}

func (x *ClientState) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_ClientState_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientState.ProtoReflect.Descriptor instead.
func (*ClientState) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_ClientState_proto_rawDescGZIP(), []int{1}
}

func (x *ClientState) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

func (x *ClientState) GetWidgetStates() *WidgetStates {
	if x != nil {
		return x.WidgetStates
	}
	return nil
}

func (x *ClientState) GetPageScriptHash() string {
	if x != nil {
		return x.PageScriptHash
	}
	return ""
}

func (x *ClientState) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

func (x *ClientState) GetFragmentId() string {
	if x != nil {
		return x.FragmentId
	}
	return ""
}

func (x *ClientState) GetIsAutoRerun() bool {
	if x != nil {
		return x.IsAutoRerun
	}
	return false
}

func (x *ClientState) GetCachedMessageHashes() []string {
	if x != nil {
		return x.CachedMessageHashes
	}
	return nil
}

func (x *ClientState) GetContextInfo() *ContextInfo {
	if x != nil {
		return x.ContextInfo
	}
	return nil
}

var File_streamlit_proto_ClientState_proto protoreflect.FileDescriptor

const file_streamlit_proto_ClientState_proto_rawDesc = "" +
	"\n" +
	"!streamlit/proto/ClientState.proto\x1a\"streamlit/proto/WidgetStates.proto\"\xb3\x02\n" +
	"\vContextInfo\x12\x1f\n" +
	"\btimezone\x18\x01 \x01(\tH\x00R\btimezone\x88\x01\x01\x12,\n" +
	"\x0ftimezone_offset\x18\x02 \x01(\x05H\x01R\x0etimezoneOffset\x88\x01\x01\x12\x1b\n" +
	"\x06locale\x18\x03 \x01(\tH\x02R\x06locale\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x04 \x01(\tH\x03R\x03url\x88\x01\x01\x12$\n" +
	"\vis_embedded\x18\x05 \x01(\bH\x04R\n" +
	"isEmbedded\x88\x01\x01\x12&\n" +
	"\fcolor_scheme\x18\x06 \x01(\tH\x05R\vcolorScheme\x88\x01\x01B\v\n" +
	"\t_timezoneB\x12\n" +
	"\x10_timezone_offsetB\t\n" +
	"\a_localeB\x06\n" +
	"\x04_urlB\x0e\n" +
	"\f_is_embeddedB\x0f\n" +
	"\r_color_scheme\"\xd5\x02\n" +
	"\vClientState\x12!\n" +
	"\fquery_string\x18\x01 \x01(\tR\vqueryString\x122\n" +
	"\rwidget_states\x18\x02 \x01(\v2\r.WidgetStatesR\fwidgetStates\x12(\n" +
	"\x10page_script_hash\x18\x03 \x01(\tR\x0epageScriptHash\x12\x1b\n" +
	"\tpage_name\x18\x04 \x01(\tR\bpageName\x12\x1f\n" +
	"\vfragment_id\x18\x05 \x01(\tR\n" +
	"fragmentId\x12\"\n" +
	"\ris_auto_rerun\x18\x06 \x01(\bR\visAutoRerun\x122\n" +
	"\x15cached_message_hashes\x18\a \x03(\tR\x13cachedMessageHashes\x12/\n" +
	"\fcontext_info\x18\b \x01(\v2\f.ContextInfoR\vcontextInfoB1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_ClientState_proto_rawDescOnce sync.Once
	file_streamlit_proto_ClientState_proto_rawDescData []byte
)

func file_streamlit_proto_ClientState_proto_rawDescGZIP() []byte {
	file_streamlit_proto_ClientState_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_ClientState_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_ClientState_proto_rawDesc), len(file_streamlit_proto_ClientState_proto_rawDesc)))
	})
	return file_streamlit_proto_ClientState_proto_rawDescData
}

var file_streamlit_proto_ClientState_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streamlit_proto_ClientState_proto_goTypes = []any{
	(*ContextInfo)(nil),  // 0: ContextInfo
	(*ClientState)(nil),  // 1: ClientState
	(*WidgetStates)(nil), // 2: WidgetStates
}
var file_streamlit_proto_ClientState_proto_depIdxs = []int32{
	2, // 0: ClientState.widget_states:type_name -> WidgetStates
	0, // 1: ClientState.context_info:type_name -> ContextInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_streamlit_proto_ClientState_proto_init() }
func file_streamlit_proto_ClientState_proto_init() {
	if File_streamlit_proto_ClientState_proto != nil {
		return
	}
	file_streamlit_proto_WidgetStates_proto_init()
	file_streamlit_proto_ClientState_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_ClientState_proto_rawDesc), len(file_streamlit_proto_ClientState_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_ClientState_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_ClientState_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_ClientState_proto_msgTypes,
	}.Build()
	File_streamlit_proto_ClientState_proto = out.File
	file_streamlit_proto_ClientState_proto_goTypes = nil
	file_streamlit_proto_ClientState_proto_depIdxs = nil
}
