//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Components.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComponentInstance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The instance's "widget ID", used to uniquely identify it.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Argument dictionary, for JSON-serializable args.
	JsonArgs string `protobuf:"bytes,2,opt,name=json_args,json=jsonArgs,proto3" json:"json_args,omitempty"`
	// Additional, non-JSON args. These require special processing
	// on the other end.
	SpecialArgs []*SpecialArg `protobuf:"bytes,3,rep,name=special_args,json=specialArgs,proto3" json:"special_args,omitempty"`
	// The component type's unique name.
	ComponentName string `protobuf:"bytes,4,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	// Optional URL to load the component from. By default this is not set,
	// but while testing, a user can e.g. point this to a local node server
	// that they're developing their component in.
	Url           string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	FormId        string `protobuf:"bytes,6,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	TabIndex      *int32 `protobuf:"varint,7,opt,name=tab_index,json=tabIndex,proto3,oneof" json:"tab_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentInstance) Reset() {
	*x = ComponentInstance{}
	mi := &file_streamlit_proto_Components_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentInstance) ProtoMessage() {}

func (x *ComponentInstance) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Components_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentInstance.ProtoReflect.Descriptor instead.
func (*ComponentInstance) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Components_proto_rawDescGZIP(), []int{0}
}

func (x *ComponentInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComponentInstance) GetJsonArgs() string {
	if x != nil {
		return x.JsonArgs
	}
	return ""
}

func (x *ComponentInstance) GetSpecialArgs() []*SpecialArg {
	if x != nil {
		return x.SpecialArgs
	}
	return nil
}

func (x *ComponentInstance) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *ComponentInstance) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ComponentInstance) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *ComponentInstance) GetTabIndex() int32 {
	if x != nil && x.TabIndex != nil {
		return *x.TabIndex
	}
	return 0
}

type SpecialArg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*SpecialArg_ArrowDataframe
	//	*SpecialArg_Bytes
	Value         isSpecialArg_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialArg) Reset() {
	*x = SpecialArg{}
	mi := &file_streamlit_proto_Components_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialArg) ProtoMessage() {}

func (x *SpecialArg) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Components_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialArg.ProtoReflect.Descriptor instead.
func (*SpecialArg) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Components_proto_rawDescGZIP(), []int{1}
}

func (x *SpecialArg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SpecialArg) GetValue() isSpecialArg_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SpecialArg) GetArrowDataframe() *ArrowDataframe {
	if x != nil {
		if x, ok := x.Value.(*SpecialArg_ArrowDataframe); ok {
			return x.ArrowDataframe
		}
	}
	return nil
}

func (x *SpecialArg) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Value.(*SpecialArg_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

type isSpecialArg_Value interface {
	isSpecialArg_Value()
}

type SpecialArg_ArrowDataframe struct {
	ArrowDataframe *ArrowDataframe `protobuf:"bytes,2,opt,name=arrow_dataframe,json=arrowDataframe,proto3,oneof"`
}

type SpecialArg_Bytes struct {
	Bytes []byte `protobuf:"bytes,3,opt,name=bytes,proto3,oneof"`
}

func (*SpecialArg_ArrowDataframe) isSpecialArg_Value() {}

func (*SpecialArg_Bytes) isSpecialArg_Value() {}

// Components uses Apache Arrow for dataframe serialization.
// This is distinct from `Arrow.proto`: Components was created before
// Streamlit supported Arrow for internal dataframe serialization, and the
// two implementations currently use different logic + data structures.
type ArrowDataframe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ArrowTable            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowDataframe) Reset() {
	*x = ArrowDataframe{}
	mi := &file_streamlit_proto_Components_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowDataframe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowDataframe) ProtoMessage() {}

func (x *ArrowDataframe) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Components_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowDataframe.ProtoReflect.Descriptor instead.
func (*ArrowDataframe) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Components_proto_rawDescGZIP(), []int{2}
}

func (x *ArrowDataframe) GetData() *ArrowTable {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArrowDataframe) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ArrowDataframe) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type ArrowTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Index         []byte                 `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Columns       []byte                 `protobuf:"bytes,3,opt,name=columns,proto3" json:"columns,omitempty"`
	Styler        *ArrowTableStyler      `protobuf:"bytes,5,opt,name=styler,proto3" json:"styler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowTable) Reset() {
	*x = ArrowTable{}
	mi := &file_streamlit_proto_Components_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowTable) ProtoMessage() {}

func (x *ArrowTable) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Components_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowTable.ProtoReflect.Descriptor instead.
func (*ArrowTable) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Components_proto_rawDescGZIP(), []int{3}
}

func (x *ArrowTable) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArrowTable) GetIndex() []byte {
	if x != nil {
		return x.Index
	}
	return nil
}

func (x *ArrowTable) GetColumns() []byte {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ArrowTable) GetStyler() *ArrowTableStyler {
	if x != nil {
		return x.Styler
	}
	return nil
}

type ArrowTableStyler struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Caption       string                 `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	Styles        string                 `protobuf:"bytes,3,opt,name=styles,proto3" json:"styles,omitempty"`
	DisplayValues []byte                 `protobuf:"bytes,4,opt,name=display_values,json=displayValues,proto3" json:"display_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowTableStyler) Reset() {
	*x = ArrowTableStyler{}
	mi := &file_streamlit_proto_Components_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowTableStyler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowTableStyler) ProtoMessage() {}

func (x *ArrowTableStyler) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Components_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowTableStyler.ProtoReflect.Descriptor instead.
func (*ArrowTableStyler) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Components_proto_rawDescGZIP(), []int{4}
}

func (x *ArrowTableStyler) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ArrowTableStyler) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *ArrowTableStyler) GetStyles() string {
	if x != nil {
		return x.Styles
	}
	return ""
}

func (x *ArrowTableStyler) GetDisplayValues() []byte {
	if x != nil {
		return x.DisplayValues
	}
	return nil
}

var File_streamlit_proto_Components_proto protoreflect.FileDescriptor

const file_streamlit_proto_Components_proto_rawDesc = "" +
	"\n" +
	" streamlit/proto/Components.proto\"\xf2\x01\n" +
	"\x11ComponentInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tjson_args\x18\x02 \x01(\tR\bjsonArgs\x12.\n" +
	"\fspecial_args\x18\x03 \x03(\v2\v.SpecialArgR\vspecialArgs\x12%\n" +
	"\x0ecomponent_name\x18\x04 \x01(\tR\rcomponentName\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x17\n" +
	"\aform_id\x18\x06 \x01(\tR\x06formId\x12 \n" +
	"\ttab_index\x18\a \x01(\x05H\x00R\btabIndex\x88\x01\x01B\f\n" +
	"\n" +
	"_tab_index\"{\n" +
	"\n" +
	"SpecialArg\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x0farrow_dataframe\x18\x02 \x01(\v2\x0f.ArrowDataframeH\x00R\x0earrowDataframe\x12\x16\n" +
	"\x05bytes\x18\x03 \x01(\fH\x00R\x05bytesB\a\n" +
	"\x05value\"_\n" +
	"\x0eArrowDataframe\x12\x1f\n" +
	"\x04data\x18\x01 \x01(\v2\v.ArrowTableR\x04data\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\"{\n" +
	"\n" +
	"ArrowTable\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05index\x18\x02 \x01(\fR\x05index\x12\x18\n" +
	"\acolumns\x18\x03 \x01(\fR\acolumns\x12)\n" +
	"\x06styler\x18\x05 \x01(\v2\x11.ArrowTableStylerR\x06styler\"\x7f\n" +
	"\x10ArrowTableStyler\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\acaption\x18\x02 \x01(\tR\acaption\x12\x16\n" +
	"\x06styles\x18\x03 \x01(\tR\x06styles\x12%\n" +
	"\x0edisplay_values\x18\x04 \x01(\fR\rdisplayValuesB1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Components_proto_rawDescOnce sync.Once
	file_streamlit_proto_Components_proto_rawDescData []byte
)

func file_streamlit_proto_Components_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Components_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Components_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Components_proto_rawDesc), len(file_streamlit_proto_Components_proto_rawDesc)))
	})
	return file_streamlit_proto_Components_proto_rawDescData
}

var file_streamlit_proto_Components_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_streamlit_proto_Components_proto_goTypes = []any{
	(*ComponentInstance)(nil), // 0: ComponentInstance
	(*SpecialArg)(nil),        // 1: SpecialArg
	(*ArrowDataframe)(nil),    // 2: ArrowDataframe
	(*ArrowTable)(nil),        // 3: ArrowTable
	(*ArrowTableStyler)(nil),  // 4: ArrowTableStyler
}
var file_streamlit_proto_Components_proto_depIdxs = []int32{
	1, // 0: ComponentInstance.special_args:type_name -> SpecialArg
	2, // 1: SpecialArg.arrow_dataframe:type_name -> ArrowDataframe
	3, // 2: ArrowDataframe.data:type_name -> ArrowTable
	4, // 3: ArrowTable.styler:type_name -> ArrowTableStyler
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Components_proto_init() }
func file_streamlit_proto_Components_proto_init() {
	if File_streamlit_proto_Components_proto != nil {
		return
	}
	file_streamlit_proto_Components_proto_msgTypes[0].OneofWrappers = []any{}
	file_streamlit_proto_Components_proto_msgTypes[1].OneofWrappers = []any{
		(*SpecialArg_ArrowDataframe)(nil),
		(*SpecialArg_Bytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Components_proto_rawDesc), len(file_streamlit_proto_Components_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Components_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Components_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_Components_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Components_proto = out.File
	file_streamlit_proto_Components_proto_goTypes = nil
	file_streamlit_proto_Components_proto_depIdxs = nil
}
