//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/DateInput.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DateInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label           string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Default         []string               `protobuf:"bytes,3,rep,name=default,proto3" json:"default,omitempty"`
	Min             string                 `protobuf:"bytes,4,opt,name=min,proto3" json:"min,omitempty"`
	Max             string                 `protobuf:"bytes,5,opt,name=max,proto3" json:"max,omitempty"`
	IsRange         bool                   `protobuf:"varint,6,opt,name=is_range,json=isRange,proto3" json:"is_range,omitempty"`
	Help            string                 `protobuf:"bytes,7,opt,name=help,proto3" json:"help,omitempty"`
	FormId          string                 `protobuf:"bytes,8,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Value           []string               `protobuf:"bytes,9,rep,name=value,proto3" json:"value,omitempty"`
	SetValue        bool                   `protobuf:"varint,10,opt,name=set_value,json=setValue,proto3" json:"set_value,omitempty"`
	Disabled        bool                   `protobuf:"varint,11,opt,name=disabled,proto3" json:"disabled,omitempty"`
	LabelVisibility *LabelVisibility       `protobuf:"bytes,12,opt,name=label_visibility,json=labelVisibility,proto3" json:"label_visibility,omitempty"`
	Format          string                 `protobuf:"bytes,13,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DateInput) Reset() {
	*x = DateInput{}
	mi := &file_streamlit_proto_DateInput_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateInput) ProtoMessage() {}

func (x *DateInput) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_DateInput_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateInput.ProtoReflect.Descriptor instead.
func (*DateInput) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_DateInput_proto_rawDescGZIP(), []int{0}
}

func (x *DateInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DateInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DateInput) GetDefault() []string {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *DateInput) GetMin() string {
	if x != nil {
		return x.Min
	}
	return ""
}

func (x *DateInput) GetMax() string {
	if x != nil {
		return x.Max
	}
	return ""
}

func (x *DateInput) GetIsRange() bool {
	if x != nil {
		return x.IsRange
	}
	return false
}

func (x *DateInput) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *DateInput) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *DateInput) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DateInput) GetSetValue() bool {
	if x != nil {
		return x.SetValue
	}
	return false
}

func (x *DateInput) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *DateInput) GetLabelVisibility() *LabelVisibility {
	if x != nil {
		return x.LabelVisibility
	}
	return nil
}

func (x *DateInput) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_streamlit_proto_DateInput_proto protoreflect.FileDescriptor

const file_streamlit_proto_DateInput_proto_rawDesc = "" +
	"\n" +
	"\x1fstreamlit/proto/DateInput.proto\x1a%streamlit/proto/LabelVisibility.proto\"\xdb\x02\n" +
	"\tDateInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\adefault\x18\x03 \x03(\tR\adefault\x12\x10\n" +
	"\x03min\x18\x04 \x01(\tR\x03min\x12\x10\n" +
	"\x03max\x18\x05 \x01(\tR\x03max\x12\x19\n" +
	"\bis_range\x18\x06 \x01(\bR\aisRange\x12\x12\n" +
	"\x04help\x18\a \x01(\tR\x04help\x12\x17\n" +
	"\aform_id\x18\b \x01(\tR\x06formId\x12\x14\n" +
	"\x05value\x18\t \x03(\tR\x05value\x12\x1b\n" +
	"\tset_value\x18\n" +
	" \x01(\bR\bsetValue\x12\x1a\n" +
	"\bdisabled\x18\v \x01(\bR\bdisabled\x12;\n" +
	"\x10label_visibility\x18\f \x01(\v2\x10.LabelVisibilityR\x0flabelVisibility\x12\x16\n" +
	"\x06format\x18\r \x01(\tR\x06formatB1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_DateInput_proto_rawDescOnce sync.Once
	file_streamlit_proto_DateInput_proto_rawDescData []byte
)

func file_streamlit_proto_DateInput_proto_rawDescGZIP() []byte {
	file_streamlit_proto_DateInput_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_DateInput_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_DateInput_proto_rawDesc), len(file_streamlit_proto_DateInput_proto_rawDesc)))
	})
	return file_streamlit_proto_DateInput_proto_rawDescData
}

var file_streamlit_proto_DateInput_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_DateInput_proto_goTypes = []any{
	(*DateInput)(nil),       // 0: DateInput
	(*LabelVisibility)(nil), // 1: LabelVisibility
}
var file_streamlit_proto_DateInput_proto_depIdxs = []int32{
	1, // 0: DateInput.label_visibility:type_name -> LabelVisibility
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_DateInput_proto_init() }
func file_streamlit_proto_DateInput_proto_init() {
	if File_streamlit_proto_DateInput_proto != nil {
		return
	}
	file_streamlit_proto_LabelVisibility_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_DateInput_proto_rawDesc), len(file_streamlit_proto_DateInput_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_DateInput_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_DateInput_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_DateInput_proto_msgTypes,
	}.Build()
	File_streamlit_proto_DateInput_proto = out.File
	file_streamlit_proto_DateInput_proto_goTypes = nil
	file_streamlit_proto_DateInput_proto_depIdxs = nil
}
