//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/DeckGlJsonChart.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Available selection modes:
type DeckGlJsonChart_SelectionMode int32

const (
	DeckGlJsonChart_SINGLE_OBJECT DeckGlJsonChart_SelectionMode = 0 // Only one object can be selected at a time.
	DeckGlJsonChart_MULTI_OBJECT  DeckGlJsonChart_SelectionMode = 1 // Multiple objects can be selected at a time.
)

// Enum value maps for DeckGlJsonChart_SelectionMode.
var (
	DeckGlJsonChart_SelectionMode_name = map[int32]string{
		0: "SINGLE_OBJECT",
		1: "MULTI_OBJECT",
	}
	DeckGlJsonChart_SelectionMode_value = map[string]int32{
		"SINGLE_OBJECT": 0,
		"MULTI_OBJECT":  1,
	}
)

func (x DeckGlJsonChart_SelectionMode) Enum() *DeckGlJsonChart_SelectionMode {
	p := new(DeckGlJsonChart_SelectionMode)
	*p = x
	return p
}

func (x DeckGlJsonChart_SelectionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeckGlJsonChart_SelectionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_DeckGlJsonChart_proto_enumTypes[0].Descriptor()
}

func (DeckGlJsonChart_SelectionMode) Type() protoreflect.EnumType {
	return &file_streamlit_proto_DeckGlJsonChart_proto_enumTypes[0]
}

func (x DeckGlJsonChart_SelectionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeckGlJsonChart_SelectionMode.Descriptor instead.
func (DeckGlJsonChart_SelectionMode) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_DeckGlJsonChart_proto_rawDescGZIP(), []int{0, 0}
}

type DeckGlJsonChart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The json of the pydeck object (https://deckgl.readthedocs.io/en/latest/deck.html)
	Json    string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Tooltip string `protobuf:"bytes,2,opt,name=tooltip,proto3" json:"tooltip,omitempty"`
	// ID, required for selection events.
	Id string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	// The Mapbox token, if any.
	MapboxToken string `protobuf:"bytes,6,opt,name=mapbox_token,json=mapboxToken,proto3" json:"mapbox_token,omitempty"`
	// If non-empty, treat this instance as a Widget
	SelectionMode []DeckGlJsonChart_SelectionMode `protobuf:"varint,9,rep,packed,name=selection_mode,json=selectionMode,proto3,enum=DeckGlJsonChart_SelectionMode" json:"selection_mode,omitempty"`
	// The form ID of the widget, this is required if the chart has selection events
	FormId        string `protobuf:"bytes,10,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckGlJsonChart) Reset() {
	*x = DeckGlJsonChart{}
	mi := &file_streamlit_proto_DeckGlJsonChart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckGlJsonChart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckGlJsonChart) ProtoMessage() {}

func (x *DeckGlJsonChart) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_DeckGlJsonChart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckGlJsonChart.ProtoReflect.Descriptor instead.
func (*DeckGlJsonChart) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_DeckGlJsonChart_proto_rawDescGZIP(), []int{0}
}

func (x *DeckGlJsonChart) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *DeckGlJsonChart) GetTooltip() string {
	if x != nil {
		return x.Tooltip
	}
	return ""
}

func (x *DeckGlJsonChart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeckGlJsonChart) GetMapboxToken() string {
	if x != nil {
		return x.MapboxToken
	}
	return ""
}

func (x *DeckGlJsonChart) GetSelectionMode() []DeckGlJsonChart_SelectionMode {
	if x != nil {
		return x.SelectionMode
	}
	return nil
}

func (x *DeckGlJsonChart) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

var File_streamlit_proto_DeckGlJsonChart_proto protoreflect.FileDescriptor

const file_streamlit_proto_DeckGlJsonChart_proto_rawDesc = "" +
	"\n" +
	"%streamlit/proto/DeckGlJsonChart.proto\"\x9a\x02\n" +
	"\x0fDeckGlJsonChart\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12\x18\n" +
	"\atooltip\x18\x02 \x01(\tR\atooltip\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12!\n" +
	"\fmapbox_token\x18\x06 \x01(\tR\vmapboxToken\x12E\n" +
	"\x0eselection_mode\x18\t \x03(\x0e2\x1e.DeckGlJsonChart.SelectionModeR\rselectionMode\x12\x17\n" +
	"\aform_id\x18\n" +
	" \x01(\tR\x06formId\"4\n" +
	"\rSelectionMode\x12\x11\n" +
	"\rSINGLE_OBJECT\x10\x00\x12\x10\n" +
	"\fMULTI_OBJECT\x10\x01J\x04\b\x04\x10\x05J\x04\b\a\x10\bJ\x04\b\b\x10\tB1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_DeckGlJsonChart_proto_rawDescOnce sync.Once
	file_streamlit_proto_DeckGlJsonChart_proto_rawDescData []byte
)

func file_streamlit_proto_DeckGlJsonChart_proto_rawDescGZIP() []byte {
	file_streamlit_proto_DeckGlJsonChart_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_DeckGlJsonChart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_DeckGlJsonChart_proto_rawDesc), len(file_streamlit_proto_DeckGlJsonChart_proto_rawDesc)))
	})
	return file_streamlit_proto_DeckGlJsonChart_proto_rawDescData
}

var file_streamlit_proto_DeckGlJsonChart_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_DeckGlJsonChart_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_DeckGlJsonChart_proto_goTypes = []any{
	(DeckGlJsonChart_SelectionMode)(0), // 0: DeckGlJsonChart.SelectionMode
	(*DeckGlJsonChart)(nil),            // 1: DeckGlJsonChart
}
var file_streamlit_proto_DeckGlJsonChart_proto_depIdxs = []int32{
	0, // 0: DeckGlJsonChart.selection_mode:type_name -> DeckGlJsonChart.SelectionMode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_DeckGlJsonChart_proto_init() }
func file_streamlit_proto_DeckGlJsonChart_proto_init() {
	if File_streamlit_proto_DeckGlJsonChart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_DeckGlJsonChart_proto_rawDesc), len(file_streamlit_proto_DeckGlJsonChart_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_DeckGlJsonChart_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_DeckGlJsonChart_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_DeckGlJsonChart_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_DeckGlJsonChart_proto_msgTypes,
	}.Build()
	File_streamlit_proto_DeckGlJsonChart_proto = out.File
	file_streamlit_proto_DeckGlJsonChart_proto_goTypes = nil
	file_streamlit_proto_DeckGlJsonChart_proto_depIdxs = nil
}
