//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Delta.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A change to an element.
type Delta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Delta_NewElement
	//	*Delta_AddBlock
	//	*Delta_NewTransient
	//	*Delta_ArrowAddRows
	Type          isDelta_Type `protobuf_oneof:"type"`
	FragmentId    string       `protobuf:"bytes,8,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_streamlit_proto_Delta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Delta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Delta_proto_rawDescGZIP(), []int{0}
}

func (x *Delta) GetType() isDelta_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Delta) GetNewElement() *Element {
	if x != nil {
		if x, ok := x.Type.(*Delta_NewElement); ok {
			return x.NewElement
		}
	}
	return nil
}

func (x *Delta) GetAddBlock() *Block {
	if x != nil {
		if x, ok := x.Type.(*Delta_AddBlock); ok {
			return x.AddBlock
		}
	}
	return nil
}

func (x *Delta) GetNewTransient() *Transient {
	if x != nil {
		if x, ok := x.Type.(*Delta_NewTransient); ok {
			return x.NewTransient
		}
	}
	return nil
}

func (x *Delta) GetArrowAddRows() *ArrowNamedDataSet {
	if x != nil {
		if x, ok := x.Type.(*Delta_ArrowAddRows); ok {
			return x.ArrowAddRows
		}
	}
	return nil
}

func (x *Delta) GetFragmentId() string {
	if x != nil {
		return x.FragmentId
	}
	return ""
}

type isDelta_Type interface {
	isDelta_Type()
}

type Delta_NewElement struct {
	// Append a new element to the frontend.
	NewElement *Element `protobuf:"bytes,3,opt,name=new_element,json=newElement,proto3,oneof"`
}

type Delta_AddBlock struct {
	// Append a new block to the frontend.
	AddBlock *Block `protobuf:"bytes,6,opt,name=add_block,json=addBlock,proto3,oneof"`
}

type Delta_NewTransient struct {
	// Append a new transient element (e.g. spinner) to the frontend.
	NewTransient *Transient `protobuf:"bytes,9,opt,name=new_transient,json=newTransient,proto3,oneof"`
}

type Delta_ArrowAddRows struct {
	// Append data to a DataFrame for the current element.
	ArrowAddRows *ArrowNamedDataSet `protobuf:"bytes,7,opt,name=arrow_add_rows,json=arrowAddRows,proto3,oneof"`
}

func (*Delta_NewElement) isDelta_Type() {}

func (*Delta_AddBlock) isDelta_Type() {}

func (*Delta_NewTransient) isDelta_Type() {}

func (*Delta_ArrowAddRows) isDelta_Type() {}

var File_streamlit_proto_Delta_proto protoreflect.FileDescriptor

const file_streamlit_proto_Delta_proto_rawDesc = "" +
	"\n" +
	"\x1bstreamlit/proto/Delta.proto\x1a\x1bstreamlit/proto/Block.proto\x1a\x1dstreamlit/proto/Element.proto\x1a'streamlit/proto/ArrowNamedDataSet.proto\x1a\x1fstreamlit/proto/Transient.proto\"\xf9\x01\n" +
	"\x05Delta\x12+\n" +
	"\vnew_element\x18\x03 \x01(\v2\b.ElementH\x00R\n" +
	"newElement\x12%\n" +
	"\tadd_block\x18\x06 \x01(\v2\x06.BlockH\x00R\baddBlock\x121\n" +
	"\rnew_transient\x18\t \x01(\v2\n" +
	".TransientH\x00R\fnewTransient\x12:\n" +
	"\x0earrow_add_rows\x18\a \x01(\v2\x12.ArrowNamedDataSetH\x00R\farrowAddRows\x12\x1f\n" +
	"\vfragment_id\x18\b \x01(\tR\n" +
	"fragmentIdB\x06\n" +
	"\x04typeJ\x04\b\x05\x10\x06B1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Delta_proto_rawDescOnce sync.Once
	file_streamlit_proto_Delta_proto_rawDescData []byte
)

func file_streamlit_proto_Delta_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Delta_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Delta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Delta_proto_rawDesc), len(file_streamlit_proto_Delta_proto_rawDesc)))
	})
	return file_streamlit_proto_Delta_proto_rawDescData
}

var file_streamlit_proto_Delta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Delta_proto_goTypes = []any{
	(*Delta)(nil),             // 0: Delta
	(*Element)(nil),           // 1: Element
	(*Block)(nil),             // 2: Block
	(*Transient)(nil),         // 3: Transient
	(*ArrowNamedDataSet)(nil), // 4: ArrowNamedDataSet
}
var file_streamlit_proto_Delta_proto_depIdxs = []int32{
	1, // 0: Delta.new_element:type_name -> Element
	2, // 1: Delta.add_block:type_name -> Block
	3, // 2: Delta.new_transient:type_name -> Transient
	4, // 3: Delta.arrow_add_rows:type_name -> ArrowNamedDataSet
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Delta_proto_init() }
func file_streamlit_proto_Delta_proto_init() {
	if File_streamlit_proto_Delta_proto != nil {
		return
	}
	file_streamlit_proto_Block_proto_init()
	file_streamlit_proto_Element_proto_init()
	file_streamlit_proto_ArrowNamedDataSet_proto_init()
	file_streamlit_proto_Transient_proto_init()
	file_streamlit_proto_Delta_proto_msgTypes[0].OneofWrappers = []any{
		(*Delta_NewElement)(nil),
		(*Delta_AddBlock)(nil),
		(*Delta_NewTransient)(nil),
		(*Delta_ArrowAddRows)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Delta_proto_rawDesc), len(file_streamlit_proto_Delta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Delta_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Delta_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_Delta_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Delta_proto = out.File
	file_streamlit_proto_Delta_proto_goTypes = nil
	file_streamlit_proto_Delta_proto_depIdxs = nil
}
