//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/DownloadButton.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadButton struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label             string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Default           bool                   `protobuf:"varint,3,opt,name=default,proto3" json:"default,omitempty"`
	Help              string                 `protobuf:"bytes,4,opt,name=help,proto3" json:"help,omitempty"`
	FormId            string                 `protobuf:"bytes,5,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Url               string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Disabled          bool                   `protobuf:"varint,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	UseContainerWidth bool                   `protobuf:"varint,8,opt,name=use_container_width,json=useContainerWidth,proto3" json:"use_container_width,omitempty"`
	Type              string                 `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	Icon              string                 `protobuf:"bytes,10,opt,name=icon,proto3" json:"icon,omitempty"`
	IgnoreRerun       bool                   `protobuf:"varint,11,opt,name=ignore_rerun,json=ignoreRerun,proto3" json:"ignore_rerun,omitempty"`
	DeferredFileId    *string                `protobuf:"bytes,12,opt,name=deferred_file_id,json=deferredFileId,proto3,oneof" json:"deferred_file_id,omitempty"`
	Shortcut          string                 `protobuf:"bytes,13,opt,name=shortcut,proto3" json:"shortcut,omitempty"`
	IconPosition      ButtonLikeIconPosition `protobuf:"varint,14,opt,name=icon_position,json=iconPosition,proto3,enum=streamlit.ButtonLikeIconPosition" json:"icon_position,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DownloadButton) Reset() {
	*x = DownloadButton{}
	mi := &file_streamlit_proto_DownloadButton_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadButton) ProtoMessage() {}

func (x *DownloadButton) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_DownloadButton_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadButton.ProtoReflect.Descriptor instead.
func (*DownloadButton) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_DownloadButton_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadButton) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadButton) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DownloadButton) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *DownloadButton) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *DownloadButton) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *DownloadButton) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadButton) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *DownloadButton) GetUseContainerWidth() bool {
	if x != nil {
		return x.UseContainerWidth
	}
	return false
}

func (x *DownloadButton) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DownloadButton) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *DownloadButton) GetIgnoreRerun() bool {
	if x != nil {
		return x.IgnoreRerun
	}
	return false
}

func (x *DownloadButton) GetDeferredFileId() string {
	if x != nil && x.DeferredFileId != nil {
		return *x.DeferredFileId
	}
	return ""
}

func (x *DownloadButton) GetShortcut() string {
	if x != nil {
		return x.Shortcut
	}
	return ""
}

func (x *DownloadButton) GetIconPosition() ButtonLikeIconPosition {
	if x != nil {
		return x.IconPosition
	}
	return ButtonLikeIconPosition_LEFT
}

var File_streamlit_proto_DownloadButton_proto protoreflect.FileDescriptor

const file_streamlit_proto_DownloadButton_proto_rawDesc = "" +
	"\n" +
	"$streamlit/proto/DownloadButton.proto\x1a,streamlit/proto/ButtonLikeIconPosition.proto\"\xce\x03\n" +
	"\x0eDownloadButton\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\adefault\x18\x03 \x01(\bR\adefault\x12\x12\n" +
	"\x04help\x18\x04 \x01(\tR\x04help\x12\x17\n" +
	"\aform_id\x18\x05 \x01(\tR\x06formId\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1a\n" +
	"\bdisabled\x18\a \x01(\bR\bdisabled\x12.\n" +
	"\x13use_container_width\x18\b \x01(\bR\x11useContainerWidth\x12\x12\n" +
	"\x04type\x18\t \x01(\tR\x04type\x12\x12\n" +
	"\x04icon\x18\n" +
	" \x01(\tR\x04icon\x12!\n" +
	"\fignore_rerun\x18\v \x01(\bR\vignoreRerun\x12-\n" +
	"\x10deferred_file_id\x18\f \x01(\tH\x00R\x0edeferredFileId\x88\x01\x01\x12\x1a\n" +
	"\bshortcut\x18\r \x01(\tR\bshortcut\x12F\n" +
	"\ricon_position\x18\x0e \x01(\x0e2!.streamlit.ButtonLikeIconPositionR\ficonPositionB\x13\n" +
	"\x11_deferred_file_idB1Z/github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_DownloadButton_proto_rawDescOnce sync.Once
	file_streamlit_proto_DownloadButton_proto_rawDescData []byte
)

func file_streamlit_proto_DownloadButton_proto_rawDescGZIP() []byte {
	file_streamlit_proto_DownloadButton_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_DownloadButton_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_DownloadButton_proto_rawDesc), len(file_streamlit_proto_DownloadButton_proto_rawDesc)))
	})
	return file_streamlit_proto_DownloadButton_proto_rawDescData
}

var file_streamlit_proto_DownloadButton_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_DownloadButton_proto_goTypes = []any{
	(*DownloadButton)(nil),      // 0: DownloadButton
	(ButtonLikeIconPosition)(0), // 1: streamlit.ButtonLikeIconPosition
}
var file_streamlit_proto_DownloadButton_proto_depIdxs = []int32{
	1, // 0: DownloadButton.icon_position:type_name -> streamlit.ButtonLikeIconPosition
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_DownloadButton_proto_init() }
func file_streamlit_proto_DownloadButton_proto_init() {
	if File_streamlit_proto_DownloadButton_proto != nil {
		return
	}
	file_streamlit_proto_ButtonLikeIconPosition_proto_init()
	file_streamlit_proto_DownloadButton_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_DownloadButton_proto_rawDesc), len(file_streamlit_proto_DownloadButton_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_DownloadButton_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_DownloadButton_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_DownloadButton_proto_msgTypes,
	}.Build()
	File_streamlit_proto_DownloadButton_proto = out.File
	file_streamlit_proto_DownloadButton_proto_goTypes = nil
	file_streamlit_proto_DownloadButton_proto_depIdxs = nil
}
