//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Exception.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A python exception.
//
// NOTE: This proto type is used by some external services so needs to remain
// relatively stable. While it isn't entirely set in stone, changing it
// may require a good amount of effort so should be avoided if possible.
type Exception struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the exception. This can be any string, but is usually a valid
	// Python exception type, like 'RuntimeError'.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The exception's message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// If true, the exception message should be rendered as Markdown text.
	MessageIsMarkdown bool `protobuf:"varint,4,opt,name=message_is_markdown,json=messageIsMarkdown,proto3" json:"message_is_markdown,omitempty"`
	// The stack trace to print.
	StackTrace []string `protobuf:"bytes,3,rep,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	// If true, this is an error that doesn't stop the execution flow. So it gets
	// rendered differently for clarity.
	IsWarning bool `protobuf:"varint,5,opt,name=is_warning,json=isWarning,proto3" json:"is_warning,omitempty"`
	// Indicates the width setting: "stetch", "content" or a pixel value.
	WidthConfig   *WidthConfig `protobuf:"bytes,6,opt,name=width_config,json=widthConfig,proto3" json:"width_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exception) Reset() {
	*x = Exception{}
	mi := &file_streamlit_proto_Exception_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exception) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exception) ProtoMessage() {}

func (x *Exception) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Exception_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exception.ProtoReflect.Descriptor instead.
func (*Exception) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Exception_proto_rawDescGZIP(), []int{0}
}

func (x *Exception) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Exception) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Exception) GetMessageIsMarkdown() bool {
	if x != nil {
		return x.MessageIsMarkdown
	}
	return false
}

func (x *Exception) GetStackTrace() []string {
	if x != nil {
		return x.StackTrace
	}
	return nil
}

func (x *Exception) GetIsWarning() bool {
	if x != nil {
		return x.IsWarning
	}
	return false
}

func (x *Exception) GetWidthConfig() *WidthConfig {
	if x != nil {
		return x.WidthConfig
	}
	return nil
}

var File_streamlit_proto_Exception_proto protoreflect.FileDescriptor

const file_streamlit_proto_Exception_proto_rawDesc = "" +
	"\n" +
	"\x1fstreamlit/proto/Exception.proto\x1a!streamlit/proto/WidthConfig.proto\"\xe4\x01\n" +
	"\tException\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x13message_is_markdown\x18\x04 \x01(\bR\x11messageIsMarkdown\x12\x1f\n" +
	"\vstack_trace\x18\x03 \x03(\tR\n" +
	"stackTrace\x12\x1d\n" +
	"\n" +
	"is_warning\x18\x05 \x01(\bR\tisWarning\x129\n" +
	"\fwidth_config\x18\x06 \x01(\v2\x16.streamlit.WidthConfigR\vwidthConfigB3Z1github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Exception_proto_rawDescOnce sync.Once
	file_streamlit_proto_Exception_proto_rawDescData []byte
)

func file_streamlit_proto_Exception_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Exception_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Exception_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Exception_proto_rawDesc), len(file_streamlit_proto_Exception_proto_rawDesc)))
	})
	return file_streamlit_proto_Exception_proto_rawDescData
}

var file_streamlit_proto_Exception_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Exception_proto_goTypes = []any{
	(*Exception)(nil),   // 0: Exception
	(*WidthConfig)(nil), // 1: streamlit.WidthConfig
}
var file_streamlit_proto_Exception_proto_depIdxs = []int32{
	1, // 0: Exception.width_config:type_name -> streamlit.WidthConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Exception_proto_init() }
func file_streamlit_proto_Exception_proto_init() {
	if File_streamlit_proto_Exception_proto != nil {
		return
	}
	file_streamlit_proto_WidthConfig_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Exception_proto_rawDesc), len(file_streamlit_proto_Exception_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Exception_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Exception_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_Exception_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Exception_proto = out.File
	file_streamlit_proto_Exception_proto_goTypes = nil
	file_streamlit_proto_Exception_proto_depIdxs = nil
}
