//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Feedback.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Feedback_FeedbackType int32

const (
	Feedback_THUMBS Feedback_FeedbackType = 0
	Feedback_FACES  Feedback_FeedbackType = 1
	Feedback_STARS  Feedback_FeedbackType = 2
)

// Enum value maps for Feedback_FeedbackType.
var (
	Feedback_FeedbackType_name = map[int32]string{
		0: "THUMBS",
		1: "FACES",
		2: "STARS",
	}
	Feedback_FeedbackType_value = map[string]int32{
		"THUMBS": 0,
		"FACES":  1,
		"STARS":  2,
	}
)

func (x Feedback_FeedbackType) Enum() *Feedback_FeedbackType {
	p := new(Feedback_FeedbackType)
	*p = x
	return p
}

func (x Feedback_FeedbackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Feedback_FeedbackType) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Feedback_proto_enumTypes[0].Descriptor()
}

func (Feedback_FeedbackType) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Feedback_proto_enumTypes[0]
}

func (x Feedback_FeedbackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Feedback_FeedbackType.Descriptor instead.
func (Feedback_FeedbackType) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Feedback_proto_rawDescGZIP(), []int{0, 0}
}

type Feedback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  Feedback_FeedbackType  `protobuf:"varint,2,opt,name=type,proto3,enum=Feedback_FeedbackType" json:"type,omitempty"`
	// Default selection index, uses None/null if not set
	Default  *uint32 `protobuf:"varint,3,opt,name=default,proto3,oneof" json:"default,omitempty"`
	Disabled bool    `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	FormId   string  `protobuf:"bytes,5,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	// Value passed by the backend (selection index)
	Value         *uint32 `protobuf:"varint,6,opt,name=value,proto3,oneof" json:"value,omitempty"`
	SetValue      bool    `protobuf:"varint,7,opt,name=set_value,json=setValue,proto3" json:"set_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feedback) Reset() {
	*x = Feedback{}
	mi := &file_streamlit_proto_Feedback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feedback) ProtoMessage() {}

func (x *Feedback) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Feedback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feedback.ProtoReflect.Descriptor instead.
func (*Feedback) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Feedback_proto_rawDescGZIP(), []int{0}
}

func (x *Feedback) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Feedback) GetType() Feedback_FeedbackType {
	if x != nil {
		return x.Type
	}
	return Feedback_THUMBS
}

func (x *Feedback) GetDefault() uint32 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Feedback) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Feedback) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *Feedback) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *Feedback) GetSetValue() bool {
	if x != nil {
		return x.SetValue
	}
	return false
}

var File_streamlit_proto_Feedback_proto protoreflect.FileDescriptor

const file_streamlit_proto_Feedback_proto_rawDesc = "" +
	"\n" +
	"\x1estreamlit/proto/Feedback.proto\"\x9a\x02\n" +
	"\bFeedback\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.Feedback.FeedbackTypeR\x04type\x12\x1d\n" +
	"\adefault\x18\x03 \x01(\rH\x00R\adefault\x88\x01\x01\x12\x1a\n" +
	"\bdisabled\x18\x04 \x01(\bR\bdisabled\x12\x17\n" +
	"\aform_id\x18\x05 \x01(\tR\x06formId\x12\x19\n" +
	"\x05value\x18\x06 \x01(\rH\x01R\x05value\x88\x01\x01\x12\x1b\n" +
	"\tset_value\x18\a \x01(\bR\bsetValue\"0\n" +
	"\fFeedbackType\x12\n" +
	"\n" +
	"\x06THUMBS\x10\x00\x12\t\n" +
	"\x05FACES\x10\x01\x12\t\n" +
	"\x05STARS\x10\x02B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_valueB1Z/github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Feedback_proto_rawDescOnce sync.Once
	file_streamlit_proto_Feedback_proto_rawDescData []byte
)

func file_streamlit_proto_Feedback_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Feedback_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Feedback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Feedback_proto_rawDesc), len(file_streamlit_proto_Feedback_proto_rawDesc)))
	})
	return file_streamlit_proto_Feedback_proto_rawDescData
}

var file_streamlit_proto_Feedback_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_Feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Feedback_proto_goTypes = []any{
	(Feedback_FeedbackType)(0), // 0: Feedback.FeedbackType
	(*Feedback)(nil),           // 1: Feedback
}
var file_streamlit_proto_Feedback_proto_depIdxs = []int32{
	0, // 0: Feedback.type:type_name -> Feedback.FeedbackType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Feedback_proto_init() }
func file_streamlit_proto_Feedback_proto_init() {
	if File_streamlit_proto_Feedback_proto != nil {
		return
	}
	file_streamlit_proto_Feedback_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Feedback_proto_rawDesc), len(file_streamlit_proto_Feedback_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Feedback_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Feedback_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_Feedback_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_Feedback_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Feedback_proto = out.File
	file_streamlit_proto_Feedback_proto_goTypes = nil
	file_streamlit_proto_Feedback_proto_depIdxs = nil
}
