//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/GapSize.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GapSize int32

const (
	GapSize_GAP_UNDEFINED GapSize = 0
	GapSize_SMALL         GapSize = 1
	GapSize_MEDIUM        GapSize = 2
	GapSize_LARGE         GapSize = 3
	GapSize_NONE          GapSize = 4
	GapSize_XXSMALL       GapSize = 5
	GapSize_XSMALL        GapSize = 6
	GapSize_XLARGE        GapSize = 7
	GapSize_XXLARGE       GapSize = 8
)

// Enum value maps for GapSize.
var (
	GapSize_name = map[int32]string{
		0: "GAP_UNDEFINED",
		1: "SMALL",
		2: "MEDIUM",
		3: "LARGE",
		4: "NONE",
		5: "XXSMALL",
		6: "XSMALL",
		7: "XLARGE",
		8: "XXLARGE",
	}
	GapSize_value = map[string]int32{
		"GAP_UNDEFINED": 0,
		"SMALL":         1,
		"MEDIUM":        2,
		"LARGE":         3,
		"NONE":          4,
		"XXSMALL":       5,
		"XSMALL":        6,
		"XLARGE":        7,
		"XXLARGE":       8,
	}
)

func (x GapSize) Enum() *GapSize {
	p := new(GapSize)
	*p = x
	return p
}

func (x GapSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GapSize) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_GapSize_proto_enumTypes[0].Descriptor()
}

func (GapSize) Type() protoreflect.EnumType {
	return &file_streamlit_proto_GapSize_proto_enumTypes[0]
}

func (x GapSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GapSize.Descriptor instead.
func (GapSize) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_GapSize_proto_rawDescGZIP(), []int{0}
}

type GapConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to GapSpec:
	//
	//	*GapConfig_GapSize
	GapSpec       isGapConfig_GapSpec `protobuf_oneof:"gap_spec"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GapConfig) Reset() {
	*x = GapConfig{}
	mi := &file_streamlit_proto_GapSize_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GapConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GapConfig) ProtoMessage() {}

func (x *GapConfig) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_GapSize_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GapConfig.ProtoReflect.Descriptor instead.
func (*GapConfig) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_GapSize_proto_rawDescGZIP(), []int{0}
}

func (x *GapConfig) GetGapSpec() isGapConfig_GapSpec {
	if x != nil {
		return x.GapSpec
	}
	return nil
}

func (x *GapConfig) GetGapSize() GapSize {
	if x != nil {
		if x, ok := x.GapSpec.(*GapConfig_GapSize); ok {
			return x.GapSize
		}
	}
	return GapSize_GAP_UNDEFINED
}

type isGapConfig_GapSpec interface {
	isGapConfig_GapSpec()
}

type GapConfig_GapSize struct {
	GapSize GapSize `protobuf:"varint,1,opt,name=gap_size,json=gapSize,proto3,enum=streamlit.GapSize,oneof"`
}

func (*GapConfig_GapSize) isGapConfig_GapSpec() {}

var File_streamlit_proto_GapSize_proto protoreflect.FileDescriptor

const file_streamlit_proto_GapSize_proto_rawDesc = "" +
	"\n" +
	"\x1dstreamlit/proto/GapSize.proto\x12\tstreamlit\"H\n" +
	"\tGapConfig\x12/\n" +
	"\bgap_size\x18\x01 \x01(\x0e2\x12.streamlit.GapSizeH\x00R\agapSizeB\n" +
	"\n" +
	"\bgap_spec*z\n" +
	"\aGapSize\x12\x11\n" +
	"\rGAP_UNDEFINED\x10\x00\x12\t\n" +
	"\x05SMALL\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\t\n" +
	"\x05LARGE\x10\x03\x12\b\n" +
	"\x04NONE\x10\x04\x12\v\n" +
	"\aXXSMALL\x10\x05\x12\n" +
	"\n" +
	"\x06XSMALL\x10\x06\x12\n" +
	"\n" +
	"\x06XLARGE\x10\a\x12\v\n" +
	"\aXXLARGE\x10\bB1Z/github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_GapSize_proto_rawDescOnce sync.Once
	file_streamlit_proto_GapSize_proto_rawDescData []byte
)

func file_streamlit_proto_GapSize_proto_rawDescGZIP() []byte {
	file_streamlit_proto_GapSize_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_GapSize_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_GapSize_proto_rawDesc), len(file_streamlit_proto_GapSize_proto_rawDesc)))
	})
	return file_streamlit_proto_GapSize_proto_rawDescData
}

var file_streamlit_proto_GapSize_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_GapSize_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_GapSize_proto_goTypes = []any{
	(GapSize)(0),      // 0: streamlit.GapSize
	(*GapConfig)(nil), // 1: streamlit.GapConfig
}
var file_streamlit_proto_GapSize_proto_depIdxs = []int32{
	0, // 0: streamlit.GapConfig.gap_size:type_name -> streamlit.GapSize
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_GapSize_proto_init() }
func file_streamlit_proto_GapSize_proto_init() {
	if File_streamlit_proto_GapSize_proto != nil {
		return
	}
	file_streamlit_proto_GapSize_proto_msgTypes[0].OneofWrappers = []any{
		(*GapConfig_GapSize)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_GapSize_proto_rawDesc), len(file_streamlit_proto_GapSize_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_GapSize_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_GapSize_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_GapSize_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_GapSize_proto_msgTypes,
	}.Build()
	File_streamlit_proto_GapSize_proto = out.File
	file_streamlit_proto_GapSize_proto_goTypes = nil
	file_streamlit_proto_GapSize_proto_depIdxs = nil
}
