//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/GitInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GitInfo_GitStates int32

const (
	GitInfo_DEFAULT         GitInfo_GitStates = 0
	GitInfo_HEAD_DETACHED   GitInfo_GitStates = 1
	GitInfo_AHEAD_OF_REMOTE GitInfo_GitStates = 2
)

// Enum value maps for GitInfo_GitStates.
var (
	GitInfo_GitStates_name = map[int32]string{
		0: "DEFAULT",
		1: "HEAD_DETACHED",
		2: "AHEAD_OF_REMOTE",
	}
	GitInfo_GitStates_value = map[string]int32{
		"DEFAULT":         0,
		"HEAD_DETACHED":   1,
		"AHEAD_OF_REMOTE": 2,
	}
)

func (x GitInfo_GitStates) Enum() *GitInfo_GitStates {
	p := new(GitInfo_GitStates)
	*p = x
	return p
}

func (x GitInfo_GitStates) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GitInfo_GitStates) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_GitInfo_proto_enumTypes[0].Descriptor()
}

func (GitInfo_GitStates) Type() protoreflect.EnumType {
	return &file_streamlit_proto_GitInfo_proto_enumTypes[0]
}

func (x GitInfo_GitStates) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GitInfo_GitStates.Descriptor instead.
func (GitInfo_GitStates) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_GitInfo_proto_rawDescGZIP(), []int{0, 0}
}

// Message used to update page metadata.
type GitInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Repository       string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Branch           string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Module           string                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	UntrackedFiles   []string               `protobuf:"bytes,4,rep,name=untracked_files,json=untrackedFiles,proto3" json:"untracked_files,omitempty"`
	UncommittedFiles []string               `protobuf:"bytes,5,rep,name=uncommitted_files,json=uncommittedFiles,proto3" json:"uncommitted_files,omitempty"`
	State            GitInfo_GitStates      `protobuf:"varint,6,opt,name=state,proto3,enum=GitInfo_GitStates" json:"state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GitInfo) Reset() {
	*x = GitInfo{}
	mi := &file_streamlit_proto_GitInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitInfo) ProtoMessage() {}

func (x *GitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_GitInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitInfo.ProtoReflect.Descriptor instead.
func (*GitInfo) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_GitInfo_proto_rawDescGZIP(), []int{0}
}

func (x *GitInfo) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *GitInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GitInfo) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *GitInfo) GetUntrackedFiles() []string {
	if x != nil {
		return x.UntrackedFiles
	}
	return nil
}

func (x *GitInfo) GetUncommittedFiles() []string {
	if x != nil {
		return x.UncommittedFiles
	}
	return nil
}

func (x *GitInfo) GetState() GitInfo_GitStates {
	if x != nil {
		return x.State
	}
	return GitInfo_DEFAULT
}

var File_streamlit_proto_GitInfo_proto protoreflect.FileDescriptor

const file_streamlit_proto_GitInfo_proto_rawDesc = "" +
	"\n" +
	"\x1dstreamlit/proto/GitInfo.proto\"\x9b\x02\n" +
	"\aGitInfo\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\x12'\n" +
	"\x0funtracked_files\x18\x04 \x03(\tR\x0euntrackedFiles\x12+\n" +
	"\x11uncommitted_files\x18\x05 \x03(\tR\x10uncommittedFiles\x12(\n" +
	"\x05state\x18\x06 \x01(\x0e2\x12.GitInfo.GitStatesR\x05state\"@\n" +
	"\tGitStates\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\x11\n" +
	"\rHEAD_DETACHED\x10\x01\x12\x13\n" +
	"\x0fAHEAD_OF_REMOTE\x10\x02B1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_GitInfo_proto_rawDescOnce sync.Once
	file_streamlit_proto_GitInfo_proto_rawDescData []byte
)

func file_streamlit_proto_GitInfo_proto_rawDescGZIP() []byte {
	file_streamlit_proto_GitInfo_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_GitInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_GitInfo_proto_rawDesc), len(file_streamlit_proto_GitInfo_proto_rawDesc)))
	})
	return file_streamlit_proto_GitInfo_proto_rawDescData
}

var file_streamlit_proto_GitInfo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_GitInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_GitInfo_proto_goTypes = []any{
	(GitInfo_GitStates)(0), // 0: GitInfo.GitStates
	(*GitInfo)(nil),        // 1: GitInfo
}
var file_streamlit_proto_GitInfo_proto_depIdxs = []int32{
	0, // 0: GitInfo.state:type_name -> GitInfo.GitStates
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_GitInfo_proto_init() }
func file_streamlit_proto_GitInfo_proto_init() {
	if File_streamlit_proto_GitInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_GitInfo_proto_rawDesc), len(file_streamlit_proto_GitInfo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_GitInfo_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_GitInfo_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_GitInfo_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_GitInfo_proto_msgTypes,
	}.Build()
	File_streamlit_proto_GitInfo_proto = out.File
	file_streamlit_proto_GitInfo_proto_goTypes = nil
	file_streamlit_proto_GitInfo_proto_depIdxs = nil
}
