//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Heading.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Heading struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// h1, h2, h3, div, etc
	Tag           string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Anchor        string `protobuf:"bytes,2,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Body          string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Help          string `protobuf:"bytes,4,opt,name=help,proto3" json:"help,omitempty"`
	HideAnchor    bool   `protobuf:"varint,5,opt,name=hide_anchor,json=hideAnchor,proto3" json:"hide_anchor,omitempty"`
	Divider       string `protobuf:"bytes,6,opt,name=divider,proto3" json:"divider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heading) Reset() {
	*x = Heading{}
	mi := &file_streamlit_proto_Heading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heading) ProtoMessage() {}

func (x *Heading) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Heading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heading.ProtoReflect.Descriptor instead.
func (*Heading) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Heading_proto_rawDescGZIP(), []int{0}
}

func (x *Heading) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Heading) GetAnchor() string {
	if x != nil {
		return x.Anchor
	}
	return ""
}

func (x *Heading) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Heading) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *Heading) GetHideAnchor() bool {
	if x != nil {
		return x.HideAnchor
	}
	return false
}

func (x *Heading) GetDivider() string {
	if x != nil {
		return x.Divider
	}
	return ""
}

var File_streamlit_proto_Heading_proto protoreflect.FileDescriptor

const file_streamlit_proto_Heading_proto_rawDesc = "" +
	"\n" +
	"\x1dstreamlit/proto/Heading.proto\"\x96\x01\n" +
	"\aHeading\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x16\n" +
	"\x06anchor\x18\x02 \x01(\tR\x06anchor\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x12\n" +
	"\x04help\x18\x04 \x01(\tR\x04help\x12\x1f\n" +
	"\vhide_anchor\x18\x05 \x01(\bR\n" +
	"hideAnchor\x12\x18\n" +
	"\adivider\x18\x06 \x01(\tR\adividerB1Z/github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Heading_proto_rawDescOnce sync.Once
	file_streamlit_proto_Heading_proto_rawDescData []byte
)

func file_streamlit_proto_Heading_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Heading_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Heading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Heading_proto_rawDesc), len(file_streamlit_proto_Heading_proto_rawDesc)))
	})
	return file_streamlit_proto_Heading_proto_rawDescData
}

var file_streamlit_proto_Heading_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Heading_proto_goTypes = []any{
	(*Heading)(nil), // 0: Heading
}
var file_streamlit_proto_Heading_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Heading_proto_init() }
func file_streamlit_proto_Heading_proto_init() {
	if File_streamlit_proto_Heading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Heading_proto_rawDesc), len(file_streamlit_proto_Heading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Heading_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Heading_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_Heading_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Heading_proto = out.File
	file_streamlit_proto_Heading_proto_goTypes = nil
	file_streamlit_proto_Heading_proto_depIdxs = nil
}
