//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Json.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Json struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content to display.
	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// Controls the initial expansion state of the json element.
	// Is superseded by max_expand_depth if provided.
	Expanded bool `protobuf:"varint,2,opt,name=expanded,proto3" json:"expanded,omitempty"`
	// The maximum depth to expand the JSON object.
	MaxExpandDepth *int32 `protobuf:"varint,3,opt,name=max_expand_depth,json=maxExpandDepth,proto3,oneof" json:"max_expand_depth,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Json) Reset() {
	*x = Json{}
	mi := &file_streamlit_proto_Json_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Json) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Json) ProtoMessage() {}

func (x *Json) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Json_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Json.ProtoReflect.Descriptor instead.
func (*Json) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Json_proto_rawDescGZIP(), []int{0}
}

func (x *Json) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Json) GetExpanded() bool {
	if x != nil {
		return x.Expanded
	}
	return false
}

func (x *Json) GetMaxExpandDepth() int32 {
	if x != nil && x.MaxExpandDepth != nil {
		return *x.MaxExpandDepth
	}
	return 0
}

var File_streamlit_proto_Json_proto protoreflect.FileDescriptor

const file_streamlit_proto_Json_proto_rawDesc = "" +
	"\n" +
	"\x1astreamlit/proto/Json.proto\"z\n" +
	"\x04Json\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12\x1a\n" +
	"\bexpanded\x18\x02 \x01(\bR\bexpanded\x12-\n" +
	"\x10max_expand_depth\x18\x03 \x01(\x05H\x00R\x0emaxExpandDepth\x88\x01\x01B\x13\n" +
	"\x11_max_expand_depthB1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Json_proto_rawDescOnce sync.Once
	file_streamlit_proto_Json_proto_rawDescData []byte
)

func file_streamlit_proto_Json_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Json_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Json_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Json_proto_rawDesc), len(file_streamlit_proto_Json_proto_rawDesc)))
	})
	return file_streamlit_proto_Json_proto_rawDescData
}

var file_streamlit_proto_Json_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Json_proto_goTypes = []any{
	(*Json)(nil), // 0: Json
}
var file_streamlit_proto_Json_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Json_proto_init() }
func file_streamlit_proto_Json_proto_init() {
	if File_streamlit_proto_Json_proto != nil {
		return
	}
	file_streamlit_proto_Json_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Json_proto_rawDesc), len(file_streamlit_proto_Json_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Json_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Json_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_Json_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Json_proto = out.File
	file_streamlit_proto_Json_proto_goTypes = nil
	file_streamlit_proto_Json_proto_depIdxs = nil
}
