//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Logo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of the logo image (image file, emoji, or material icon)
type Logo_ImageType int32

const (
	Logo_IMAGE Logo_ImageType = 0
	Logo_EMOJI Logo_ImageType = 1
	Logo_ICON  Logo_ImageType = 2
)

// Enum value maps for Logo_ImageType.
var (
	Logo_ImageType_name = map[int32]string{
		0: "IMAGE",
		1: "EMOJI",
		2: "ICON",
	}
	Logo_ImageType_value = map[string]int32{
		"IMAGE": 0,
		"EMOJI": 1,
		"ICON":  2,
	}
)

func (x Logo_ImageType) Enum() *Logo_ImageType {
	p := new(Logo_ImageType)
	*p = x
	return p
}

func (x Logo_ImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Logo_ImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Logo_proto_enumTypes[0].Descriptor()
}

func (Logo_ImageType) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Logo_proto_enumTypes[0]
}

func (x Logo_ImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Logo_ImageType.Descriptor instead.
func (Logo_ImageType) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Logo_proto_rawDescGZIP(), []int{0, 0}
}

// Handle the logo for an app
type Logo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	IconImage     string                 `protobuf:"bytes,3,opt,name=icon_image,json=iconImage,proto3" json:"icon_image,omitempty"`
	Size          string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	ImageType     Logo_ImageType         `protobuf:"varint,5,opt,name=image_type,json=imageType,proto3,enum=Logo_ImageType" json:"image_type,omitempty"`
	IconImageType Logo_ImageType         `protobuf:"varint,6,opt,name=icon_image_type,json=iconImageType,proto3,enum=Logo_ImageType" json:"icon_image_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logo) Reset() {
	*x = Logo{}
	mi := &file_streamlit_proto_Logo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logo) ProtoMessage() {}

func (x *Logo) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Logo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logo.ProtoReflect.Descriptor instead.
func (*Logo) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Logo_proto_rawDescGZIP(), []int{0}
}

func (x *Logo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Logo) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Logo) GetIconImage() string {
	if x != nil {
		return x.IconImage
	}
	return ""
}

func (x *Logo) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Logo) GetImageType() Logo_ImageType {
	if x != nil {
		return x.ImageType
	}
	return Logo_IMAGE
}

func (x *Logo) GetIconImageType() Logo_ImageType {
	if x != nil {
		return x.IconImageType
	}
	return Logo_IMAGE
}

var File_streamlit_proto_Logo_proto protoreflect.FileDescriptor

const file_streamlit_proto_Logo_proto_rawDesc = "" +
	"\n" +
	"\x1astreamlit/proto/Logo.proto\"\xf9\x01\n" +
	"\x04Logo\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12\x1d\n" +
	"\n" +
	"icon_image\x18\x03 \x01(\tR\ticonImage\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\x12.\n" +
	"\n" +
	"image_type\x18\x05 \x01(\x0e2\x0f.Logo.ImageTypeR\timageType\x127\n" +
	"\x0ficon_image_type\x18\x06 \x01(\x0e2\x0f.Logo.ImageTypeR\riconImageType\"+\n" +
	"\tImageType\x12\t\n" +
	"\x05IMAGE\x10\x00\x12\t\n" +
	"\x05EMOJI\x10\x01\x12\b\n" +
	"\x04ICON\x10\x02B1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Logo_proto_rawDescOnce sync.Once
	file_streamlit_proto_Logo_proto_rawDescData []byte
)

func file_streamlit_proto_Logo_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Logo_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Logo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Logo_proto_rawDesc), len(file_streamlit_proto_Logo_proto_rawDesc)))
	})
	return file_streamlit_proto_Logo_proto_rawDescData
}

var file_streamlit_proto_Logo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_Logo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Logo_proto_goTypes = []any{
	(Logo_ImageType)(0), // 0: Logo.ImageType
	(*Logo)(nil),        // 1: Logo
}
var file_streamlit_proto_Logo_proto_depIdxs = []int32{
	0, // 0: Logo.image_type:type_name -> Logo.ImageType
	0, // 1: Logo.icon_image_type:type_name -> Logo.ImageType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Logo_proto_init() }
func file_streamlit_proto_Logo_proto_init() {
	if File_streamlit_proto_Logo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Logo_proto_rawDesc), len(file_streamlit_proto_Logo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Logo_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Logo_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_Logo_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_Logo_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Logo_proto = out.File
	file_streamlit_proto_Logo_proto_goTypes = nil
	file_streamlit_proto_Logo_proto_depIdxs = nil
}
