//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Markdown.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Markdown_Type int32

const (
	Markdown_UNSPECIFIED Markdown_Type = 0 // This is recommended to be reserved for proto files backwards compatibility reasons.
	Markdown_NATIVE      Markdown_Type = 1
	Markdown_CAPTION     Markdown_Type = 2
	Markdown_CODE        Markdown_Type = 3
	Markdown_LATEX       Markdown_Type = 4
	Markdown_DIVIDER     Markdown_Type = 5
)

// Enum value maps for Markdown_Type.
var (
	Markdown_Type_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "NATIVE",
		2: "CAPTION",
		3: "CODE",
		4: "LATEX",
		5: "DIVIDER",
	}
	Markdown_Type_value = map[string]int32{
		"UNSPECIFIED": 0,
		"NATIVE":      1,
		"CAPTION":     2,
		"CODE":        3,
		"LATEX":       4,
		"DIVIDER":     5,
	}
)

func (x Markdown_Type) Enum() *Markdown_Type {
	p := new(Markdown_Type)
	*p = x
	return p
}

func (x Markdown_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Markdown_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Markdown_proto_enumTypes[0].Descriptor()
}

func (Markdown_Type) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Markdown_proto_enumTypes[0]
}

func (x Markdown_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Markdown_Type.Descriptor instead.
func (Markdown_Type) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Markdown_proto_rawDescGZIP(), []int{0, 0}
}

// Formatted text
type Markdown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content to display.
	Body          string        `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	AllowHtml     bool          `protobuf:"varint,2,opt,name=allow_html,json=allowHtml,proto3" json:"allow_html,omitempty"`
	ElementType   Markdown_Type `protobuf:"varint,4,opt,name=element_type,json=elementType,proto3,enum=Markdown_Type" json:"element_type,omitempty"`
	Help          string        `protobuf:"bytes,5,opt,name=help,proto3" json:"help,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Markdown) Reset() {
	*x = Markdown{}
	mi := &file_streamlit_proto_Markdown_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Markdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Markdown) ProtoMessage() {}

func (x *Markdown) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Markdown_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Markdown.ProtoReflect.Descriptor instead.
func (*Markdown) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Markdown_proto_rawDescGZIP(), []int{0}
}

func (x *Markdown) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Markdown) GetAllowHtml() bool {
	if x != nil {
		return x.AllowHtml
	}
	return false
}

func (x *Markdown) GetElementType() Markdown_Type {
	if x != nil {
		return x.ElementType
	}
	return Markdown_UNSPECIFIED
}

func (x *Markdown) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

var File_streamlit_proto_Markdown_proto protoreflect.FileDescriptor

const file_streamlit_proto_Markdown_proto_rawDesc = "" +
	"\n" +
	"\x1estreamlit/proto/Markdown.proto\"\xde\x01\n" +
	"\bMarkdown\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"allow_html\x18\x02 \x01(\bR\tallowHtml\x121\n" +
	"\felement_type\x18\x04 \x01(\x0e2\x0e.Markdown.TypeR\velementType\x12\x12\n" +
	"\x04help\x18\x05 \x01(\tR\x04help\"R\n" +
	"\x04Type\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06NATIVE\x10\x01\x12\v\n" +
	"\aCAPTION\x10\x02\x12\b\n" +
	"\x04CODE\x10\x03\x12\t\n" +
	"\x05LATEX\x10\x04\x12\v\n" +
	"\aDIVIDER\x10\x05J\x04\b\x03\x10\x04B3Z1github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Markdown_proto_rawDescOnce sync.Once
	file_streamlit_proto_Markdown_proto_rawDescData []byte
)

func file_streamlit_proto_Markdown_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Markdown_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Markdown_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Markdown_proto_rawDesc), len(file_streamlit_proto_Markdown_proto_rawDesc)))
	})
	return file_streamlit_proto_Markdown_proto_rawDescData
}

var file_streamlit_proto_Markdown_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_Markdown_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Markdown_proto_goTypes = []any{
	(Markdown_Type)(0), // 0: Markdown.Type
	(*Markdown)(nil),   // 1: Markdown
}
var file_streamlit_proto_Markdown_proto_depIdxs = []int32{
	0, // 0: Markdown.element_type:type_name -> Markdown.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Markdown_proto_init() }
func file_streamlit_proto_Markdown_proto_init() {
	if File_streamlit_proto_Markdown_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Markdown_proto_rawDesc), len(file_streamlit_proto_Markdown_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Markdown_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Markdown_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_Markdown_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_Markdown_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Markdown_proto = out.File
	file_streamlit_proto_Markdown_proto_goTypes = nil
	file_streamlit_proto_Markdown_proto_depIdxs = nil
}
