//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/MetricsEvent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metrics events:
type MetricsEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common Event Fields:
	Event            string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	AnonymousId      string `protobuf:"bytes,2,opt,name=anonymous_id,json=anonymousId,proto3" json:"anonymous_id,omitempty"`
	MachineIdV3      string `protobuf:"bytes,3,opt,name=machine_id_v3,json=machineIdV3,proto3" json:"machine_id_v3,omitempty"`
	MachineIdV4      string `protobuf:"bytes,41,opt,name=machine_id_v4,json=machineIdV4,proto3" json:"machine_id_v4,omitempty"`
	ReportHash       string `protobuf:"bytes,4,opt,name=report_hash,json=reportHash,proto3" json:"report_hash,omitempty"`
	Dev              bool   `protobuf:"varint,5,opt,name=dev,proto3" json:"dev,omitempty"`
	Source           string `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	StreamlitVersion string `protobuf:"bytes,7,opt,name=streamlit_version,json=streamlitVersion,proto3" json:"streamlit_version,omitempty"`
	IsHello          bool   `protobuf:"varint,8,opt,name=is_hello,json=isHello,proto3" json:"is_hello,omitempty"`
	AppId            string `protobuf:"bytes,33,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	SessionId        string `protobuf:"bytes,35,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PythonVersion    string `protobuf:"bytes,36,opt,name=python_version,json=pythonVersion,proto3" json:"python_version,omitempty"`
	ServerOs         string `protobuf:"bytes,42,opt,name=server_os,json=serverOs,proto3" json:"server_os,omitempty"`
	HasDisplay       bool   `protobuf:"varint,43,opt,name=has_display,json=hasDisplay,proto3" json:"has_display,omitempty"`
	IsWebdriver      bool   `protobuf:"varint,44,opt,name=is_webdriver,json=isWebdriver,proto3" json:"is_webdriver,omitempty"`
	// Host tracking fields:
	HostedAt   string `protobuf:"bytes,9,opt,name=hosted_at,json=hostedAt,proto3" json:"hosted_at,omitempty"`
	Owner      string `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo       string `protobuf:"bytes,11,opt,name=repo,proto3" json:"repo,omitempty"`
	Branch     string `protobuf:"bytes,12,opt,name=branch,proto3" json:"branch,omitempty"`
	MainModule string `protobuf:"bytes,13,opt,name=main_module,json=mainModule,proto3" json:"main_module,omitempty"`
	CreatorId  string `protobuf:"bytes,14,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	// Context fields:
	ContextPageUrl      string `protobuf:"bytes,15,opt,name=context_page_url,json=contextPageUrl,proto3" json:"context_page_url,omitempty"`
	ContextPageTitle    string `protobuf:"bytes,16,opt,name=context_page_title,json=contextPageTitle,proto3" json:"context_page_title,omitempty"`
	ContextPagePath     string `protobuf:"bytes,17,opt,name=context_page_path,json=contextPagePath,proto3" json:"context_page_path,omitempty"`
	ContextPageReferrer string `protobuf:"bytes,18,opt,name=context_page_referrer,json=contextPageReferrer,proto3" json:"context_page_referrer,omitempty"`
	ContextPageSearch   string `protobuf:"bytes,19,opt,name=context_page_search,json=contextPageSearch,proto3" json:"context_page_search,omitempty"`
	ContextLocale       string `protobuf:"bytes,20,opt,name=context_locale,json=contextLocale,proto3" json:"context_locale,omitempty"`
	ContextUserAgent    string `protobuf:"bytes,21,opt,name=context_user_agent,json=contextUserAgent,proto3" json:"context_user_agent,omitempty"`
	// Menu Click Event field:
	Label string `protobuf:"bytes,22,opt,name=label,proto3" json:"label,omitempty"`
	// Page Profile Event fields:
	// Same as PageProfile msg
	Commands          []*Command `protobuf:"bytes,23,rep,name=commands,proto3" json:"commands,omitempty"`
	ExecTime          int64      `protobuf:"varint,24,opt,name=exec_time,json=execTime,proto3" json:"exec_time,omitempty"`
	PrepTime          int64      `protobuf:"varint,25,opt,name=prep_time,json=prepTime,proto3" json:"prep_time,omitempty"`
	Config            []string   `protobuf:"bytes,26,rep,name=config,proto3" json:"config,omitempty"`
	UncaughtException string     `protobuf:"bytes,27,opt,name=uncaught_exception,json=uncaughtException,proto3" json:"uncaught_exception,omitempty"`
	Attributions      []string   `protobuf:"bytes,28,rep,name=attributions,proto3" json:"attributions,omitempty"`
	Os                string     `protobuf:"bytes,29,opt,name=os,proto3" json:"os,omitempty"`
	Timezone          string     `protobuf:"bytes,30,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Headless          bool       `protobuf:"varint,31,opt,name=headless,proto3" json:"headless,omitempty"`
	IsFragmentRun     bool       `protobuf:"varint,32,opt,name=is_fragment_run,json=isFragmentRun,proto3" json:"is_fragment_run,omitempty"`
	// Addtl for page profile metrics
	NumPages       int64        `protobuf:"varint,34,opt,name=numPages,proto3" json:"numPages,omitempty"`
	PageScriptHash string       `protobuf:"bytes,37,opt,name=page_script_hash,json=pageScriptHash,proto3" json:"page_script_hash,omitempty"`
	ActiveTheme    string       `protobuf:"bytes,38,opt,name=active_theme,json=activeTheme,proto3" json:"active_theme,omitempty"`
	TotalLoadTime  int64        `protobuf:"varint,39,opt,name=total_load_time,json=totalLoadTime,proto3" json:"total_load_time,omitempty"`
	BrowserInfo    *BrowserInfo `protobuf:"bytes,40,opt,name=browser_info,json=browserInfo,proto3" json:"browser_info,omitempty"`
	ServerMode     string       `protobuf:"bytes,45,opt,name=server_mode,json=serverMode,proto3" json:"server_mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsEvent) Reset() {
	*x = MetricsEvent{}
	mi := &file_streamlit_proto_MetricsEvent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsEvent) ProtoMessage() {}

func (x *MetricsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_MetricsEvent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsEvent.ProtoReflect.Descriptor instead.
func (*MetricsEvent) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_MetricsEvent_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *MetricsEvent) GetAnonymousId() string {
	if x != nil {
		return x.AnonymousId
	}
	return ""
}

func (x *MetricsEvent) GetMachineIdV3() string {
	if x != nil {
		return x.MachineIdV3
	}
	return ""
}

func (x *MetricsEvent) GetMachineIdV4() string {
	if x != nil {
		return x.MachineIdV4
	}
	return ""
}

func (x *MetricsEvent) GetReportHash() string {
	if x != nil {
		return x.ReportHash
	}
	return ""
}

func (x *MetricsEvent) GetDev() bool {
	if x != nil {
		return x.Dev
	}
	return false
}

func (x *MetricsEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MetricsEvent) GetStreamlitVersion() string {
	if x != nil {
		return x.StreamlitVersion
	}
	return ""
}

func (x *MetricsEvent) GetIsHello() bool {
	if x != nil {
		return x.IsHello
	}
	return false
}

func (x *MetricsEvent) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *MetricsEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MetricsEvent) GetPythonVersion() string {
	if x != nil {
		return x.PythonVersion
	}
	return ""
}

func (x *MetricsEvent) GetServerOs() string {
	if x != nil {
		return x.ServerOs
	}
	return ""
}

func (x *MetricsEvent) GetHasDisplay() bool {
	if x != nil {
		return x.HasDisplay
	}
	return false
}

func (x *MetricsEvent) GetIsWebdriver() bool {
	if x != nil {
		return x.IsWebdriver
	}
	return false
}

func (x *MetricsEvent) GetHostedAt() string {
	if x != nil {
		return x.HostedAt
	}
	return ""
}

func (x *MetricsEvent) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MetricsEvent) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *MetricsEvent) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *MetricsEvent) GetMainModule() string {
	if x != nil {
		return x.MainModule
	}
	return ""
}

func (x *MetricsEvent) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *MetricsEvent) GetContextPageUrl() string {
	if x != nil {
		return x.ContextPageUrl
	}
	return ""
}

func (x *MetricsEvent) GetContextPageTitle() string {
	if x != nil {
		return x.ContextPageTitle
	}
	return ""
}

func (x *MetricsEvent) GetContextPagePath() string {
	if x != nil {
		return x.ContextPagePath
	}
	return ""
}

func (x *MetricsEvent) GetContextPageReferrer() string {
	if x != nil {
		return x.ContextPageReferrer
	}
	return ""
}

func (x *MetricsEvent) GetContextPageSearch() string {
	if x != nil {
		return x.ContextPageSearch
	}
	return ""
}

func (x *MetricsEvent) GetContextLocale() string {
	if x != nil {
		return x.ContextLocale
	}
	return ""
}

func (x *MetricsEvent) GetContextUserAgent() string {
	if x != nil {
		return x.ContextUserAgent
	}
	return ""
}

func (x *MetricsEvent) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MetricsEvent) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *MetricsEvent) GetExecTime() int64 {
	if x != nil {
		return x.ExecTime
	}
	return 0
}

func (x *MetricsEvent) GetPrepTime() int64 {
	if x != nil {
		return x.PrepTime
	}
	return 0
}

func (x *MetricsEvent) GetConfig() []string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *MetricsEvent) GetUncaughtException() string {
	if x != nil {
		return x.UncaughtException
	}
	return ""
}

func (x *MetricsEvent) GetAttributions() []string {
	if x != nil {
		return x.Attributions
	}
	return nil
}

func (x *MetricsEvent) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *MetricsEvent) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *MetricsEvent) GetHeadless() bool {
	if x != nil {
		return x.Headless
	}
	return false
}

func (x *MetricsEvent) GetIsFragmentRun() bool {
	if x != nil {
		return x.IsFragmentRun
	}
	return false
}

func (x *MetricsEvent) GetNumPages() int64 {
	if x != nil {
		return x.NumPages
	}
	return 0
}

func (x *MetricsEvent) GetPageScriptHash() string {
	if x != nil {
		return x.PageScriptHash
	}
	return ""
}

func (x *MetricsEvent) GetActiveTheme() string {
	if x != nil {
		return x.ActiveTheme
	}
	return ""
}

func (x *MetricsEvent) GetTotalLoadTime() int64 {
	if x != nil {
		return x.TotalLoadTime
	}
	return 0
}

func (x *MetricsEvent) GetBrowserInfo() *BrowserInfo {
	if x != nil {
		return x.BrowserInfo
	}
	return nil
}

func (x *MetricsEvent) GetServerMode() string {
	if x != nil {
		return x.ServerMode
	}
	return ""
}

type BrowserInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BrowserName    string                 `protobuf:"bytes,1,opt,name=browser_name,json=browserName,proto3" json:"browser_name,omitempty"`
	BrowserVersion string                 `protobuf:"bytes,2,opt,name=browser_version,json=browserVersion,proto3" json:"browser_version,omitempty"`
	DeviceType     string                 `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Os             string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BrowserInfo) Reset() {
	*x = BrowserInfo{}
	mi := &file_streamlit_proto_MetricsEvent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserInfo) ProtoMessage() {}

func (x *BrowserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_MetricsEvent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserInfo.ProtoReflect.Descriptor instead.
func (*BrowserInfo) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_MetricsEvent_proto_rawDescGZIP(), []int{1}
}

func (x *BrowserInfo) GetBrowserName() string {
	if x != nil {
		return x.BrowserName
	}
	return ""
}

func (x *BrowserInfo) GetBrowserVersion() string {
	if x != nil {
		return x.BrowserVersion
	}
	return ""
}

func (x *BrowserInfo) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *BrowserInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

var File_streamlit_proto_MetricsEvent_proto protoreflect.FileDescriptor

const file_streamlit_proto_MetricsEvent_proto_rawDesc = "" +
	"\n" +
	"\"streamlit/proto/MetricsEvent.proto\x1a!streamlit/proto/PageProfile.proto\"\xf0\v\n" +
	"\fMetricsEvent\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12!\n" +
	"\fanonymous_id\x18\x02 \x01(\tR\vanonymousId\x12\"\n" +
	"\rmachine_id_v3\x18\x03 \x01(\tR\vmachineIdV3\x12\"\n" +
	"\rmachine_id_v4\x18) \x01(\tR\vmachineIdV4\x12\x1f\n" +
	"\vreport_hash\x18\x04 \x01(\tR\n" +
	"reportHash\x12\x10\n" +
	"\x03dev\x18\x05 \x01(\bR\x03dev\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12+\n" +
	"\x11streamlit_version\x18\a \x01(\tR\x10streamlitVersion\x12\x19\n" +
	"\bis_hello\x18\b \x01(\bR\aisHello\x12\x15\n" +
	"\x06app_id\x18! \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"session_id\x18# \x01(\tR\tsessionId\x12%\n" +
	"\x0epython_version\x18$ \x01(\tR\rpythonVersion\x12\x1b\n" +
	"\tserver_os\x18* \x01(\tR\bserverOs\x12\x1f\n" +
	"\vhas_display\x18+ \x01(\bR\n" +
	"hasDisplay\x12!\n" +
	"\fis_webdriver\x18, \x01(\bR\visWebdriver\x12\x1b\n" +
	"\thosted_at\x18\t \x01(\tR\bhostedAt\x12\x14\n" +
	"\x05owner\x18\n" +
	" \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\v \x01(\tR\x04repo\x12\x16\n" +
	"\x06branch\x18\f \x01(\tR\x06branch\x12\x1f\n" +
	"\vmain_module\x18\r \x01(\tR\n" +
	"mainModule\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x0e \x01(\tR\tcreatorId\x12(\n" +
	"\x10context_page_url\x18\x0f \x01(\tR\x0econtextPageUrl\x12,\n" +
	"\x12context_page_title\x18\x10 \x01(\tR\x10contextPageTitle\x12*\n" +
	"\x11context_page_path\x18\x11 \x01(\tR\x0fcontextPagePath\x122\n" +
	"\x15context_page_referrer\x18\x12 \x01(\tR\x13contextPageReferrer\x12.\n" +
	"\x13context_page_search\x18\x13 \x01(\tR\x11contextPageSearch\x12%\n" +
	"\x0econtext_locale\x18\x14 \x01(\tR\rcontextLocale\x12,\n" +
	"\x12context_user_agent\x18\x15 \x01(\tR\x10contextUserAgent\x12\x14\n" +
	"\x05label\x18\x16 \x01(\tR\x05label\x12$\n" +
	"\bcommands\x18\x17 \x03(\v2\b.CommandR\bcommands\x12\x1b\n" +
	"\texec_time\x18\x18 \x01(\x03R\bexecTime\x12\x1b\n" +
	"\tprep_time\x18\x19 \x01(\x03R\bprepTime\x12\x16\n" +
	"\x06config\x18\x1a \x03(\tR\x06config\x12-\n" +
	"\x12uncaught_exception\x18\x1b \x01(\tR\x11uncaughtException\x12\"\n" +
	"\fattributions\x18\x1c \x03(\tR\fattributions\x12\x0e\n" +
	"\x02os\x18\x1d \x01(\tR\x02os\x12\x1a\n" +
	"\btimezone\x18\x1e \x01(\tR\btimezone\x12\x1a\n" +
	"\bheadless\x18\x1f \x01(\bR\bheadless\x12&\n" +
	"\x0fis_fragment_run\x18  \x01(\bR\risFragmentRun\x12\x1a\n" +
	"\bnumPages\x18\" \x01(\x03R\bnumPages\x12(\n" +
	"\x10page_script_hash\x18% \x01(\tR\x0epageScriptHash\x12!\n" +
	"\factive_theme\x18& \x01(\tR\vactiveTheme\x12&\n" +
	"\x0ftotal_load_time\x18' \x01(\x03R\rtotalLoadTime\x12/\n" +
	"\fbrowser_info\x18( \x01(\v2\f.BrowserInfoR\vbrowserInfo\x12\x1f\n" +
	"\vserver_mode\x18- \x01(\tR\n" +
	"serverMode\"\x8a\x01\n" +
	"\vBrowserInfo\x12!\n" +
	"\fbrowser_name\x18\x01 \x01(\tR\vbrowserName\x12'\n" +
	"\x0fbrowser_version\x18\x02 \x01(\tR\x0ebrowserVersion\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02osB1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_MetricsEvent_proto_rawDescOnce sync.Once
	file_streamlit_proto_MetricsEvent_proto_rawDescData []byte
)

func file_streamlit_proto_MetricsEvent_proto_rawDescGZIP() []byte {
	file_streamlit_proto_MetricsEvent_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_MetricsEvent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_MetricsEvent_proto_rawDesc), len(file_streamlit_proto_MetricsEvent_proto_rawDesc)))
	})
	return file_streamlit_proto_MetricsEvent_proto_rawDescData
}

var file_streamlit_proto_MetricsEvent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streamlit_proto_MetricsEvent_proto_goTypes = []any{
	(*MetricsEvent)(nil), // 0: MetricsEvent
	(*BrowserInfo)(nil),  // 1: BrowserInfo
	(*Command)(nil),      // 2: Command
}
var file_streamlit_proto_MetricsEvent_proto_depIdxs = []int32{
	2, // 0: MetricsEvent.commands:type_name -> Command
	1, // 1: MetricsEvent.browser_info:type_name -> BrowserInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_streamlit_proto_MetricsEvent_proto_init() }
func file_streamlit_proto_MetricsEvent_proto_init() {
	if File_streamlit_proto_MetricsEvent_proto != nil {
		return
	}
	file_streamlit_proto_PageProfile_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_MetricsEvent_proto_rawDesc), len(file_streamlit_proto_MetricsEvent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_MetricsEvent_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_MetricsEvent_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_MetricsEvent_proto_msgTypes,
	}.Build()
	File_streamlit_proto_MetricsEvent_proto = out.File
	file_streamlit_proto_MetricsEvent_proto_goTypes = nil
	file_streamlit_proto_MetricsEvent_proto_depIdxs = nil
}
