//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Metric.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric_MetricDirection int32

const (
	Metric_DOWN Metric_MetricDirection = 0
	Metric_UP   Metric_MetricDirection = 1
	Metric_NONE Metric_MetricDirection = 2
)

// Enum value maps for Metric_MetricDirection.
var (
	Metric_MetricDirection_name = map[int32]string{
		0: "DOWN",
		1: "UP",
		2: "NONE",
	}
	Metric_MetricDirection_value = map[string]int32{
		"DOWN": 0,
		"UP":   1,
		"NONE": 2,
	}
)

func (x Metric_MetricDirection) Enum() *Metric_MetricDirection {
	p := new(Metric_MetricDirection)
	*p = x
	return p
}

func (x Metric_MetricDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_MetricDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Metric_proto_enumTypes[0].Descriptor()
}

func (Metric_MetricDirection) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Metric_proto_enumTypes[0]
}

func (x Metric_MetricDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_MetricDirection.Descriptor instead.
func (Metric_MetricDirection) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Metric_proto_rawDescGZIP(), []int{0, 0}
}

type Metric_MetricColor int32

const (
	Metric_RED     Metric_MetricColor = 0
	Metric_GREEN   Metric_MetricColor = 1
	Metric_GRAY    Metric_MetricColor = 2
	Metric_ORANGE  Metric_MetricColor = 3
	Metric_YELLOW  Metric_MetricColor = 4
	Metric_BLUE    Metric_MetricColor = 5
	Metric_VIOLET  Metric_MetricColor = 6
	Metric_PRIMARY Metric_MetricColor = 7
)

// Enum value maps for Metric_MetricColor.
var (
	Metric_MetricColor_name = map[int32]string{
		0: "RED",
		1: "GREEN",
		2: "GRAY",
		3: "ORANGE",
		4: "YELLOW",
		5: "BLUE",
		6: "VIOLET",
		7: "PRIMARY",
	}
	Metric_MetricColor_value = map[string]int32{
		"RED":     0,
		"GREEN":   1,
		"GRAY":    2,
		"ORANGE":  3,
		"YELLOW":  4,
		"BLUE":    5,
		"VIOLET":  6,
		"PRIMARY": 7,
	}
)

func (x Metric_MetricColor) Enum() *Metric_MetricColor {
	p := new(Metric_MetricColor)
	*p = x
	return p
}

func (x Metric_MetricColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_MetricColor) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Metric_proto_enumTypes[1].Descriptor()
}

func (Metric_MetricColor) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Metric_proto_enumTypes[1]
}

func (x Metric_MetricColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_MetricColor.Descriptor instead.
func (Metric_MetricColor) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Metric_proto_rawDescGZIP(), []int{0, 1}
}

type Metric_ChartType int32

const (
	Metric_LINE Metric_ChartType = 0
	Metric_BAR  Metric_ChartType = 1
	Metric_AREA Metric_ChartType = 2
)

// Enum value maps for Metric_ChartType.
var (
	Metric_ChartType_name = map[int32]string{
		0: "LINE",
		1: "BAR",
		2: "AREA",
	}
	Metric_ChartType_value = map[string]int32{
		"LINE": 0,
		"BAR":  1,
		"AREA": 2,
	}
)

func (x Metric_ChartType) Enum() *Metric_ChartType {
	p := new(Metric_ChartType)
	*p = x
	return p
}

func (x Metric_ChartType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_ChartType) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Metric_proto_enumTypes[2].Descriptor()
}

func (Metric_ChartType) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Metric_proto_enumTypes[2]
}

func (x Metric_ChartType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_ChartType.Descriptor instead.
func (Metric_ChartType) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Metric_proto_rawDescGZIP(), []int{0, 2}
}

type Metric struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Label           string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Body            string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Delta           string                 `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Direction       Metric_MetricDirection `protobuf:"varint,4,opt,name=direction,proto3,enum=Metric_MetricDirection" json:"direction,omitempty"`
	Color           Metric_MetricColor     `protobuf:"varint,5,opt,name=color,proto3,enum=Metric_MetricColor" json:"color,omitempty"`
	Help            string                 `protobuf:"bytes,6,opt,name=help,proto3" json:"help,omitempty"`
	LabelVisibility *LabelVisibility       `protobuf:"bytes,7,opt,name=label_visibility,json=labelVisibility,proto3" json:"label_visibility,omitempty"`
	ShowBorder      bool                   `protobuf:"varint,8,opt,name=show_border,json=showBorder,proto3" json:"show_border,omitempty"`
	ChartData       []float64              `protobuf:"fixed64,9,rep,packed,name=chart_data,json=chartData,proto3" json:"chart_data,omitempty"`
	ChartType       Metric_ChartType       `protobuf:"varint,10,opt,name=chart_type,json=chartType,proto3,enum=Metric_ChartType" json:"chart_type,omitempty"`
	// Format string for the value and delta (applied only if they are numeric).
	Format        string `protobuf:"bytes,11,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_streamlit_proto_Metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Metric_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Metric) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Metric) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *Metric) GetDirection() Metric_MetricDirection {
	if x != nil {
		return x.Direction
	}
	return Metric_DOWN
}

func (x *Metric) GetColor() Metric_MetricColor {
	if x != nil {
		return x.Color
	}
	return Metric_RED
}

func (x *Metric) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *Metric) GetLabelVisibility() *LabelVisibility {
	if x != nil {
		return x.LabelVisibility
	}
	return nil
}

func (x *Metric) GetShowBorder() bool {
	if x != nil {
		return x.ShowBorder
	}
	return false
}

func (x *Metric) GetChartData() []float64 {
	if x != nil {
		return x.ChartData
	}
	return nil
}

func (x *Metric) GetChartType() Metric_ChartType {
	if x != nil {
		return x.ChartType
	}
	return Metric_LINE
}

func (x *Metric) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_streamlit_proto_Metric_proto protoreflect.FileDescriptor

const file_streamlit_proto_Metric_proto_rawDesc = "" +
	"\n" +
	"\x1cstreamlit/proto/Metric.proto\x1a%streamlit/proto/LabelVisibility.proto\"\xc6\x04\n" +
	"\x06Metric\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\tR\x05delta\x125\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x17.Metric.MetricDirectionR\tdirection\x12)\n" +
	"\x05color\x18\x05 \x01(\x0e2\x13.Metric.MetricColorR\x05color\x12\x12\n" +
	"\x04help\x18\x06 \x01(\tR\x04help\x12;\n" +
	"\x10label_visibility\x18\a \x01(\v2\x10.LabelVisibilityR\x0flabelVisibility\x12\x1f\n" +
	"\vshow_border\x18\b \x01(\bR\n" +
	"showBorder\x12\x1d\n" +
	"\n" +
	"chart_data\x18\t \x03(\x01R\tchartData\x120\n" +
	"\n" +
	"chart_type\x18\n" +
	" \x01(\x0e2\x11.Metric.ChartTypeR\tchartType\x12\x16\n" +
	"\x06format\x18\v \x01(\tR\x06format\"-\n" +
	"\x0fMetricDirection\x12\b\n" +
	"\x04DOWN\x10\x00\x12\x06\n" +
	"\x02UP\x10\x01\x12\b\n" +
	"\x04NONE\x10\x02\"f\n" +
	"\vMetricColor\x12\a\n" +
	"\x03RED\x10\x00\x12\t\n" +
	"\x05GREEN\x10\x01\x12\b\n" +
	"\x04GRAY\x10\x02\x12\n" +
	"\n" +
	"\x06ORANGE\x10\x03\x12\n" +
	"\n" +
	"\x06YELLOW\x10\x04\x12\b\n" +
	"\x04BLUE\x10\x05\x12\n" +
	"\n" +
	"\x06VIOLET\x10\x06\x12\v\n" +
	"\aPRIMARY\x10\a\"(\n" +
	"\tChartType\x12\b\n" +
	"\x04LINE\x10\x00\x12\a\n" +
	"\x03BAR\x10\x01\x12\b\n" +
	"\x04AREA\x10\x02B3Z1github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Metric_proto_rawDescOnce sync.Once
	file_streamlit_proto_Metric_proto_rawDescData []byte
)

func file_streamlit_proto_Metric_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Metric_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Metric_proto_rawDesc), len(file_streamlit_proto_Metric_proto_rawDesc)))
	})
	return file_streamlit_proto_Metric_proto_rawDescData
}

var file_streamlit_proto_Metric_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_streamlit_proto_Metric_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Metric_proto_goTypes = []any{
	(Metric_MetricDirection)(0), // 0: Metric.MetricDirection
	(Metric_MetricColor)(0),     // 1: Metric.MetricColor
	(Metric_ChartType)(0),       // 2: Metric.ChartType
	(*Metric)(nil),              // 3: Metric
	(*LabelVisibility)(nil),     // 4: LabelVisibility
}
var file_streamlit_proto_Metric_proto_depIdxs = []int32{
	0, // 0: Metric.direction:type_name -> Metric.MetricDirection
	1, // 1: Metric.color:type_name -> Metric.MetricColor
	4, // 2: Metric.label_visibility:type_name -> LabelVisibility
	2, // 3: Metric.chart_type:type_name -> Metric.ChartType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Metric_proto_init() }
func file_streamlit_proto_Metric_proto_init() {
	if File_streamlit_proto_Metric_proto != nil {
		return
	}
	file_streamlit_proto_LabelVisibility_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Metric_proto_rawDesc), len(file_streamlit_proto_Metric_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Metric_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Metric_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_Metric_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_Metric_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Metric_proto = out.File
	file_streamlit_proto_Metric_proto_goTypes = nil
	file_streamlit_proto_Metric_proto_depIdxs = nil
}
