//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Navigation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Position of the Navigation
type Navigation_Position int32

const (
	// do not display the navigation
	Navigation_HIDDEN Navigation_Position = 0
	// display navigation in the sidebar
	Navigation_SIDEBAR Navigation_Position = 1
	// display navigation in the top header
	Navigation_TOP Navigation_Position = 2
)

// Enum value maps for Navigation_Position.
var (
	Navigation_Position_name = map[int32]string{
		0: "HIDDEN",
		1: "SIDEBAR",
		2: "TOP",
	}
	Navigation_Position_value = map[string]int32{
		"HIDDEN":  0,
		"SIDEBAR": 1,
		"TOP":     2,
	}
)

func (x Navigation_Position) Enum() *Navigation_Position {
	p := new(Navigation_Position)
	*p = x
	return p
}

func (x Navigation_Position) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Navigation_Position) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Navigation_proto_enumTypes[0].Descriptor()
}

func (Navigation_Position) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Navigation_proto_enumTypes[0]
}

func (x Navigation_Position) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Navigation_Position.Descriptor instead.
func (Navigation_Position) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Navigation_proto_rawDescGZIP(), []int{0, 0}
}

type Navigation struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sections []string               `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	AppPages []*AppPage             `protobuf:"bytes,2,rep,name=app_pages,json=appPages,proto3" json:"app_pages,omitempty"`
	Position Navigation_Position    `protobuf:"varint,3,opt,name=position,proto3,enum=Navigation_Position" json:"position,omitempty"`
	// The script hash for the page identified by st.navigation
	PageScriptHash string `protobuf:"bytes,4,opt,name=page_script_hash,json=pageScriptHash,proto3" json:"page_script_hash,omitempty"`
	Expanded       bool   `protobuf:"varint,5,opt,name=expanded,proto3" json:"expanded,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Navigation) Reset() {
	*x = Navigation{}
	mi := &file_streamlit_proto_Navigation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Navigation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Navigation) ProtoMessage() {}

func (x *Navigation) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Navigation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Navigation.ProtoReflect.Descriptor instead.
func (*Navigation) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Navigation_proto_rawDescGZIP(), []int{0}
}

func (x *Navigation) GetSections() []string {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *Navigation) GetAppPages() []*AppPage {
	if x != nil {
		return x.AppPages
	}
	return nil
}

func (x *Navigation) GetPosition() Navigation_Position {
	if x != nil {
		return x.Position
	}
	return Navigation_HIDDEN
}

func (x *Navigation) GetPageScriptHash() string {
	if x != nil {
		return x.PageScriptHash
	}
	return ""
}

func (x *Navigation) GetExpanded() bool {
	if x != nil {
		return x.Expanded
	}
	return false
}

var File_streamlit_proto_Navigation_proto protoreflect.FileDescriptor

const file_streamlit_proto_Navigation_proto_rawDesc = "" +
	"\n" +
	" streamlit/proto/Navigation.proto\x1a\x1dstreamlit/proto/AppPage.proto\"\xf5\x01\n" +
	"\n" +
	"Navigation\x12\x1a\n" +
	"\bsections\x18\x01 \x03(\tR\bsections\x12%\n" +
	"\tapp_pages\x18\x02 \x03(\v2\b.AppPageR\bappPages\x120\n" +
	"\bposition\x18\x03 \x01(\x0e2\x14.Navigation.PositionR\bposition\x12(\n" +
	"\x10page_script_hash\x18\x04 \x01(\tR\x0epageScriptHash\x12\x1a\n" +
	"\bexpanded\x18\x05 \x01(\bR\bexpanded\",\n" +
	"\bPosition\x12\n" +
	"\n" +
	"\x06HIDDEN\x10\x00\x12\v\n" +
	"\aSIDEBAR\x10\x01\x12\a\n" +
	"\x03TOP\x10\x02B1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Navigation_proto_rawDescOnce sync.Once
	file_streamlit_proto_Navigation_proto_rawDescData []byte
)

func file_streamlit_proto_Navigation_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Navigation_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Navigation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Navigation_proto_rawDesc), len(file_streamlit_proto_Navigation_proto_rawDesc)))
	})
	return file_streamlit_proto_Navigation_proto_rawDescData
}

var file_streamlit_proto_Navigation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_Navigation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Navigation_proto_goTypes = []any{
	(Navigation_Position)(0), // 0: Navigation.Position
	(*Navigation)(nil),       // 1: Navigation
	(*AppPage)(nil),          // 2: AppPage
}
var file_streamlit_proto_Navigation_proto_depIdxs = []int32{
	2, // 0: Navigation.app_pages:type_name -> AppPage
	0, // 1: Navigation.position:type_name -> Navigation.Position
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Navigation_proto_init() }
func file_streamlit_proto_Navigation_proto_init() {
	if File_streamlit_proto_Navigation_proto != nil {
		return
	}
	file_streamlit_proto_AppPage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Navigation_proto_rawDesc), len(file_streamlit_proto_Navigation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Navigation_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Navigation_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_Navigation_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_Navigation_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Navigation_proto = out.File
	file_streamlit_proto_Navigation_proto_goTypes = nil
	file_streamlit_proto_Navigation_proto_depIdxs = nil
}
