//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/NumberInput.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberInput_DataType int32

const (
	// Does the input operate on ints or floats? This doesn't change how the
	// data is stored, but the frontend needs to know for input parsing.
	NumberInput_INT   NumberInput_DataType = 0
	NumberInput_FLOAT NumberInput_DataType = 1
)

// Enum value maps for NumberInput_DataType.
var (
	NumberInput_DataType_name = map[int32]string{
		0: "INT",
		1: "FLOAT",
	}
	NumberInput_DataType_value = map[string]int32{
		"INT":   0,
		"FLOAT": 1,
	}
)

func (x NumberInput_DataType) Enum() *NumberInput_DataType {
	p := new(NumberInput_DataType)
	*p = x
	return p
}

func (x NumberInput_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NumberInput_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_NumberInput_proto_enumTypes[0].Descriptor()
}

func (NumberInput_DataType) Type() protoreflect.EnumType {
	return &file_streamlit_proto_NumberInput_proto_enumTypes[0]
}

func (x NumberInput_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NumberInput_DataType.Descriptor instead.
func (NumberInput_DataType) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_NumberInput_proto_rawDescGZIP(), []int{0, 0}
}

type NumberInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label           string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	FormId          string                 `protobuf:"bytes,3,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Format          string                 `protobuf:"bytes,8,opt,name=format,proto3" json:"format,omitempty"`
	HasMin          bool                   `protobuf:"varint,11,opt,name=has_min,json=hasMin,proto3" json:"has_min,omitempty"`
	HasMax          bool                   `protobuf:"varint,12,opt,name=has_max,json=hasMax,proto3" json:"has_max,omitempty"`
	DataType        NumberInput_DataType   `protobuf:"varint,13,opt,name=data_type,json=dataType,proto3,enum=NumberInput_DataType" json:"data_type,omitempty"`
	Default         *float64               `protobuf:"fixed64,14,opt,name=default,proto3,oneof" json:"default,omitempty"`
	Step            float64                `protobuf:"fixed64,15,opt,name=step,proto3" json:"step,omitempty"`
	Min             float64                `protobuf:"fixed64,16,opt,name=min,proto3" json:"min,omitempty"`
	Max             float64                `protobuf:"fixed64,17,opt,name=max,proto3" json:"max,omitempty"`
	Help            string                 `protobuf:"bytes,18,opt,name=help,proto3" json:"help,omitempty"`
	Value           *float64               `protobuf:"fixed64,19,opt,name=value,proto3,oneof" json:"value,omitempty"`
	SetValue        bool                   `protobuf:"varint,20,opt,name=set_value,json=setValue,proto3" json:"set_value,omitempty"`
	Disabled        bool                   `protobuf:"varint,21,opt,name=disabled,proto3" json:"disabled,omitempty"`
	LabelVisibility *LabelVisibility       `protobuf:"bytes,22,opt,name=label_visibility,json=labelVisibility,proto3" json:"label_visibility,omitempty"`
	Placeholder     string                 `protobuf:"bytes,23,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Icon            string                 `protobuf:"bytes,24,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NumberInput) Reset() {
	*x = NumberInput{}
	mi := &file_streamlit_proto_NumberInput_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberInput) ProtoMessage() {}

func (x *NumberInput) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_NumberInput_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberInput.ProtoReflect.Descriptor instead.
func (*NumberInput) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_NumberInput_proto_rawDescGZIP(), []int{0}
}

func (x *NumberInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NumberInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *NumberInput) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *NumberInput) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *NumberInput) GetHasMin() bool {
	if x != nil {
		return x.HasMin
	}
	return false
}

func (x *NumberInput) GetHasMax() bool {
	if x != nil {
		return x.HasMax
	}
	return false
}

func (x *NumberInput) GetDataType() NumberInput_DataType {
	if x != nil {
		return x.DataType
	}
	return NumberInput_INT
}

func (x *NumberInput) GetDefault() float64 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *NumberInput) GetStep() float64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *NumberInput) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *NumberInput) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *NumberInput) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *NumberInput) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *NumberInput) GetSetValue() bool {
	if x != nil {
		return x.SetValue
	}
	return false
}

func (x *NumberInput) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *NumberInput) GetLabelVisibility() *LabelVisibility {
	if x != nil {
		return x.LabelVisibility
	}
	return nil
}

func (x *NumberInput) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *NumberInput) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

var File_streamlit_proto_NumberInput_proto protoreflect.FileDescriptor

const file_streamlit_proto_NumberInput_proto_rawDesc = "" +
	"\n" +
	"!streamlit/proto/NumberInput.proto\x1a%streamlit/proto/LabelVisibility.proto\"\xd6\x04\n" +
	"\vNumberInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x17\n" +
	"\aform_id\x18\x03 \x01(\tR\x06formId\x12\x16\n" +
	"\x06format\x18\b \x01(\tR\x06format\x12\x17\n" +
	"\ahas_min\x18\v \x01(\bR\x06hasMin\x12\x17\n" +
	"\ahas_max\x18\f \x01(\bR\x06hasMax\x122\n" +
	"\tdata_type\x18\r \x01(\x0e2\x15.NumberInput.DataTypeR\bdataType\x12\x1d\n" +
	"\adefault\x18\x0e \x01(\x01H\x00R\adefault\x88\x01\x01\x12\x12\n" +
	"\x04step\x18\x0f \x01(\x01R\x04step\x12\x10\n" +
	"\x03min\x18\x10 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x11 \x01(\x01R\x03max\x12\x12\n" +
	"\x04help\x18\x12 \x01(\tR\x04help\x12\x19\n" +
	"\x05value\x18\x13 \x01(\x01H\x01R\x05value\x88\x01\x01\x12\x1b\n" +
	"\tset_value\x18\x14 \x01(\bR\bsetValue\x12\x1a\n" +
	"\bdisabled\x18\x15 \x01(\bR\bdisabled\x12;\n" +
	"\x10label_visibility\x18\x16 \x01(\v2\x10.LabelVisibilityR\x0flabelVisibility\x12 \n" +
	"\vplaceholder\x18\x17 \x01(\tR\vplaceholder\x12\x12\n" +
	"\x04icon\x18\x18 \x01(\tR\x04icon\"\x1e\n" +
	"\bDataType\x12\a\n" +
	"\x03INT\x10\x00\x12\t\n" +
	"\x05FLOAT\x10\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_valueJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\vB3Z1github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_NumberInput_proto_rawDescOnce sync.Once
	file_streamlit_proto_NumberInput_proto_rawDescData []byte
)

func file_streamlit_proto_NumberInput_proto_rawDescGZIP() []byte {
	file_streamlit_proto_NumberInput_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_NumberInput_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_NumberInput_proto_rawDesc), len(file_streamlit_proto_NumberInput_proto_rawDesc)))
	})
	return file_streamlit_proto_NumberInput_proto_rawDescData
}

var file_streamlit_proto_NumberInput_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_NumberInput_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_NumberInput_proto_goTypes = []any{
	(NumberInput_DataType)(0), // 0: NumberInput.DataType
	(*NumberInput)(nil),       // 1: NumberInput
	(*LabelVisibility)(nil),   // 2: LabelVisibility
}
var file_streamlit_proto_NumberInput_proto_depIdxs = []int32{
	0, // 0: NumberInput.data_type:type_name -> NumberInput.DataType
	2, // 1: NumberInput.label_visibility:type_name -> LabelVisibility
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_streamlit_proto_NumberInput_proto_init() }
func file_streamlit_proto_NumberInput_proto_init() {
	if File_streamlit_proto_NumberInput_proto != nil {
		return
	}
	file_streamlit_proto_LabelVisibility_proto_init()
	file_streamlit_proto_NumberInput_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_NumberInput_proto_rawDesc), len(file_streamlit_proto_NumberInput_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_NumberInput_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_NumberInput_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_NumberInput_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_NumberInput_proto_msgTypes,
	}.Build()
	File_streamlit_proto_NumberInput_proto = out.File
	file_streamlit_proto_NumberInput_proto_goTypes = nil
	file_streamlit_proto_NumberInput_proto_depIdxs = nil
}
