//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/PageLink.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageLink struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Page              string                 `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Label             string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Icon              string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	PageScriptHash    string                 `protobuf:"bytes,4,opt,name=page_script_hash,json=pageScriptHash,proto3" json:"page_script_hash,omitempty"`
	Help              string                 `protobuf:"bytes,5,opt,name=help,proto3" json:"help,omitempty"`
	UseContainerWidth *bool                  `protobuf:"varint,6,opt,name=use_container_width,json=useContainerWidth,proto3,oneof" json:"use_container_width,omitempty"`
	Disabled          bool                   `protobuf:"varint,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	External          bool                   `protobuf:"varint,8,opt,name=external,proto3" json:"external,omitempty"`
	QueryString       string                 `protobuf:"bytes,9,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`
	IconPosition      ButtonLikeIconPosition `protobuf:"varint,10,opt,name=icon_position,json=iconPosition,proto3,enum=streamlit.ButtonLikeIconPosition" json:"icon_position,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PageLink) Reset() {
	*x = PageLink{}
	mi := &file_streamlit_proto_PageLink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageLink) ProtoMessage() {}

func (x *PageLink) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_PageLink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageLink.ProtoReflect.Descriptor instead.
func (*PageLink) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_PageLink_proto_rawDescGZIP(), []int{0}
}

func (x *PageLink) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *PageLink) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PageLink) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PageLink) GetPageScriptHash() string {
	if x != nil {
		return x.PageScriptHash
	}
	return ""
}

func (x *PageLink) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *PageLink) GetUseContainerWidth() bool {
	if x != nil && x.UseContainerWidth != nil {
		return *x.UseContainerWidth
	}
	return false
}

func (x *PageLink) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *PageLink) GetExternal() bool {
	if x != nil {
		return x.External
	}
	return false
}

func (x *PageLink) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

func (x *PageLink) GetIconPosition() ButtonLikeIconPosition {
	if x != nil {
		return x.IconPosition
	}
	return ButtonLikeIconPosition_LEFT
}

var File_streamlit_proto_PageLink_proto protoreflect.FileDescriptor

const file_streamlit_proto_PageLink_proto_rawDesc = "" +
	"\n" +
	"\x1estreamlit/proto/PageLink.proto\x1a,streamlit/proto/ButtonLikeIconPosition.proto\"\xf6\x02\n" +
	"\bPageLink\x12\x12\n" +
	"\x04page\x18\x01 \x01(\tR\x04page\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12(\n" +
	"\x10page_script_hash\x18\x04 \x01(\tR\x0epageScriptHash\x12\x12\n" +
	"\x04help\x18\x05 \x01(\tR\x04help\x123\n" +
	"\x13use_container_width\x18\x06 \x01(\bH\x00R\x11useContainerWidth\x88\x01\x01\x12\x1a\n" +
	"\bdisabled\x18\a \x01(\bR\bdisabled\x12\x1a\n" +
	"\bexternal\x18\b \x01(\bR\bexternal\x12!\n" +
	"\fquery_string\x18\t \x01(\tR\vqueryString\x12F\n" +
	"\ricon_position\x18\n" +
	" \x01(\x0e2!.streamlit.ButtonLikeIconPositionR\ficonPositionB\x16\n" +
	"\x14_use_container_widthB1Z/github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_PageLink_proto_rawDescOnce sync.Once
	file_streamlit_proto_PageLink_proto_rawDescData []byte
)

func file_streamlit_proto_PageLink_proto_rawDescGZIP() []byte {
	file_streamlit_proto_PageLink_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_PageLink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_PageLink_proto_rawDesc), len(file_streamlit_proto_PageLink_proto_rawDesc)))
	})
	return file_streamlit_proto_PageLink_proto_rawDescData
}

var file_streamlit_proto_PageLink_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_PageLink_proto_goTypes = []any{
	(*PageLink)(nil),            // 0: PageLink
	(ButtonLikeIconPosition)(0), // 1: streamlit.ButtonLikeIconPosition
}
var file_streamlit_proto_PageLink_proto_depIdxs = []int32{
	1, // 0: PageLink.icon_position:type_name -> streamlit.ButtonLikeIconPosition
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_PageLink_proto_init() }
func file_streamlit_proto_PageLink_proto_init() {
	if File_streamlit_proto_PageLink_proto != nil {
		return
	}
	file_streamlit_proto_ButtonLikeIconPosition_proto_init()
	file_streamlit_proto_PageLink_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_PageLink_proto_rawDesc), len(file_streamlit_proto_PageLink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_PageLink_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_PageLink_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_PageLink_proto_msgTypes,
	}.Build()
	File_streamlit_proto_PageLink_proto = out.File
	file_streamlit_proto_PageLink_proto_goTypes = nil
	file_streamlit_proto_PageLink_proto_depIdxs = nil
}
