//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/PlotlyChart.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Available selection modes:
type PlotlyChart_SelectionMode int32

const (
	PlotlyChart_POINTS PlotlyChart_SelectionMode = 0 // Point selection mode
	PlotlyChart_BOX    PlotlyChart_SelectionMode = 1 // Box selection mode
	PlotlyChart_LASSO  PlotlyChart_SelectionMode = 2 // Lasso selection mode
)

// Enum value maps for PlotlyChart_SelectionMode.
var (
	PlotlyChart_SelectionMode_name = map[int32]string{
		0: "POINTS",
		1: "BOX",
		2: "LASSO",
	}
	PlotlyChart_SelectionMode_value = map[string]int32{
		"POINTS": 0,
		"BOX":    1,
		"LASSO":  2,
	}
)

func (x PlotlyChart_SelectionMode) Enum() *PlotlyChart_SelectionMode {
	p := new(PlotlyChart_SelectionMode)
	*p = x
	return p
}

func (x PlotlyChart_SelectionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlotlyChart_SelectionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_PlotlyChart_proto_enumTypes[0].Descriptor()
}

func (PlotlyChart_SelectionMode) Type() protoreflect.EnumType {
	return &file_streamlit_proto_PlotlyChart_proto_enumTypes[0]
}

func (x PlotlyChart_SelectionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlotlyChart_SelectionMode.Descriptor instead.
func (PlotlyChart_SelectionMode) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_PlotlyChart_proto_rawDescGZIP(), []int{0, 0}
}

type PlotlyChart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// override the properties with a theme. Currently, only "streamlit" or None are accepted.
	Theme string `protobuf:"bytes,6,opt,name=theme,proto3" json:"theme,omitempty"`
	// The unique element ID of this chart.
	Id string `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	// Activate selections types on the chart.
	SelectionMode []PlotlyChart_SelectionMode `protobuf:"varint,8,rep,packed,name=selection_mode,json=selectionMode,proto3,enum=PlotlyChart_SelectionMode" json:"selection_mode,omitempty"`
	// Form ID, filled if selections are activated.
	FormId string `protobuf:"bytes,9,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	// JSON-serialized dict containing keys from the set {data, frames, layout}.
	Spec string `protobuf:"bytes,10,opt,name=spec,proto3" json:"spec,omitempty"`
	// JSON-serialized dict with Plotly's config object.
	Config        string `protobuf:"bytes,11,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlotlyChart) Reset() {
	*x = PlotlyChart{}
	mi := &file_streamlit_proto_PlotlyChart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotlyChart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotlyChart) ProtoMessage() {}

func (x *PlotlyChart) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_PlotlyChart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlotlyChart.ProtoReflect.Descriptor instead.
func (*PlotlyChart) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_PlotlyChart_proto_rawDescGZIP(), []int{0}
}

func (x *PlotlyChart) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *PlotlyChart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlotlyChart) GetSelectionMode() []PlotlyChart_SelectionMode {
	if x != nil {
		return x.SelectionMode
	}
	return nil
}

func (x *PlotlyChart) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *PlotlyChart) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *PlotlyChart) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

var File_streamlit_proto_PlotlyChart_proto protoreflect.FileDescriptor

const file_streamlit_proto_PlotlyChart_proto_rawDesc = "" +
	"\n" +
	"!streamlit/proto/PlotlyChart.proto\"\x8a\x02\n" +
	"\vPlotlyChart\x12\x14\n" +
	"\x05theme\x18\x06 \x01(\tR\x05theme\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12A\n" +
	"\x0eselection_mode\x18\b \x03(\x0e2\x1a.PlotlyChart.SelectionModeR\rselectionMode\x12\x17\n" +
	"\aform_id\x18\t \x01(\tR\x06formId\x12\x12\n" +
	"\x04spec\x18\n" +
	" \x01(\tR\x04spec\x12\x16\n" +
	"\x06config\x18\v \x01(\tR\x06config\"/\n" +
	"\rSelectionMode\x12\n" +
	"\n" +
	"\x06POINTS\x10\x00\x12\a\n" +
	"\x03BOX\x10\x01\x12\t\n" +
	"\x05LASSO\x10\x02J\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06B1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_PlotlyChart_proto_rawDescOnce sync.Once
	file_streamlit_proto_PlotlyChart_proto_rawDescData []byte
)

func file_streamlit_proto_PlotlyChart_proto_rawDescGZIP() []byte {
	file_streamlit_proto_PlotlyChart_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_PlotlyChart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_PlotlyChart_proto_rawDesc), len(file_streamlit_proto_PlotlyChart_proto_rawDesc)))
	})
	return file_streamlit_proto_PlotlyChart_proto_rawDescData
}

var file_streamlit_proto_PlotlyChart_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_PlotlyChart_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_PlotlyChart_proto_goTypes = []any{
	(PlotlyChart_SelectionMode)(0), // 0: PlotlyChart.SelectionMode
	(*PlotlyChart)(nil),            // 1: PlotlyChart
}
var file_streamlit_proto_PlotlyChart_proto_depIdxs = []int32{
	0, // 0: PlotlyChart.selection_mode:type_name -> PlotlyChart.SelectionMode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_PlotlyChart_proto_init() }
func file_streamlit_proto_PlotlyChart_proto_init() {
	if File_streamlit_proto_PlotlyChart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_PlotlyChart_proto_rawDesc), len(file_streamlit_proto_PlotlyChart_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_PlotlyChart_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_PlotlyChart_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_PlotlyChart_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_PlotlyChart_proto_msgTypes,
	}.Build()
	File_streamlit_proto_PlotlyChart_proto = out.File
	file_streamlit_proto_PlotlyChart_proto_goTypes = nil
	file_streamlit_proto_PlotlyChart_proto_depIdxs = nil
}
