//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Selectbox.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Selectbox struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label            string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Default          *int32                 `protobuf:"varint,3,opt,name=default,proto3,oneof" json:"default,omitempty"`
	Options          []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	Help             string                 `protobuf:"bytes,5,opt,name=help,proto3" json:"help,omitempty"`
	FormId           string                 `protobuf:"bytes,6,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	RawValue         *string                `protobuf:"bytes,13,opt,name=raw_value,json=rawValue,proto3,oneof" json:"raw_value,omitempty"`
	SetValue         bool                   `protobuf:"varint,8,opt,name=set_value,json=setValue,proto3" json:"set_value,omitempty"`
	Disabled         bool                   `protobuf:"varint,9,opt,name=disabled,proto3" json:"disabled,omitempty"`
	LabelVisibility  *LabelVisibility       `protobuf:"bytes,10,opt,name=label_visibility,json=labelVisibility,proto3" json:"label_visibility,omitempty"`
	Placeholder      string                 `protobuf:"bytes,11,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	AcceptNewOptions *bool                  `protobuf:"varint,12,opt,name=accept_new_options,json=acceptNewOptions,proto3,oneof" json:"accept_new_options,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Selectbox) Reset() {
	*x = Selectbox{}
	mi := &file_streamlit_proto_Selectbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selectbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selectbox) ProtoMessage() {}

func (x *Selectbox) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Selectbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selectbox.ProtoReflect.Descriptor instead.
func (*Selectbox) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Selectbox_proto_rawDescGZIP(), []int{0}
}

func (x *Selectbox) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Selectbox) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Selectbox) GetDefault() int32 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Selectbox) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Selectbox) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *Selectbox) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *Selectbox) GetRawValue() string {
	if x != nil && x.RawValue != nil {
		return *x.RawValue
	}
	return ""
}

func (x *Selectbox) GetSetValue() bool {
	if x != nil {
		return x.SetValue
	}
	return false
}

func (x *Selectbox) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Selectbox) GetLabelVisibility() *LabelVisibility {
	if x != nil {
		return x.LabelVisibility
	}
	return nil
}

func (x *Selectbox) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *Selectbox) GetAcceptNewOptions() bool {
	if x != nil && x.AcceptNewOptions != nil {
		return *x.AcceptNewOptions
	}
	return false
}

var File_streamlit_proto_Selectbox_proto protoreflect.FileDescriptor

const file_streamlit_proto_Selectbox_proto_rawDesc = "" +
	"\n" +
	"\x1fstreamlit/proto/Selectbox.proto\x1a%streamlit/proto/LabelVisibility.proto\"\xbb\x03\n" +
	"\tSelectbox\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1d\n" +
	"\adefault\x18\x03 \x01(\x05H\x00R\adefault\x88\x01\x01\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12\x12\n" +
	"\x04help\x18\x05 \x01(\tR\x04help\x12\x17\n" +
	"\aform_id\x18\x06 \x01(\tR\x06formId\x12 \n" +
	"\traw_value\x18\r \x01(\tH\x01R\brawValue\x88\x01\x01\x12\x1b\n" +
	"\tset_value\x18\b \x01(\bR\bsetValue\x12\x1a\n" +
	"\bdisabled\x18\t \x01(\bR\bdisabled\x12;\n" +
	"\x10label_visibility\x18\n" +
	" \x01(\v2\x10.LabelVisibilityR\x0flabelVisibility\x12 \n" +
	"\vplaceholder\x18\v \x01(\tR\vplaceholder\x121\n" +
	"\x12accept_new_options\x18\f \x01(\bH\x02R\x10acceptNewOptions\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\f\n" +
	"\n" +
	"_raw_valueB\x15\n" +
	"\x13_accept_new_optionsJ\x04\b\a\x10\bB1Z/github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Selectbox_proto_rawDescOnce sync.Once
	file_streamlit_proto_Selectbox_proto_rawDescData []byte
)

func file_streamlit_proto_Selectbox_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Selectbox_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Selectbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Selectbox_proto_rawDesc), len(file_streamlit_proto_Selectbox_proto_rawDesc)))
	})
	return file_streamlit_proto_Selectbox_proto_rawDescData
}

var file_streamlit_proto_Selectbox_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Selectbox_proto_goTypes = []any{
	(*Selectbox)(nil),       // 0: Selectbox
	(*LabelVisibility)(nil), // 1: LabelVisibility
}
var file_streamlit_proto_Selectbox_proto_depIdxs = []int32{
	1, // 0: Selectbox.label_visibility:type_name -> LabelVisibility
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Selectbox_proto_init() }
func file_streamlit_proto_Selectbox_proto_init() {
	if File_streamlit_proto_Selectbox_proto != nil {
		return
	}
	file_streamlit_proto_LabelVisibility_proto_init()
	file_streamlit_proto_Selectbox_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Selectbox_proto_rawDesc), len(file_streamlit_proto_Selectbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Selectbox_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Selectbox_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_Selectbox_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Selectbox_proto = out.File
	file_streamlit_proto_Selectbox_proto_goTypes = nil
	file_streamlit_proto_Selectbox_proto_depIdxs = nil
}
