//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/SessionStatus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status for a session. Sent as part of the Initialize message, and also
// on AppSession status change events.
//
// NOTE: This proto type is used by some external services so needs to remain
// relatively stable. While it isn't entirely set in stone, changing it
// may require a good amount of effort so should be avoided if possible.
type SessionStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, streamlit will re-run the script if it detects that the script
	// has been changed. This value comes from the server.runOnSave config.
	// The browser can change this option; it's sent here so that the browser
	// shows the correct initial value in its Settings dialog.
	RunOnSave bool `protobuf:"varint,1,opt,name=run_on_save,json=runOnSave,proto3" json:"run_on_save,omitempty"`
	// True if the script is being run by a client right now.
	ScriptIsRunning bool `protobuf:"varint,2,opt,name=script_is_running,json=scriptIsRunning,proto3" json:"script_is_running,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionStatus) Reset() {
	*x = SessionStatus{}
	mi := &file_streamlit_proto_SessionStatus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatus) ProtoMessage() {}

func (x *SessionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_SessionStatus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatus.ProtoReflect.Descriptor instead.
func (*SessionStatus) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_SessionStatus_proto_rawDescGZIP(), []int{0}
}

func (x *SessionStatus) GetRunOnSave() bool {
	if x != nil {
		return x.RunOnSave
	}
	return false
}

func (x *SessionStatus) GetScriptIsRunning() bool {
	if x != nil {
		return x.ScriptIsRunning
	}
	return false
}

var File_streamlit_proto_SessionStatus_proto protoreflect.FileDescriptor

const file_streamlit_proto_SessionStatus_proto_rawDesc = "" +
	"\n" +
	"#streamlit/proto/SessionStatus.proto\"[\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\vrun_on_save\x18\x01 \x01(\bR\trunOnSave\x12*\n" +
	"\x11script_is_running\x18\x02 \x01(\bR\x0fscriptIsRunningB1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_SessionStatus_proto_rawDescOnce sync.Once
	file_streamlit_proto_SessionStatus_proto_rawDescData []byte
)

func file_streamlit_proto_SessionStatus_proto_rawDescGZIP() []byte {
	file_streamlit_proto_SessionStatus_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_SessionStatus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_SessionStatus_proto_rawDesc), len(file_streamlit_proto_SessionStatus_proto_rawDesc)))
	})
	return file_streamlit_proto_SessionStatus_proto_rawDescData
}

var file_streamlit_proto_SessionStatus_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_SessionStatus_proto_goTypes = []any{
	(*SessionStatus)(nil), // 0: SessionStatus
}
var file_streamlit_proto_SessionStatus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streamlit_proto_SessionStatus_proto_init() }
func file_streamlit_proto_SessionStatus_proto_init() {
	if File_streamlit_proto_SessionStatus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_SessionStatus_proto_rawDesc), len(file_streamlit_proto_SessionStatus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_SessionStatus_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_SessionStatus_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_SessionStatus_proto_msgTypes,
	}.Build()
	File_streamlit_proto_SessionStatus_proto = out.File
	file_streamlit_proto_SessionStatus_proto_goTypes = nil
	file_streamlit_proto_SessionStatus_proto_depIdxs = nil
}
