//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/SessionEvent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A transient event sent to all browsers connected to an associated app.
type SessionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*SessionEvent_ScriptChangedOnDisk
	//	*SessionEvent_ScriptWasManuallyStopped
	//	*SessionEvent_ScriptCompilationException
	Type          isSessionEvent_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_streamlit_proto_SessionEvent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_SessionEvent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_SessionEvent_proto_rawDescGZIP(), []int{0}
}

func (x *SessionEvent) GetType() isSessionEvent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *SessionEvent) GetScriptChangedOnDisk() bool {
	if x != nil {
		if x, ok := x.Type.(*SessionEvent_ScriptChangedOnDisk); ok {
			return x.ScriptChangedOnDisk
		}
	}
	return false
}

func (x *SessionEvent) GetScriptWasManuallyStopped() bool {
	if x != nil {
		if x, ok := x.Type.(*SessionEvent_ScriptWasManuallyStopped); ok {
			return x.ScriptWasManuallyStopped
		}
	}
	return false
}

func (x *SessionEvent) GetScriptCompilationException() *Exception {
	if x != nil {
		if x, ok := x.Type.(*SessionEvent_ScriptCompilationException); ok {
			return x.ScriptCompilationException
		}
	}
	return nil
}

type isSessionEvent_Type interface {
	isSessionEvent_Type()
}

type SessionEvent_ScriptChangedOnDisk struct {
	// The app's script changed on disk, but is *not* being re-run
	// automatically. The browser should prompt the user to re-run.
	ScriptChangedOnDisk bool `protobuf:"varint,1,opt,name=script_changed_on_disk,json=scriptChangedOnDisk,proto3,oneof"`
}

type SessionEvent_ScriptWasManuallyStopped struct {
	// The app's script was running, but it was manually stopped before
	// completion.
	ScriptWasManuallyStopped bool `protobuf:"varint,2,opt,name=script_was_manually_stopped,json=scriptWasManuallyStopped,proto3,oneof"`
}

type SessionEvent_ScriptCompilationException struct {
	// Script compilation failed with an exception.
	// We can't start running the script.
	ScriptCompilationException *Exception `protobuf:"bytes,3,opt,name=script_compilation_exception,json=scriptCompilationException,proto3,oneof"`
}

func (*SessionEvent_ScriptChangedOnDisk) isSessionEvent_Type() {}

func (*SessionEvent_ScriptWasManuallyStopped) isSessionEvent_Type() {}

func (*SessionEvent_ScriptCompilationException) isSessionEvent_Type() {}

var File_streamlit_proto_SessionEvent_proto protoreflect.FileDescriptor

const file_streamlit_proto_SessionEvent_proto_rawDesc = "" +
	"\n" +
	"\"streamlit/proto/SessionEvent.proto\x1a\x1fstreamlit/proto/Exception.proto\"\xde\x01\n" +
	"\fSessionEvent\x125\n" +
	"\x16script_changed_on_disk\x18\x01 \x01(\bH\x00R\x13scriptChangedOnDisk\x12?\n" +
	"\x1bscript_was_manually_stopped\x18\x02 \x01(\bH\x00R\x18scriptWasManuallyStopped\x12N\n" +
	"\x1cscript_compilation_exception\x18\x03 \x01(\v2\n" +
	".ExceptionH\x00R\x1ascriptCompilationExceptionB\x06\n" +
	"\x04typeB1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_SessionEvent_proto_rawDescOnce sync.Once
	file_streamlit_proto_SessionEvent_proto_rawDescData []byte
)

func file_streamlit_proto_SessionEvent_proto_rawDescGZIP() []byte {
	file_streamlit_proto_SessionEvent_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_SessionEvent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_SessionEvent_proto_rawDesc), len(file_streamlit_proto_SessionEvent_proto_rawDesc)))
	})
	return file_streamlit_proto_SessionEvent_proto_rawDescData
}

var file_streamlit_proto_SessionEvent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_SessionEvent_proto_goTypes = []any{
	(*SessionEvent)(nil), // 0: SessionEvent
	(*Exception)(nil),    // 1: Exception
}
var file_streamlit_proto_SessionEvent_proto_depIdxs = []int32{
	1, // 0: SessionEvent.script_compilation_exception:type_name -> Exception
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_SessionEvent_proto_init() }
func file_streamlit_proto_SessionEvent_proto_init() {
	if File_streamlit_proto_SessionEvent_proto != nil {
		return
	}
	file_streamlit_proto_Exception_proto_init()
	file_streamlit_proto_SessionEvent_proto_msgTypes[0].OneofWrappers = []any{
		(*SessionEvent_ScriptChangedOnDisk)(nil),
		(*SessionEvent_ScriptWasManuallyStopped)(nil),
		(*SessionEvent_ScriptCompilationException)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_SessionEvent_proto_rawDesc), len(file_streamlit_proto_SessionEvent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_SessionEvent_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_SessionEvent_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_SessionEvent_proto_msgTypes,
	}.Build()
	File_streamlit_proto_SessionEvent_proto = out.File
	file_streamlit_proto_SessionEvent_proto_goTypes = nil
	file_streamlit_proto_SessionEvent_proto_depIdxs = nil
}
