//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Skeleton.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Skeleton_SkeletonStyle int32

const (
	Skeleton_ELEMENT Skeleton_SkeletonStyle = 0
	Skeleton_APP     Skeleton_SkeletonStyle = 1 // internal-only, for now
)

// Enum value maps for Skeleton_SkeletonStyle.
var (
	Skeleton_SkeletonStyle_name = map[int32]string{
		0: "ELEMENT",
		1: "APP",
	}
	Skeleton_SkeletonStyle_value = map[string]int32{
		"ELEMENT": 0,
		"APP":     1,
	}
)

func (x Skeleton_SkeletonStyle) Enum() *Skeleton_SkeletonStyle {
	p := new(Skeleton_SkeletonStyle)
	*p = x
	return p
}

func (x Skeleton_SkeletonStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Skeleton_SkeletonStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Skeleton_proto_enumTypes[0].Descriptor()
}

func (Skeleton_SkeletonStyle) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Skeleton_proto_enumTypes[0]
}

func (x Skeleton_SkeletonStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Skeleton_SkeletonStyle.Descriptor instead.
func (Skeleton_SkeletonStyle) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Skeleton_proto_rawDescGZIP(), []int{0, 0}
}

// An empty-like element that displays an app skeleton.
type Skeleton struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Skeleton visual style
	Style Skeleton_SkeletonStyle `protobuf:"varint,1,opt,name=style,proto3,enum=Skeleton_SkeletonStyle" json:"style,omitempty"`
	// Height in pixels
	Height        *int32 `protobuf:"varint,2,opt,name=height,proto3,oneof" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skeleton) Reset() {
	*x = Skeleton{}
	mi := &file_streamlit_proto_Skeleton_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skeleton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skeleton) ProtoMessage() {}

func (x *Skeleton) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Skeleton_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skeleton.ProtoReflect.Descriptor instead.
func (*Skeleton) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Skeleton_proto_rawDescGZIP(), []int{0}
}

func (x *Skeleton) GetStyle() Skeleton_SkeletonStyle {
	if x != nil {
		return x.Style
	}
	return Skeleton_ELEMENT
}

func (x *Skeleton) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

var File_streamlit_proto_Skeleton_proto protoreflect.FileDescriptor

const file_streamlit_proto_Skeleton_proto_rawDesc = "" +
	"\n" +
	"\x1estreamlit/proto/Skeleton.proto\"\x88\x01\n" +
	"\bSkeleton\x12-\n" +
	"\x05style\x18\x01 \x01(\x0e2\x17.Skeleton.SkeletonStyleR\x05style\x12\x1b\n" +
	"\x06height\x18\x02 \x01(\x05H\x00R\x06height\x88\x01\x01\"%\n" +
	"\rSkeletonStyle\x12\v\n" +
	"\aELEMENT\x10\x00\x12\a\n" +
	"\x03APP\x10\x01B\t\n" +
	"\a_heightB1Z/github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Skeleton_proto_rawDescOnce sync.Once
	file_streamlit_proto_Skeleton_proto_rawDescData []byte
)

func file_streamlit_proto_Skeleton_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Skeleton_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Skeleton_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Skeleton_proto_rawDesc), len(file_streamlit_proto_Skeleton_proto_rawDesc)))
	})
	return file_streamlit_proto_Skeleton_proto_rawDescData
}

var file_streamlit_proto_Skeleton_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_Skeleton_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Skeleton_proto_goTypes = []any{
	(Skeleton_SkeletonStyle)(0), // 0: Skeleton.SkeletonStyle
	(*Skeleton)(nil),            // 1: Skeleton
}
var file_streamlit_proto_Skeleton_proto_depIdxs = []int32{
	0, // 0: Skeleton.style:type_name -> Skeleton.SkeletonStyle
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Skeleton_proto_init() }
func file_streamlit_proto_Skeleton_proto_init() {
	if File_streamlit_proto_Skeleton_proto != nil {
		return
	}
	file_streamlit_proto_Skeleton_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Skeleton_proto_rawDesc), len(file_streamlit_proto_Skeleton_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Skeleton_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Skeleton_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_Skeleton_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_Skeleton_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Skeleton_proto = out.File
	file_streamlit_proto_Skeleton_proto_goTypes = nil
	file_streamlit_proto_Skeleton_proto_depIdxs = nil
}
