//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Snow.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Show          bool                   `protobuf:"varint,1,opt,name=show,proto3" json:"show,omitempty"` // Dummy boolean because protos need to have something.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snow) Reset() {
	*x = Snow{}
	mi := &file_streamlit_proto_Snow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snow) ProtoMessage() {}

func (x *Snow) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Snow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snow.ProtoReflect.Descriptor instead.
func (*Snow) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Snow_proto_rawDescGZIP(), []int{0}
}

func (x *Snow) GetShow() bool {
	if x != nil {
		return x.Show
	}
	return false
}

var File_streamlit_proto_Snow_proto protoreflect.FileDescriptor

const file_streamlit_proto_Snow_proto_rawDesc = "" +
	"\n" +
	"\x1astreamlit/proto/Snow.proto\"\x1a\n" +
	"\x04Snow\x12\x12\n" +
	"\x04show\x18\x01 \x01(\bR\x04showB3Z1github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Snow_proto_rawDescOnce sync.Once
	file_streamlit_proto_Snow_proto_rawDescData []byte
)

func file_streamlit_proto_Snow_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Snow_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Snow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Snow_proto_rawDesc), len(file_streamlit_proto_Snow_proto_rawDesc)))
	})
	return file_streamlit_proto_Snow_proto_rawDescData
}

var file_streamlit_proto_Snow_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Snow_proto_goTypes = []any{
	(*Snow)(nil), // 0: Snow
}
var file_streamlit_proto_Snow_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Snow_proto_init() }
func file_streamlit_proto_Snow_proto_init() {
	if File_streamlit_proto_Snow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Snow_proto_rawDesc), len(file_streamlit_proto_Snow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Snow_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Snow_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_Snow_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Snow_proto = out.File
	file_streamlit_proto_Snow_proto_goTypes = nil
	file_streamlit_proto_Snow_proto_depIdxs = nil
}
