//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Table.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Available border modes:
type Table_BorderMode int32

const (
	Table_ALL        Table_BorderMode = 0 // Show borders around the table and between cells.
	Table_NONE       Table_BorderMode = 1 // Show no borders.
	Table_HORIZONTAL Table_BorderMode = 2 // Show only horizontal borders between rows.
)

// Enum value maps for Table_BorderMode.
var (
	Table_BorderMode_name = map[int32]string{
		0: "ALL",
		1: "NONE",
		2: "HORIZONTAL",
	}
	Table_BorderMode_value = map[string]int32{
		"ALL":        0,
		"NONE":       1,
		"HORIZONTAL": 2,
	}
)

func (x Table_BorderMode) Enum() *Table_BorderMode {
	p := new(Table_BorderMode)
	*p = x
	return p
}

func (x Table_BorderMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Table_BorderMode) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Table_proto_enumTypes[0].Descriptor()
}

func (Table_BorderMode) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Table_proto_enumTypes[0]
}

func (x Table_BorderMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Table_BorderMode.Descriptor instead.
func (Table_BorderMode) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Table_proto_rawDescGZIP(), []int{0, 0}
}

// Proto message for st.table element.
type Table struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Arrow data to display
	ArrowData *ArrowData `protobuf:"bytes,1,opt,name=arrow_data,json=arrowData,proto3" json:"arrow_data,omitempty"`
	// How to show borders around the table and between cells.
	BorderMode    Table_BorderMode `protobuf:"varint,2,opt,name=border_mode,json=borderMode,proto3,enum=Table_BorderMode" json:"border_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_streamlit_proto_Table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Table_proto_rawDescGZIP(), []int{0}
}

func (x *Table) GetArrowData() *ArrowData {
	if x != nil {
		return x.ArrowData
	}
	return nil
}

func (x *Table) GetBorderMode() Table_BorderMode {
	if x != nil {
		return x.BorderMode
	}
	return Table_ALL
}

var File_streamlit_proto_Table_proto protoreflect.FileDescriptor

const file_streamlit_proto_Table_proto_rawDesc = "" +
	"\n" +
	"\x1bstreamlit/proto/Table.proto\x1a\x1fstreamlit/proto/ArrowData.proto\"\x97\x01\n" +
	"\x05Table\x12)\n" +
	"\n" +
	"arrow_data\x18\x01 \x01(\v2\n" +
	".ArrowDataR\tarrowData\x122\n" +
	"\vborder_mode\x18\x02 \x01(\x0e2\x11.Table.BorderModeR\n" +
	"borderMode\"/\n" +
	"\n" +
	"BorderMode\x12\a\n" +
	"\x03ALL\x10\x00\x12\b\n" +
	"\x04NONE\x10\x01\x12\x0e\n" +
	"\n" +
	"HORIZONTAL\x10\x02B1Z/github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Table_proto_rawDescOnce sync.Once
	file_streamlit_proto_Table_proto_rawDescData []byte
)

func file_streamlit_proto_Table_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Table_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Table_proto_rawDesc), len(file_streamlit_proto_Table_proto_rawDesc)))
	})
	return file_streamlit_proto_Table_proto_rawDescData
}

var file_streamlit_proto_Table_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_Table_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_Table_proto_goTypes = []any{
	(Table_BorderMode)(0), // 0: Table.BorderMode
	(*Table)(nil),         // 1: Table
	(*ArrowData)(nil),     // 2: ArrowData
}
var file_streamlit_proto_Table_proto_depIdxs = []int32{
	2, // 0: Table.arrow_data:type_name -> ArrowData
	0, // 1: Table.border_mode:type_name -> Table.BorderMode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Table_proto_init() }
func file_streamlit_proto_Table_proto_init() {
	if File_streamlit_proto_Table_proto != nil {
		return
	}
	file_streamlit_proto_ArrowData_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Table_proto_rawDesc), len(file_streamlit_proto_Table_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Table_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Table_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_Table_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_Table_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Table_proto = out.File
	file_streamlit_proto_Table_proto_goTypes = nil
	file_streamlit_proto_Table_proto_depIdxs = nil
}
