//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/TextAlignmentConfig.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextAlignmentConfig_Alignment int32

const (
	TextAlignmentConfig_UNSPECIFIED TextAlignmentConfig_Alignment = 0
	TextAlignmentConfig_LEFT        TextAlignmentConfig_Alignment = 1
	TextAlignmentConfig_CENTER      TextAlignmentConfig_Alignment = 2
	TextAlignmentConfig_RIGHT       TextAlignmentConfig_Alignment = 3
	TextAlignmentConfig_JUSTIFY     TextAlignmentConfig_Alignment = 4
)

// Enum value maps for TextAlignmentConfig_Alignment.
var (
	TextAlignmentConfig_Alignment_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "LEFT",
		2: "CENTER",
		3: "RIGHT",
		4: "JUSTIFY",
	}
	TextAlignmentConfig_Alignment_value = map[string]int32{
		"UNSPECIFIED": 0,
		"LEFT":        1,
		"CENTER":      2,
		"RIGHT":       3,
		"JUSTIFY":     4,
	}
)

func (x TextAlignmentConfig_Alignment) Enum() *TextAlignmentConfig_Alignment {
	p := new(TextAlignmentConfig_Alignment)
	*p = x
	return p
}

func (x TextAlignmentConfig_Alignment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextAlignmentConfig_Alignment) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_TextAlignmentConfig_proto_enumTypes[0].Descriptor()
}

func (TextAlignmentConfig_Alignment) Type() protoreflect.EnumType {
	return &file_streamlit_proto_TextAlignmentConfig_proto_enumTypes[0]
}

func (x TextAlignmentConfig_Alignment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextAlignmentConfig_Alignment.Descriptor instead.
func (TextAlignmentConfig_Alignment) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_TextAlignmentConfig_proto_rawDescGZIP(), []int{0, 0}
}

// Text alignment configuration for text elements
type TextAlignmentConfig struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Alignment     TextAlignmentConfig_Alignment `protobuf:"varint,1,opt,name=alignment,proto3,enum=streamlit.TextAlignmentConfig_Alignment" json:"alignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAlignmentConfig) Reset() {
	*x = TextAlignmentConfig{}
	mi := &file_streamlit_proto_TextAlignmentConfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAlignmentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAlignmentConfig) ProtoMessage() {}

func (x *TextAlignmentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_TextAlignmentConfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAlignmentConfig.ProtoReflect.Descriptor instead.
func (*TextAlignmentConfig) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_TextAlignmentConfig_proto_rawDescGZIP(), []int{0}
}

func (x *TextAlignmentConfig) GetAlignment() TextAlignmentConfig_Alignment {
	if x != nil {
		return x.Alignment
	}
	return TextAlignmentConfig_UNSPECIFIED
}

var File_streamlit_proto_TextAlignmentConfig_proto protoreflect.FileDescriptor

const file_streamlit_proto_TextAlignmentConfig_proto_rawDesc = "" +
	"\n" +
	")streamlit/proto/TextAlignmentConfig.proto\x12\tstreamlit\"\xa9\x01\n" +
	"\x13TextAlignmentConfig\x12F\n" +
	"\talignment\x18\x01 \x01(\x0e2(.streamlit.TextAlignmentConfig.AlignmentR\talignment\"J\n" +
	"\tAlignment\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\b\n" +
	"\x04LEFT\x10\x01\x12\n" +
	"\n" +
	"\x06CENTER\x10\x02\x12\t\n" +
	"\x05RIGHT\x10\x03\x12\v\n" +
	"\aJUSTIFY\x10\x04B1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_TextAlignmentConfig_proto_rawDescOnce sync.Once
	file_streamlit_proto_TextAlignmentConfig_proto_rawDescData []byte
)

func file_streamlit_proto_TextAlignmentConfig_proto_rawDescGZIP() []byte {
	file_streamlit_proto_TextAlignmentConfig_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_TextAlignmentConfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_TextAlignmentConfig_proto_rawDesc), len(file_streamlit_proto_TextAlignmentConfig_proto_rawDesc)))
	})
	return file_streamlit_proto_TextAlignmentConfig_proto_rawDescData
}

var file_streamlit_proto_TextAlignmentConfig_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_TextAlignmentConfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_TextAlignmentConfig_proto_goTypes = []any{
	(TextAlignmentConfig_Alignment)(0), // 0: streamlit.TextAlignmentConfig.Alignment
	(*TextAlignmentConfig)(nil),        // 1: streamlit.TextAlignmentConfig
}
var file_streamlit_proto_TextAlignmentConfig_proto_depIdxs = []int32{
	0, // 0: streamlit.TextAlignmentConfig.alignment:type_name -> streamlit.TextAlignmentConfig.Alignment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streamlit_proto_TextAlignmentConfig_proto_init() }
func file_streamlit_proto_TextAlignmentConfig_proto_init() {
	if File_streamlit_proto_TextAlignmentConfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_TextAlignmentConfig_proto_rawDesc), len(file_streamlit_proto_TextAlignmentConfig_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_TextAlignmentConfig_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_TextAlignmentConfig_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_TextAlignmentConfig_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_TextAlignmentConfig_proto_msgTypes,
	}.Build()
	File_streamlit_proto_TextAlignmentConfig_proto = out.File
	file_streamlit_proto_TextAlignmentConfig_proto_goTypes = nil
	file_streamlit_proto_TextAlignmentConfig_proto_depIdxs = nil
}
