//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/Video.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Video_Type int32

const (
	Video_UNUSED         Video_Type = 0 // This should always exist.
	Video_NATIVE         Video_Type = 1
	Video_YOUTUBE_IFRAME Video_Type = 2
)

// Enum value maps for Video_Type.
var (
	Video_Type_name = map[int32]string{
		0: "UNUSED",
		1: "NATIVE",
		2: "YOUTUBE_IFRAME",
	}
	Video_Type_value = map[string]int32{
		"UNUSED":         0,
		"NATIVE":         1,
		"YOUTUBE_IFRAME": 2,
	}
)

func (x Video_Type) Enum() *Video_Type {
	p := new(Video_Type)
	*p = x
	return p
}

func (x Video_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Video_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_streamlit_proto_Video_proto_enumTypes[0].Descriptor()
}

func (Video_Type) Type() protoreflect.EnumType {
	return &file_streamlit_proto_Video_proto_enumTypes[0]
}

func (x Video_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Video_Type.Descriptor instead.
func (Video_Type) EnumDescriptor() ([]byte, []int) {
	return file_streamlit_proto_Video_proto_rawDescGZIP(), []int{1, 0}
}

type SubtitleTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"` // Label for the subtitle e.g. "English" or "Spanish".
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtitleTrack) Reset() {
	*x = SubtitleTrack{}
	mi := &file_streamlit_proto_Video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtitleTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtitleTrack) ProtoMessage() {}

func (x *SubtitleTrack) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtitleTrack.ProtoReflect.Descriptor instead.
func (*SubtitleTrack) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Video_proto_rawDescGZIP(), []int{0}
}

func (x *SubtitleTrack) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SubtitleTrack) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Video struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A url pointing to a video file
	Url string `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	// The currentTime attribute of the HTML <video> tag's <source> subtag.
	StartTime int32 `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Type affects how browser wraps the video in tags: plain HTML5, YouTube...
	Type Video_Type `protobuf:"varint,5,opt,name=type,proto3,enum=Video_Type" json:"type,omitempty"`
	// Repeated field for subtitle tracks
	Subtitles []*SubtitleTrack `protobuf:"bytes,7,rep,name=subtitles,proto3" json:"subtitles,omitempty"`
	// The time at which the video should stop playing. If not specified, plays to the end.
	EndTime int32 `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Indicates whether the video should start over from the beginning once it ends.
	Loop          bool         `protobuf:"varint,9,opt,name=loop,proto3" json:"loop,omitempty"`
	Autoplay      bool         `protobuf:"varint,10,opt,name=autoplay,proto3" json:"autoplay,omitempty"`
	Muted         bool         `protobuf:"varint,11,opt,name=muted,proto3" json:"muted,omitempty"`
	Id            string       `protobuf:"bytes,12,opt,name=id,proto3" json:"id,omitempty"`
	WidthConfig   *WidthConfig `protobuf:"bytes,13,opt,name=width_config,json=widthConfig,proto3,oneof" json:"width_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_streamlit_proto_Video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_Video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_Video_proto_rawDescGZIP(), []int{1}
}

func (x *Video) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Video) GetStartTime() int32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Video) GetType() Video_Type {
	if x != nil {
		return x.Type
	}
	return Video_UNUSED
}

func (x *Video) GetSubtitles() []*SubtitleTrack {
	if x != nil {
		return x.Subtitles
	}
	return nil
}

func (x *Video) GetEndTime() int32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Video) GetLoop() bool {
	if x != nil {
		return x.Loop
	}
	return false
}

func (x *Video) GetAutoplay() bool {
	if x != nil {
		return x.Autoplay
	}
	return false
}

func (x *Video) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *Video) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Video) GetWidthConfig() *WidthConfig {
	if x != nil {
		return x.WidthConfig
	}
	return nil
}

var File_streamlit_proto_Video_proto protoreflect.FileDescriptor

const file_streamlit_proto_Video_proto_rawDesc = "" +
	"\n" +
	"\x1bstreamlit/proto/Video.proto\x1a!streamlit/proto/WidthConfig.proto\"7\n" +
	"\rSubtitleTrack\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x8f\x03\n" +
	"\x05Video\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x05R\tstartTime\x12\x1f\n" +
	"\x04type\x18\x05 \x01(\x0e2\v.Video.TypeR\x04type\x12,\n" +
	"\tsubtitles\x18\a \x03(\v2\x0e.SubtitleTrackR\tsubtitles\x12\x19\n" +
	"\bend_time\x18\b \x01(\x05R\aendTime\x12\x12\n" +
	"\x04loop\x18\t \x01(\bR\x04loop\x12\x1a\n" +
	"\bautoplay\x18\n" +
	" \x01(\bR\bautoplay\x12\x14\n" +
	"\x05muted\x18\v \x01(\bR\x05muted\x12\x0e\n" +
	"\x02id\x18\f \x01(\tR\x02id\x12>\n" +
	"\fwidth_config\x18\r \x01(\v2\x16.streamlit.WidthConfigH\x00R\vwidthConfig\x88\x01\x01\"2\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06UNUSED\x10\x00\x12\n" +
	"\n" +
	"\x06NATIVE\x10\x01\x12\x12\n" +
	"\x0eYOUTUBE_IFRAME\x10\x02B\x0f\n" +
	"\r_width_configJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x04\x10\x05B1Z/github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_Video_proto_rawDescOnce sync.Once
	file_streamlit_proto_Video_proto_rawDescData []byte
)

func file_streamlit_proto_Video_proto_rawDescGZIP() []byte {
	file_streamlit_proto_Video_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_Video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_Video_proto_rawDesc), len(file_streamlit_proto_Video_proto_rawDesc)))
	})
	return file_streamlit_proto_Video_proto_rawDescData
}

var file_streamlit_proto_Video_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamlit_proto_Video_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streamlit_proto_Video_proto_goTypes = []any{
	(Video_Type)(0),       // 0: Video.Type
	(*SubtitleTrack)(nil), // 1: SubtitleTrack
	(*Video)(nil),         // 2: Video
	(*WidthConfig)(nil),   // 3: streamlit.WidthConfig
}
var file_streamlit_proto_Video_proto_depIdxs = []int32{
	0, // 0: Video.type:type_name -> Video.Type
	1, // 1: Video.subtitles:type_name -> SubtitleTrack
	3, // 2: Video.width_config:type_name -> streamlit.WidthConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_streamlit_proto_Video_proto_init() }
func file_streamlit_proto_Video_proto_init() {
	if File_streamlit_proto_Video_proto != nil {
		return
	}
	file_streamlit_proto_WidthConfig_proto_init()
	file_streamlit_proto_Video_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_Video_proto_rawDesc), len(file_streamlit_proto_Video_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_Video_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_Video_proto_depIdxs,
		EnumInfos:         file_streamlit_proto_Video_proto_enumTypes,
		MessageInfos:      file_streamlit_proto_Video_proto_msgTypes,
	}.Build()
	File_streamlit_proto_Video_proto = out.File
	file_streamlit_proto_Video_proto_goTypes = nil
	file_streamlit_proto_Video_proto_depIdxs = nil
}
