//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/WidgetStates.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State for every widget in an app.
type WidgetStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Widgets       []*WidgetState         `protobuf:"bytes,1,rep,name=widgets,proto3" json:"widgets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetStates) Reset() {
	*x = WidgetStates{}
	mi := &file_streamlit_proto_WidgetStates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetStates) ProtoMessage() {}

func (x *WidgetStates) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_WidgetStates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetStates.ProtoReflect.Descriptor instead.
func (*WidgetStates) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_WidgetStates_proto_rawDescGZIP(), []int{0}
}

func (x *WidgetStates) GetWidgets() []*WidgetState {
	if x != nil {
		return x.Widgets
	}
	return nil
}

// State for a single widget.
type WidgetState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*WidgetState_TriggerValue
	//	*WidgetState_BoolValue
	//	*WidgetState_DoubleValue
	//	*WidgetState_IntValue
	//	*WidgetState_StringValue
	//	*WidgetState_DoubleArrayValue
	//	*WidgetState_IntArrayValue
	//	*WidgetState_StringArrayValue
	//	*WidgetState_JsonValue
	//	*WidgetState_ArrowValue
	//	*WidgetState_BytesValue
	//	*WidgetState_FileUploaderStateValue
	//	*WidgetState_StringTriggerValue
	//	*WidgetState_ChatInputValue
	//	*WidgetState_JsonTriggerValue
	Value         isWidgetState_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetState) Reset() {
	*x = WidgetState{}
	mi := &file_streamlit_proto_WidgetStates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetState) ProtoMessage() {}

func (x *WidgetState) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_WidgetStates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetState.ProtoReflect.Descriptor instead.
func (*WidgetState) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_WidgetStates_proto_rawDescGZIP(), []int{1}
}

func (x *WidgetState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WidgetState) GetValue() isWidgetState_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WidgetState) GetTriggerValue() bool {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_TriggerValue); ok {
			return x.TriggerValue
		}
	}
	return false
}

func (x *WidgetState) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *WidgetState) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *WidgetState) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *WidgetState) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *WidgetState) GetDoubleArrayValue() *DoubleArray {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_DoubleArrayValue); ok {
			return x.DoubleArrayValue
		}
	}
	return nil
}

func (x *WidgetState) GetIntArrayValue() *SInt64Array {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_IntArrayValue); ok {
			return x.IntArrayValue
		}
	}
	return nil
}

func (x *WidgetState) GetStringArrayValue() *StringArray {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_StringArrayValue); ok {
			return x.StringArrayValue
		}
	}
	return nil
}

func (x *WidgetState) GetJsonValue() string {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_JsonValue); ok {
			return x.JsonValue
		}
	}
	return ""
}

func (x *WidgetState) GetArrowValue() *ArrowTable {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_ArrowValue); ok {
			return x.ArrowValue
		}
	}
	return nil
}

func (x *WidgetState) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *WidgetState) GetFileUploaderStateValue() *FileUploaderState {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_FileUploaderStateValue); ok {
			return x.FileUploaderStateValue
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in streamlit/proto/WidgetStates.proto.
func (x *WidgetState) GetStringTriggerValue() *StringTriggerValue {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_StringTriggerValue); ok {
			return x.StringTriggerValue
		}
	}
	return nil
}

func (x *WidgetState) GetChatInputValue() *ChatInputValue {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_ChatInputValue); ok {
			return x.ChatInputValue
		}
	}
	return nil
}

func (x *WidgetState) GetJsonTriggerValue() string {
	if x != nil {
		if x, ok := x.Value.(*WidgetState_JsonTriggerValue); ok {
			return x.JsonTriggerValue
		}
	}
	return ""
}

type isWidgetState_Value interface {
	isWidgetState_Value()
}

type WidgetState_TriggerValue struct {
	// trigger_value is for buttons. A button's value needs to
	// auto-revert back to False after the script has been run with
	// the value set to True. After running the script, the server
	// will reset all trigger_values in its stored Widget state dict.
	// (Use bool_value for widgets like checkboxes, whose state persists
	// beyond a single script run.)
	TriggerValue bool `protobuf:"varint,2,opt,name=trigger_value,json=triggerValue,proto3,oneof"`
}

type WidgetState_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type WidgetState_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type WidgetState_IntValue struct {
	IntValue int64 `protobuf:"zigzag64,5,opt,name=int_value,json=intValue,proto3,oneof"`
}

type WidgetState_StringValue struct {
	StringValue string `protobuf:"bytes,6,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type WidgetState_DoubleArrayValue struct {
	DoubleArrayValue *DoubleArray `protobuf:"bytes,7,opt,name=double_array_value,json=doubleArrayValue,proto3,oneof"`
}

type WidgetState_IntArrayValue struct {
	IntArrayValue *SInt64Array `protobuf:"bytes,8,opt,name=int_array_value,json=intArrayValue,proto3,oneof"`
}

type WidgetState_StringArrayValue struct {
	StringArrayValue *StringArray `protobuf:"bytes,9,opt,name=string_array_value,json=stringArrayValue,proto3,oneof"`
}

type WidgetState_JsonValue struct {
	JsonValue string `protobuf:"bytes,10,opt,name=json_value,json=jsonValue,proto3,oneof"`
}

type WidgetState_ArrowValue struct {
	ArrowValue *ArrowTable `protobuf:"bytes,11,opt,name=arrow_value,json=arrowValue,proto3,oneof"`
}

type WidgetState_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,12,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type WidgetState_FileUploaderStateValue struct {
	FileUploaderStateValue *FileUploaderState `protobuf:"bytes,13,opt,name=file_uploader_state_value,json=fileUploaderStateValue,proto3,oneof"`
}

type WidgetState_StringTriggerValue struct {
	// DEPRECATED: StringTriggerValue proto message is deprecated and unused.
	// The ChatInputValue proto message should be used instead.
	//
	// Deprecated: Marked as deprecated in streamlit/proto/WidgetStates.proto.
	StringTriggerValue *StringTriggerValue `protobuf:"bytes,14,opt,name=string_trigger_value,json=stringTriggerValue,proto3,oneof"`
}

type WidgetState_ChatInputValue struct {
	// ChatInputValue resets itself to empty after the script has been run.
	// This is used for the chat_input widget.
	ChatInputValue *ChatInputValue `protobuf:"bytes,15,opt,name=chat_input_value,json=chatInputValue,proto3,oneof"`
}

type WidgetState_JsonTriggerValue struct {
	// Transient trigger payload transport (JSON-stringified).
	// - Purpose: carry per-run, non-persistent trigger data across the wire.
	// - Shape: JSON object or JSON array (batched within a single update).
	// - Lifecycle: treated as a trigger; cleared after each script run.
	// Use json_value for persistent state; use json_trigger_value for
	// auto-resetting payloads.
	JsonTriggerValue string `protobuf:"bytes,16,opt,name=json_trigger_value,json=jsonTriggerValue,proto3,oneof"`
}

func (*WidgetState_TriggerValue) isWidgetState_Value() {}

func (*WidgetState_BoolValue) isWidgetState_Value() {}

func (*WidgetState_DoubleValue) isWidgetState_Value() {}

func (*WidgetState_IntValue) isWidgetState_Value() {}

func (*WidgetState_StringValue) isWidgetState_Value() {}

func (*WidgetState_DoubleArrayValue) isWidgetState_Value() {}

func (*WidgetState_IntArrayValue) isWidgetState_Value() {}

func (*WidgetState_StringArrayValue) isWidgetState_Value() {}

func (*WidgetState_JsonValue) isWidgetState_Value() {}

func (*WidgetState_ArrowValue) isWidgetState_Value() {}

func (*WidgetState_BytesValue) isWidgetState_Value() {}

func (*WidgetState_FileUploaderStateValue) isWidgetState_Value() {}

func (*WidgetState_StringTriggerValue) isWidgetState_Value() {}

func (*WidgetState_ChatInputValue) isWidgetState_Value() {}

func (*WidgetState_JsonTriggerValue) isWidgetState_Value() {}

var File_streamlit_proto_WidgetStates_proto protoreflect.FileDescriptor

const file_streamlit_proto_WidgetStates_proto_rawDesc = "" +
	"\n" +
	"\"streamlit/proto/WidgetStates.proto\x1a\x1cstreamlit/proto/Common.proto\x1a streamlit/proto/Components.proto\"6\n" +
	"\fWidgetStates\x12&\n" +
	"\awidgets\x18\x01 \x03(\v2\f.WidgetStateR\awidgets\"\x8a\x06\n" +
	"\vWidgetState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\rtrigger_value\x18\x02 \x01(\bH\x00R\ftriggerValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fdouble_value\x18\x04 \x01(\x01H\x00R\vdoubleValue\x12\x1d\n" +
	"\tint_value\x18\x05 \x01(\x12H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x06 \x01(\tH\x00R\vstringValue\x12<\n" +
	"\x12double_array_value\x18\a \x01(\v2\f.DoubleArrayH\x00R\x10doubleArrayValue\x126\n" +
	"\x0fint_array_value\x18\b \x01(\v2\f.SInt64ArrayH\x00R\rintArrayValue\x12<\n" +
	"\x12string_array_value\x18\t \x01(\v2\f.StringArrayH\x00R\x10stringArrayValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\n" +
	" \x01(\tH\x00R\tjsonValue\x12.\n" +
	"\varrow_value\x18\v \x01(\v2\v.ArrowTableH\x00R\n" +
	"arrowValue\x12!\n" +
	"\vbytes_value\x18\f \x01(\fH\x00R\n" +
	"bytesValue\x12O\n" +
	"\x19file_uploader_state_value\x18\r \x01(\v2\x12.FileUploaderStateH\x00R\x16fileUploaderStateValue\x12K\n" +
	"\x14string_trigger_value\x18\x0e \x01(\v2\x13.StringTriggerValueB\x02\x18\x01H\x00R\x12stringTriggerValue\x12;\n" +
	"\x10chat_input_value\x18\x0f \x01(\v2\x0f.ChatInputValueH\x00R\x0echatInputValue\x12.\n" +
	"\x12json_trigger_value\x18\x10 \x01(\tH\x00R\x10jsonTriggerValueB\a\n" +
	"\x05valueB3Z1github.com/stevenblair/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_WidgetStates_proto_rawDescOnce sync.Once
	file_streamlit_proto_WidgetStates_proto_rawDescData []byte
)

func file_streamlit_proto_WidgetStates_proto_rawDescGZIP() []byte {
	file_streamlit_proto_WidgetStates_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_WidgetStates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_WidgetStates_proto_rawDesc), len(file_streamlit_proto_WidgetStates_proto_rawDesc)))
	})
	return file_streamlit_proto_WidgetStates_proto_rawDescData
}

var file_streamlit_proto_WidgetStates_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streamlit_proto_WidgetStates_proto_goTypes = []any{
	(*WidgetStates)(nil),       // 0: WidgetStates
	(*WidgetState)(nil),        // 1: WidgetState
	(*DoubleArray)(nil),        // 2: DoubleArray
	(*SInt64Array)(nil),        // 3: SInt64Array
	(*StringArray)(nil),        // 4: StringArray
	(*ArrowTable)(nil),         // 5: ArrowTable
	(*FileUploaderState)(nil),  // 6: FileUploaderState
	(*StringTriggerValue)(nil), // 7: StringTriggerValue
	(*ChatInputValue)(nil),     // 8: ChatInputValue
}
var file_streamlit_proto_WidgetStates_proto_depIdxs = []int32{
	1, // 0: WidgetStates.widgets:type_name -> WidgetState
	2, // 1: WidgetState.double_array_value:type_name -> DoubleArray
	3, // 2: WidgetState.int_array_value:type_name -> SInt64Array
	4, // 3: WidgetState.string_array_value:type_name -> StringArray
	5, // 4: WidgetState.arrow_value:type_name -> ArrowTable
	6, // 5: WidgetState.file_uploader_state_value:type_name -> FileUploaderState
	7, // 6: WidgetState.string_trigger_value:type_name -> StringTriggerValue
	8, // 7: WidgetState.chat_input_value:type_name -> ChatInputValue
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_streamlit_proto_WidgetStates_proto_init() }
func file_streamlit_proto_WidgetStates_proto_init() {
	if File_streamlit_proto_WidgetStates_proto != nil {
		return
	}
	file_streamlit_proto_Common_proto_init()
	file_streamlit_proto_Components_proto_init()
	file_streamlit_proto_WidgetStates_proto_msgTypes[1].OneofWrappers = []any{
		(*WidgetState_TriggerValue)(nil),
		(*WidgetState_BoolValue)(nil),
		(*WidgetState_DoubleValue)(nil),
		(*WidgetState_IntValue)(nil),
		(*WidgetState_StringValue)(nil),
		(*WidgetState_DoubleArrayValue)(nil),
		(*WidgetState_IntArrayValue)(nil),
		(*WidgetState_StringArrayValue)(nil),
		(*WidgetState_JsonValue)(nil),
		(*WidgetState_ArrowValue)(nil),
		(*WidgetState_BytesValue)(nil),
		(*WidgetState_FileUploaderStateValue)(nil),
		(*WidgetState_StringTriggerValue)(nil),
		(*WidgetState_ChatInputValue)(nil),
		(*WidgetState_JsonTriggerValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_WidgetStates_proto_rawDesc), len(file_streamlit_proto_WidgetStates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_WidgetStates_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_WidgetStates_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_WidgetStates_proto_msgTypes,
	}.Build()
	File_streamlit_proto_WidgetStates_proto = out.File
	file_streamlit_proto_WidgetStates_proto_goTypes = nil
	file_streamlit_proto_WidgetStates_proto_depIdxs = nil
}
