//*!
// Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2026)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: streamlit/proto/WidthConfig.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WidthConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to WidthSpec:
	//
	//	*WidthConfig_UseStretch
	//	*WidthConfig_UseContent
	//	*WidthConfig_PixelWidth
	//	*WidthConfig_RemWidth
	WidthSpec     isWidthConfig_WidthSpec `protobuf_oneof:"width_spec"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidthConfig) Reset() {
	*x = WidthConfig{}
	mi := &file_streamlit_proto_WidthConfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidthConfig) ProtoMessage() {}

func (x *WidthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_streamlit_proto_WidthConfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidthConfig.ProtoReflect.Descriptor instead.
func (*WidthConfig) Descriptor() ([]byte, []int) {
	return file_streamlit_proto_WidthConfig_proto_rawDescGZIP(), []int{0}
}

func (x *WidthConfig) GetWidthSpec() isWidthConfig_WidthSpec {
	if x != nil {
		return x.WidthSpec
	}
	return nil
}

func (x *WidthConfig) GetUseStretch() bool {
	if x != nil {
		if x, ok := x.WidthSpec.(*WidthConfig_UseStretch); ok {
			return x.UseStretch
		}
	}
	return false
}

func (x *WidthConfig) GetUseContent() bool {
	if x != nil {
		if x, ok := x.WidthSpec.(*WidthConfig_UseContent); ok {
			return x.UseContent
		}
	}
	return false
}

func (x *WidthConfig) GetPixelWidth() uint32 {
	if x != nil {
		if x, ok := x.WidthSpec.(*WidthConfig_PixelWidth); ok {
			return x.PixelWidth
		}
	}
	return 0
}

func (x *WidthConfig) GetRemWidth() float32 {
	if x != nil {
		if x, ok := x.WidthSpec.(*WidthConfig_RemWidth); ok {
			return x.RemWidth
		}
	}
	return 0
}

type isWidthConfig_WidthSpec interface {
	isWidthConfig_WidthSpec()
}

type WidthConfig_UseStretch struct {
	UseStretch bool `protobuf:"varint,1,opt,name=use_stretch,json=useStretch,proto3,oneof"`
}

type WidthConfig_UseContent struct {
	UseContent bool `protobuf:"varint,2,opt,name=use_content,json=useContent,proto3,oneof"`
}

type WidthConfig_PixelWidth struct {
	PixelWidth uint32 `protobuf:"varint,3,opt,name=pixel_width,json=pixelWidth,proto3,oneof"`
}

type WidthConfig_RemWidth struct {
	RemWidth float32 `protobuf:"fixed32,4,opt,name=rem_width,json=remWidth,proto3,oneof"`
}

func (*WidthConfig_UseStretch) isWidthConfig_WidthSpec() {}

func (*WidthConfig_UseContent) isWidthConfig_WidthSpec() {}

func (*WidthConfig_PixelWidth) isWidthConfig_WidthSpec() {}

func (*WidthConfig_RemWidth) isWidthConfig_WidthSpec() {}

var File_streamlit_proto_WidthConfig_proto protoreflect.FileDescriptor

const file_streamlit_proto_WidthConfig_proto_rawDesc = "" +
	"\n" +
	"!streamlit/proto/WidthConfig.proto\x12\tstreamlit\"\xa3\x01\n" +
	"\vWidthConfig\x12!\n" +
	"\vuse_stretch\x18\x01 \x01(\bH\x00R\n" +
	"useStretch\x12!\n" +
	"\vuse_content\x18\x02 \x01(\bH\x00R\n" +
	"useContent\x12!\n" +
	"\vpixel_width\x18\x03 \x01(\rH\x00R\n" +
	"pixelWidth\x12\x1d\n" +
	"\trem_width\x18\x04 \x01(\x02H\x00R\bremWidthB\f\n" +
	"\n" +
	"width_specB1Z/github.com/streamlit/streamlit/go-backend/protob\x06proto3"

var (
	file_streamlit_proto_WidthConfig_proto_rawDescOnce sync.Once
	file_streamlit_proto_WidthConfig_proto_rawDescData []byte
)

func file_streamlit_proto_WidthConfig_proto_rawDescGZIP() []byte {
	file_streamlit_proto_WidthConfig_proto_rawDescOnce.Do(func() {
		file_streamlit_proto_WidthConfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamlit_proto_WidthConfig_proto_rawDesc), len(file_streamlit_proto_WidthConfig_proto_rawDesc)))
	})
	return file_streamlit_proto_WidthConfig_proto_rawDescData
}

var file_streamlit_proto_WidthConfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamlit_proto_WidthConfig_proto_goTypes = []any{
	(*WidthConfig)(nil), // 0: streamlit.WidthConfig
}
var file_streamlit_proto_WidthConfig_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streamlit_proto_WidthConfig_proto_init() }
func file_streamlit_proto_WidthConfig_proto_init() {
	if File_streamlit_proto_WidthConfig_proto != nil {
		return
	}
	file_streamlit_proto_WidthConfig_proto_msgTypes[0].OneofWrappers = []any{
		(*WidthConfig_UseStretch)(nil),
		(*WidthConfig_UseContent)(nil),
		(*WidthConfig_PixelWidth)(nil),
		(*WidthConfig_RemWidth)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamlit_proto_WidthConfig_proto_rawDesc), len(file_streamlit_proto_WidthConfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamlit_proto_WidthConfig_proto_goTypes,
		DependencyIndexes: file_streamlit_proto_WidthConfig_proto_depIdxs,
		MessageInfos:      file_streamlit_proto_WidthConfig_proto_msgTypes,
	}.Build()
	File_streamlit_proto_WidthConfig_proto = out.File
	file_streamlit_proto_WidthConfig_proto_goTypes = nil
	file_streamlit_proto_WidthConfig_proto_depIdxs = nil
}
